### ISSUE TITLE
Marker

### ISSUE THREAD

**Issue by Weeeishy** [shanapu/MyJailbreak#1]
I still can't figure out how to get the marker work!

**Comment by shanapu** [comment]
`sm_warden_marker "1"` to enable marker for warden.

`sm_warden_markerkey "1"`
aim to a position and just press the **+lookatweapon** Button. Default CS:GO-Key is "**F**"  
  
`sm_warden_markerkey "2"`
aim to a position and press the **+use** Button and shot your gun.  Default CS:GO-Key is "**E**"  
  
if `sm_warden_markerkey "3"`
aim to a position and press the **+speed** Button and shot your gun.  Default CS:GO-Key is "**SHIFT**"  
  
![screenshot](http://shanapu.de/marker.jpg)

**Comment by shanapu** [comment]
if it is desired, i could make a Console Command like `sm_marker` to spawn marker.

**Comment by Weeeishy** [comment]
Thank you very much!

**Comment by shanapu** [comment]
I added with one of the recent updates a new Marker. Zipcores Advanced Marker.
Here is a little howto video

[![HowTo Marker](http://img.youtube.com/vi/tp6k_Q6K37c/0.jpg)](http://www.youtube.com/watch?v=tp6k_Q6K37c)

http://www.youtube.com/watch?v=tp6k_Q6K37c
