### ISSUE TITLE
Zombi: Does not install the skin.

### ISSUE THREAD

**Issue by mrkos9i4ok** [shanapu/MyJailbreak#100]
When you start zombie day,CT is the skin that you put in .
Way to jump the normal and in the config also all ordered.

**Comment by good-live** [comment]
Same problem here. I really don't get your message. Could you please try to express clearly?

**Comment by mrkos9i4ok** [comment]
Starts zombie day.In fact all ct must receive a skin of a zombie,but this is not happening.

**Comment by shanapu** [comment]
On Zombie Day Round Start all CT get a Zombie skin set in `sm_zombie_model` 

It's very hard to understand you in all your requests.
Please, mrkos9i4ok try to explain your problems more detailed in better English. 
I know it's hard to learn a new language. Try to use different translators, don't copy paste a translation without a recheck. Ask a friend who speaks english, maybe he can correct you.
I'm sorry, but I getting crazy with some of your posts...

What is the exact problem?`

No CT get a Zombie Skin? All stay CT?
Some CT get A Zombie Skin but not all?
There are BIG error boxes everywhere? 
Do you have a error log to this problem?
Do the client download of the models on server connect work? -> FastDL

**Comment by mrkos9i4ok** [comment]
![20160809025333_1](https://cloud.githubusercontent.com/assets/20227450/17500274/c193b780-5ddc-11e6-92fe-53d4561f0a77.jpg)
Protection zombie skin is not given to terrorists over their normal skin is a standard yet.

**Comment by shanapu** [comment]
ok, I see.
I used an older version of sm_skinchooser. I will hook the models on Post round start. Fixed coming soon

**Comment by shanapu** [comment]
this also happens on duckhunt... fixed with next update
