### ISSUE TITLE
Warden: noblock

### ISSUE THREAD

**Issue by mrkos9i4ok** [shanapu/MyJailbreak#101]
I wanted to put the default noblock to 0,but I could not find this in the config and when you type in the console writes:

>L 08/04/2016 - 12:35:08: [SM] Exception reported: Invalid client index 0
L 08/04/2016 - 12:35:08: [SM] Blaming: MyJailbreak/warden.smx()
L 08/04/2016 - 12:35:08: [SM] Call stack trace:
L 08/04/2016 - 12:35:08: [SM]   [0] ThrowError
L 08/04/2016 - 12:35:08: [SM]   [1] Line 67, D:\Code\MyJailbreak\addons\sourcemod\scripting\include\colors.inc::CPrintToChat()
L 08/04/2016 - 12:35:08: [SM]   [2] Line 104, MyJailbreak/Modules/Warden/noblock.sp::Command_ToggleNoBlock()

**Comment by good-live** [comment]
This is not a console command, as you need to be the warden to use it. However the error shouldn't occure.

**Comment by mrkos9i4ok** [comment]
With the revival of the players included noblac,and I wish that it was turned off.

**Comment by good-live** [comment]
?  What are you trying to say. I don't really get your point.

**Comment by mrkos9i4ok** [comment]
Inmates pass through each other,I want to prevent it.So initially they could not pass through each other.

**Comment by good-live** [comment]
This plugin only affects the collisionGroup on command use. The initial noblock seems to be controlled by another of your Plugins like hosties?
