### ISSUE TITLE
Ratio: Cooldown/ctban on wrong guard question

### ISSUE THREAD

**Issue by mrkos9i4ok** [shanapu/MyJailbreak#104]
To make it so that it was impossible to endlessly poke at answers,if not answered correctly,then the next attempt until the next round.

**Comment by mrkos9i4ok** [comment]
Refusing to add reasons for the refusal.

**Comment by shanapu** [comment]
> To make it so that it was impossible to endlessly poke at answers,if not answered correctly,then the next attempt until the next round.

Yeah I will do this and maybe connect with a ban of databombs CT Ban if it is running.

> Refusing to add reasons for the refusal.
What?

And again, and again and again... PLEASE mrkos9i4ok try to explain more exactly with more detail... remember always ONE issue/request per New Issue Post. And also make more useful topics!
