### ISSUE TITLE
Warden: quiz  doesn`t work

### ISSUE THREAD

**Issue by mrkos9i4ok** [shanapu/MyJailbreak#106]
![20160811063045_1](https://cloud.githubusercontent.com/assets/20227450/17578070/81437d84-5f8d-11e6-81ed-47c2ecbb7687.jpg)

**Comment by shanapu** [comment]
I'm sorry. I can't reproduce it either any other admin I asked have this problem...

does it happend everytime? does it happend to all player?

![math](https://cloud.githubusercontent.com/assets/7787074/17603083/d5efc0f4-600f-11e6-8a3e-1d08a33735fd.png)

**Comment by mrkos9i4ok** [comment]
Doesn't work when you writes to the general chat when you writes to a command chat when you are an administrator when the VIP when the simple player, doesn't see at all.

**Comment by shanapu** [comment]
tested several times with friends with and without flags.
Never had this problem... I also asked some other server admins... also not notice this issue.
Could you post your plugin list or do you know about a plugin that manipulates the chat? like simplechatprozessor?

**Comment by mrkos9i4ok** [comment]
[SM] Listing 94 plugins:
  01 "[CS:GO] SpawnTools7" (1.0.1)
  02 "SM_Hosties v2" (2.2.3)
  03 "Thirdperson Mode" (2.2) by Zephyrus & Justkasi
  04 "Basic Chat" (1.8.0.5916) by AlliedModders LLC
  05 "Smart Jail Doors" (0.5.2-beta)
  06 "[Shop] Core" (2.0.22) by FrozDark
  07 "SourceBans++" (1.5.4.6) by SourceBans Development Team, Sarabveer(VEER), NoTiCE
  08 "Basic Info Triggers" (1.8.0.5916) by AlliedModders LLC
  09 "HostName Rus" (1.0.0) by GoDtm666
  10 "Rock The Vote Extended" (1.10.0)
  11 "SourceComms" ((SB++) 1.5.4.6) by Alex, Sarabveer(VEER)
  12 "[Shop] Paintball" (2.1.1) by FrozDark (HLModders LLC)
  13 "Player Commands" (1.8.0.5916) by AlliedModders LLC
  14 "Last Request: Backstabs" (1.0.3) by Jason Bourne & Kolapsicle
  15 "Admin Help" (1.8.0.5916) by AlliedModders LLC
  16 "Disable HUD money" (1.0) by Pheonix (‰7Феникс7‰)
  17 "Team Names" (1.1) by Internet Bully
  18 "[KDLP] Game Events" (1.0.1) by KorDen
  19 "Admin Menu" (1.8.0.5916) by AlliedModders LLC
  20 "CT Ban" (1.6.1.3) by databomb(Changed Forever(Skype: barstis7)
  21 "SourceBans: Admin Config Loader" ((SB++) 1.5.5-dev) by AlliedModders LLC
  22 "SourceBans Checker" ((SB++) 1.5.4.6) by psychonic, Ca$h Munny, Sarabveer(VEER)
  23 "[VIP] Regen HP" (1.0.4) by R1KO
  24 "[VIP] Vampirism" (1.0.2) by R1KO
  25 "[VIP] Bhop" (1.0.0) by KOROVKA
  26 "[VIP] Admin Privileges" (1.0.2) by R1KO (skype: vova.andrienko1)
  27 "[VIP] HP" (1.0.0) by R1KO (skype: vova.andrienko1)
  28 "[VIP] Top Icon" (1.0.0) by R1KO
  29 "[VIP] Keys" (1.0.2) by R1KO (skype: vova.andrienko1)
  30 "[VIP] Armor" (1.0.1) by R1KO (skype: vova.andrienko1)
  31 "[VIP] Vips Online" (1.0.1) by R1KO (skype: vova.andrienko1)
  32 "[VIP] Core" (2.0.1 DEV (build 220314-1)) by R1KO (skype: vova.andrienko1)
  33 "[VIP] Gravity" (1.0.0) by R1KO (skype: vova.andrienko1)
  34 "[VIP] Trails (CS:GO)" (1.0.0) by R1KO
  35 "Admin File Reader" (1.8.0.5916) by AlliedModders LLC
  36 "Anti-Flood" (1.8.0.5916) by AlliedModders LLC
  37 "CSGO Sprays" (1.4.1) by 
  38 "[Shop] Money Distributor" (1.4.3) by FrozDark (HLModders LLC)
  39 "[Shop] Top10 Function" (2.0.1) by FrozDark
  40 "Basic Commands" (1.8.0.5916) by AlliedModders LLC
  41 "Fun Commands" (1.8.0.5916) by AlliedModders LLC
  42 "Mirror" (1.0) by Franc1sco franug and Nanochip
  43 "Default SM Text Replacer" (0.32.GO) by Mitch/Bacardi
  44 "Player Cleaner" (1.0) by White Wolf (HLModders LLC)
  45 "Voice Comm" (2.2.1) by databomb
  46 "Client Preferences" (1.8.0.5916) by AlliedModders LLC
  47 "Basic Votes" (1.8.0.5916) by AlliedModders LLC
  48 "Last Request: Max Damage" (1.0.3) by Jason Bourne & Kolapsicle
  49 "[VIP] LR Off (PRIVATE)" (1.0) by White Wolf & R1KO
  50 "CS:GO Slots fix" (1.0.0) by www.MyArena.ru
  51 "[Shop] Skins" (2.1.0) by FrozDark (arms by R1KO)
  52 "MapChooser Extended" (1.10.2) by Powerlord, Zuko
  53 "Реклама" (1.2) by Pheonix (‰7Феникс7‰)
  54 "[Shop] Online Credits" (1.2) by White Wolf (HLModders LLC)
  55 "SM Speaker Icon" (2.0) by Franc1sco steam: franug
  56 "Basic Comm Control" (1.8.0.5916) by AlliedModders LLC
  57 "stacker" (1.0) 
  58 "Multiple player boost " (1.00) by boomix
  59 "VoiceAnnounceEx" (2.1.1) by Franc1sco franug, Mini and GoD-Tony
  60 "Map Nominations Extended" (1.10.0) by 
  61 "Custom Player Skins (Core)" (1.3.4) by Mitchell, Root
  62 "[Shop] Logs" (1.1) by R1KO (skype: vova.andrienko1)
  63 "Rotate server graphic banners" (0.2) by HiTmAnY
  64 "Last Request: HE Battle" (1.0.2) by Jason Bourne & Kolapsicle
  65 "Radio" (2.0.2)
  66 "[Shop] Pets" (1.0) by Pheonix & Zephyrus
  67 "Last Request: Quick Hands" (1.0.1) by Jason Bourne & Kolapsicle
  68 "SourceSleuth" ((SB++) 1.5.4.6) by ecca, Sarabveer(VEER)
  69 "MyJailbreak - NoScope" (Beta 7.1) by shanapu
  70 "MyJailbreak - Core" (Beta 7.1) by shanapu
  71 "MyJailbreak - Weapons" (Beta 7.1) by shanapu, Franc1sco
  72 "MyJailbreak - Warden" (Beta 7.1) by shanapu, ecca, ESKO & .#zipcore
  73 "MyJailbreak - CowBoy" (Beta 7.1) by shanapu
  74 "MyJailbreak - DealDamage" (Beta 7.1) by shanapu
  75 "MyJailbreak - Suicide Bomber" (Beta 7.1) by shanapu
  76 "MyJailbreak - HideInTheDark" (Beta 7.1) by shanapu
  77 "MyJailbreak - KnifeFight" (Beta 7.1) by shanapu
  78 "MyJailbreak - PlayerTags" (Beta 7.1) by shanapu
  79 "MyJailbreak - Zeus" (Beta 7.1) by shanapu
  80 "MyJailbreak - War FFA" (Beta 7.1) by shanapu
  81 "MyJailbreak - Ratio" (Beta 7.1) by shanapu, Addicted
  82 "MyJailbreak - Torch Relay" (Beta 7.1) by shanapu
  83 "MyJailbreak - Last Guard Rule" (Beta 7.1) by shanapu
  84 "MyJailbreak - DuckHunt" (Beta 7.1) by shanapu
  85 "MyJailbreak - Drunk" (Beta 7.1) by shanapu
  86 "MyJailbreak - War" (Beta 7.1) by shanapu
  87 "MyJailbreak - Player HUD" (Beta 7.1) by shanapu
  88 "MyJailbreak - Zombie" (Beta 7.1) by shanapu
  89 "MyJailbreak - Freeday" (Beta 7.1) by shanapu
  90 "MyJailbreak - Catch & Freeze" (Beta 7.1) by shanapu
  91 "MyJailbreak - Request" (Beta 7.1) by shanapu
  92 "MyJailbreak - HE Battle" (Beta 7.1) by shanapu
  93 "Skins" (1.6)
  94 "MyJailbreak - Menus" (Beta 7.1) by shanapu, Franc1sco

**Comment by mrkos9i4ok** [comment]
The problem was solved after installation
https://forums.alliedmods.net/showthread.php?p=1820365

**Comment by shanapu** [comment]
thanks for telling the solution. I haven't think about it. required plugins
