### ISSUE TITLE
Ratio: Error

### ISSUE THREAD

**Issue by mrkos9i4ok** [shanapu/MyJailbreak#107]
L 08/11/2016 - 06:53:44: [SM] Blaming: MyJailbreak/ratio.smx()
L 08/11/2016 - 06:53:44: [SM] Call stack trace:
L 08/11/2016 - 06:53:44: [SM]   [0] VFormat
L 08/11/2016 - 06:53:44: [SM]   [1] Line 78, D:\Code\MyJailbreak\addons\sourcemod\scripting\include\colors.inc::CPrintToChat()
L 08/11/2016 - 06:53:44: [SM]   [2] Line 526, MyJailbreak/ratio.sp::AddToQueue()
L 08/11/2016 - 06:53:44: [SM]   [3] Line 288, MyJailbreak/ratio.sp::Command_JoinGuardQueue()

**Comment by mrkos9i4ok** [comment]
The problem consists in new translate.
With old everything works.

**Comment by good-live** [comment]
This is just the call stack trace. Would you be so kind to post the error aswell?

**Comment by mrkos9i4ok** [comment]
L 08/11/2016 - 06:53:14: [SM] Exception reported: Language phrase "ratio_question_title" not found
L 08/11/2016 - 06:58:01: [SM] Exception reported: Language phrase "ratio_tag" not found

**Comment by shanapu** [comment]
both is there... 

"ratio_question_title"
https://github.com/shanapu/MyJailbreak/blob/master/addons/sourcemod/translations/MyJailbreak.Ratio.phrases.txt#L166

"ratio_tag" 
https://github.com/shanapu/MyJailbreak/blob/master/addons/sourcemod/translations/MyJailbreak.Ratio.phrases.txt#L105

**Comment by mrkos9i4ok** [comment]
They are in the translator, I don't know why so.

**Comment by shanapu** [comment]
there is a 'lil gap:

> L 08/11/2016 - **06:53:14**: [SM] Exception reported: Language phrase "ratio_question_title" not found
> L 08/11/2016 - **06:53:44**: [SM] Blaming: MyJailbreak/ratio.smx()


06:53:14 & 06:53:44  normal a error dont need 30seconds. you sure you posted the right/full log?

**Comment by mrkos9i4ok** [comment]
`L 08/12/2016 - 09:58:59: [SM] Exception reported: Language phrase "ratio_tag" not found
L 08/12/2016 - 09:58:59: [SM] Blaming: MyJailbreak/ratio.smx()
L 08/12/2016 - 09:58:59: [SM] Call stack trace:
L 08/12/2016 - 09:58:59: [SM]   [0] VFormat
L 08/12/2016 - 09:58:59: [SM]   [1] Line 174, D:\Code\MyJailbreak\addons\sourcemod\scripting\include\colors.inc::CPrintToChatAll()
L 08/12/2016 - 09:58:59: [SM]   [2] Line 916, MyJailbreak/ratio.sp::FixTeamRatio()
L 08/12/2016 - 09:58:59: [SM]   [3] Line 413, MyJailbreak/ratio.sp::Event_RoundEnd_Post()
L 08/12/2016 - 09:58:59: [SM]   [5] ForcePlayerSuicide
L 08/12/2016 - 09:58:59: [SM]   [6] Line 199, hosties/gunsafety.sp::PerformSlay()
L 08/12/2016 - 09:58:59: [SM]   [7] Line 270, hosties/gunsafety.sp::MenuHandler_Slay()
L 08/12/2016 - 09:59:02: [SM] Exception reported: Language phrase "ratio_question_title" not found
L 08/12/2016 - 09:59:02: [SM] Blaming: MyJailbreak/ratio.smx()
L 08/12/2016 - 09:59:02: [SM] Call stack trace:
L 08/12/2016 - 09:59:02: [SM]   [0] Format
L 08/12/2016 - 09:59:02: [SM]   [1] Line 688, MyJailbreak/ratio.sp::Menu_GuardQuestions()
L 08/12/2016 - 09:59:02: [SM]   [2] Line 484, MyJailbreak/ratio.sp::Event_OnJoinTeam()`

**Comment by shanapu** [comment]
oh, i think it should be this https://github.com/shanapu/MyJailbreak/pull/108 
make a change on line 21 in translation.phrases.txt 
https://github.com/shanapu/MyJailbreak/pull/108/commits/79c7186a981cf2e163b14687865f24b51ae9c4c5 this could be your error

**Comment by shanapu** [comment]
my fault... was fixed by Kailo97 but new RU translation rebroke it. fixed with 7.1
