### ISSUE TITLE
Warden Icons don't work if sm_warden_icon_ct_enable is 0

### ISSUE THREAD

**Issue by devu4** [shanapu/MyJailbreak#109]
Ok I set it so sm_warden_icon_ct_enable is 0 so CTs don't get icons but this also stops wardens getting icons.

it can be fixed by adding this in icon.sp
Change: line 206
https://i.gyazo.com/433638003e9c6694d9948f1a204df8b9.png

Replace with:
https://i.gyazo.com/9590c9f463f4506e29dddfca629fc9bc.png

**Comment by shanapu** [comment]
thx!
