### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by DamrosRak** [shanapu/MyJailbreak#110]
I tried your plugin on my server and all the models are messed,I can't open the menu,basically everything is not working,what should I do?

**Comment by shanapu** [comment]
first use a better topic cause MyJailbreak does work!

type 'sm plugins list' into server console to see if everything is loaded.

go to ...csgo/addons/sourcemod/logs and see whats in the error files

**Comment by devu4** [comment]
Pretty sure you don't have the translations in your server.

**Comment by DamrosRak** [comment]
Unable to load plugin "MyJailbreak/zeus.smx": Could not find required plugin "lastrequest"
this is just one,it does this thing to all the .smx files
Displaying call stack trace for plugin "RandomPlayerModels.smx":
[0]  Line 94, D:\ScriptsGit\Custom-Player-Skins\scripting\RandomPlayerModels.sp::KeyValue()
Plugin encountered error 15: Array index is out of bounds

**Comment by shanapu** [comment]
> Unable to load plugin "MyJailbreak/zeus.smx": **Could not find required plugin "lastrequest"**

You missed step 1. of install instruction https://github.com/shanapu/MyJailbreak/wiki/Installation

> Displaying call stack trace for plugin "RandomPlayerModels.smx"

You don't need RandomPlayerModels.smx
