### ISSUE TITLE
Make Catch better

### ISSUE THREAD

**Issue by devu4** [shanapu/MyJailbreak#111]
Catch should be changed so that Ts get to hide for 30 seconds, Cts are frozen, 

If a prisoner is caught twice they should die, you could create a cvar for this so people can pick how may times to be tagged before death.

Then enable LR and Beacon for this day. I think this would make the day better as a T will win and CTs have a chance to win too. Right now, it is near impossible for CTs to win.

**Comment by shanapu** [comment]
I like the idea of a terror get killed on 'second' catch. 
but I don't like the freeze time. So it would be very similar to zombie & hide. 

I consider something like a 'reason' for the Ts to stay near the CT,..
...maybe a terror must first knife the CT (in the back) 'to get the keys' before he can free another Terror
...maybe a terror must first stay for x seconds in CT (or catched T) near (radius) to free him.
...maybe there is only one (or more) Terrors who can free others. If 'the one' get catched, the game ends or new player get "the one". 

even if I don't like the freeze time I will include it with cvar.

**Comment by devu4** [comment]
Yeah I think it will be good if you make cvar for if caught more that x times you die. 
I don't think a reason to stay near ct is needed. And remove sprint cooldown on CT

I don't want reason because on my server I allow everyone to go anywhere in the map. Thats why I want the beacon to be added to after x time.

**Comment by shanapu** [comment]
>  cvar for if caught more that x times you die.   

sm_catch_count

> And remove sprint cooldown on CT

done

**Comment by shanapu** [comment]
forget the half... 

> Catch should be changed so that Ts get to hide for 30 seconds, Cts are frozen...
> Then enable LR and Beacon for this day...

**Comment by shanapu** [comment]
how about wallhack(glow) for CTs to see only freezed/catched Ts?

**Comment by devu4** [comment]
I think add that with cvar but beacon is one that is needed, And thanks for doing the count.

**Comment by shanapu** [comment]
done
