### ISSUE TITLE
Where do i download the latest Sm_hosties?

### ISSUE THREAD

**Issue by DamrosRak** [shanapu/MyJailbreak#112]
I can just find sm_hosties v2.2.0
Where I can find sm_hosties v2.2.3?

**Comment by shanapu** [comment]
Go to https://github.com/dataviruset/sm-hosties/
left side below the commits, change the branch to 'beta'.
right side 'clone or download' -> 'Download ZIP'

https://github.com/dataviruset/sm-hosties/archive/beta.zip

**Comment by DamrosRak** [comment]
I still have that error

**Comment by shanapu** [comment]
what error? my magic glas ball is broken...

**Comment by DamrosRak** [comment]
Unable to load plugin "MyJailbreak/zeus.smx": Could not find required plugin "lastrequest"

**Comment by shanapu** [comment]
`sm plugin list` in server console
is hosties loaded?

**Comment by DamrosRak** [comment]
yeah

**Comment by shanapu** [comment]
how about you try to give some more infos? like your plugin list, your full error logs, your sm version.....

....my magic glass ball is still broken -.-

**Comment by Include5** [comment]
Hello! My magic glass ball is working! Based on your nick i think you know the Russian language, you can add me on Skype zerald20. I'll try to help you

**Comment by shanapu** [comment]
> Hello! My magic glass ball is working! 

What does it say?

**Comment by DamrosRak** [comment]
I have all of the requires plugins,I have sourcemod 1.8.0 and I can't give you right now the full error logs because I'm not at home and I'm using my phone
And I'm not Russian
