### ISSUE TITLE
Could not find required plugin "voiceannounce_ex" | Native "warden_iswarden" was not found

### ISSUE THREAD

**Issue by krysti500** [shanapu/MyJailbreak#113]
After update to 7.0 or 7.1 i have errors

L 08/18/2016 - 23:29:20: [SM] Unable to load plugin "MyJailbreak/warden.smx": Could not find required plugin "voiceannounce_ex"
L 08/18/2016 - 23:29:20: [SM] Unable to load plugin "MyJailbreak/zeus.smx": Native "warden_iswarden" was not found

I have all files installed i'm try on sourcemod 1.7 and 1.8

**Comment by shanapu** [comment]
The error tells you what to do...
`Could not find **required plugin** "**voiceannounce_ex**"`

Since Beta 7.0 there a to new requirements:

> New Requirements
> [ANY] **VoiceannounceEX** (VoiceHook) - https://forums.alliedmods.net/showthread.php?p=2177167
> DHooks (Dynamic Hooks - Dev Preview) - https://forums.alliedmods.net/showthread.php?t=180114

**Comment by krysti500** [comment]
I have this installed

**Comment by shanapu** [comment]
does is loaded correctly?   
`sm plugins list` in server console. Any other errors?
