### ISSUE TITLE
Problem with install

### ISSUE THREAD

**Issue by krysti500** [shanapu/MyJailbreak#114]
My next try :/

I try to install version 7.0 or 7.1 i installed all new plugins!

I try install plugins and MyJailbreak on sm 1.7 and 1.8 and i have error 

L 08/18/2016 - 23:29:20: [SM] Unable to load plugin "MyJailbreak/warden.smx": Could not find required plugin "voiceannounce_ex"
L 08/18/2016 - 23:29:20: [SM] Unable to load plugin "MyJailbreak/zeus.smx": Native "warden_iswarden" was not found

Or any logs! 

I INSTALLED ALL NEW PLUGINS!

VoiceannounceEX and DHooks (Dynamic Hooks - Dev Preview) 

And this plugins work!

**Comment by Include5** [comment]
sm plugins list

**Comment by krysti500** [comment]
From MyJailBreak Pack only Core and Last Guard

**Comment by krysti500** [comment]
After bilion reinstalls i get new errors

L 08/19/2016 - 20:23:38: [SM] Unable to load plugin "MyJailbreak/war.smx": Native "warden_iswarden" was not found
L 08/19/2016 - 20:23:38: [SM] Unable to load plugin "MyJailbreak/ratio.smx": Native "warden_iswarden" was not found
L 08/19/2016 - 20:23:38: [SM] Unable to load plugin "MyJailbreak/request.smx": Native "warden_iswarden" was not found
L 08/19/2016 - 20:23:38: [SM] Unable to load plugin "MyJailbreak/hebattle.smx": Native "warden_iswarden" was not found
L 08/19/2016 - 20:23:38: [SM] Unable to load plugin "MyJailbreak/cowboy.smx": Native "warden_iswarden" was not found
L 08/19/2016 - 20:23:38: [SM] Unable to load plugin "MyJailbreak/hud.smx": Native "warden_get" was not found
L 08/19/2016 - 20:23:38: [SM] Unable to load plugin "MyJailbreak/playertags.smx": Native "warden_iswarden" was not found
L 08/19/2016 - 20:23:38: [SM] Unable to load plugin "MyJailbreak/weapons.smx": Native "warden_iswarden" was not found
L 08/19/2016 - 20:23:38: [SM] Unable to load plugin "MyJailbreak/dealdamage.smx": Native "warden_iswarden" was not found
L 08/19/2016 - 20:23:38: [SM] Unable to load plugin "MyJailbreak/suicide.smx": Native "warden_iswarden" was not found
L 08/19/2016 - 20:23:38: [SM] Unable to load plugin "MyJailbreak/menu.smx": Native "warden_iswarden" was not found
L 08/19/2016 - 20:23:38: [SM] Unable to load plugin "MyJailbreak/drunk.smx": Native "warden_iswarden" was not found
L 08/19/2016 - 20:23:38: [SM] Unable to load plugin "MyJailbreak/noscope.smx": Native "warden_iswarden" was not found
L 08/19/2016 - 20:23:38: [SM] Unable to load plugin "MyJailbreak/duckhunt.smx": Native "warden_iswarden" was not found
L 08/19/2016 - 20:23:38: [SM] Unable to load plugin "MyJailbreak/zombie.smx": Native "warden_iswarden" was not found
L 08/19/2016 - 20:23:38: [SM] Unable to load plugin "MyJailbreak/catch.smx": Native "warden_iswarden" was not found
L 08/19/2016 - 20:23:38: [SM] Unable to load plugin "MyJailbreak/ffa.smx": Native "warden_iswarden" was not found
L 08/19/2016 - 20:23:38: [SM] Unable to load plugin "MyJailbreak/freeday.smx": Native "warden_iswarden" was not found
L 08/19/2016 - 20:23:38: [SM] Unable to load plugin "MyJailbreak/hide.smx": Native "warden_iswarden" was not found
L 08/19/2016 - 20:23:38: [SM] Unable to load plugin "MyJailbreak/knife.smx": Native "warden_iswarden" was not found
L 08/19/2016 - 20:23:38: [SM] Unable to load plugin "MyJailbreak/torch.smx": Native "warden_iswarden" was not found

**Comment by shanapu** [comment]
you need the warden plugin for use event days

**Comment by krysti500** [comment]
I install all plugins i install warden

**Comment by shanapu** [comment]
> ... and if you wanna our help please provide the infos we asking. like "sm plugins list" like in #113

**Comment by shanapu** [comment]
I assume that you fixed your problem because you haven't provided any further infos. 
closed
