### ISSUE TITLE
Cvar for random moves.

### ISSUE THREAD

**Issue by good-live** [shanapu/MyJailbreak#115]
You should definitly add a ConVar to disable random moves to CT. Pretty annoying when it moves guys, who just don't want to be CT.

**Comment by good-live** [comment]
Iv'e quickly made this. Completly untested. (See PR)

**Comment by shanapu** [comment]
yeah, La$ka asked me today exactly that.  #116 
Thank you very much for doing it instantly and sharing with us!
will have a small fast test and merge it to develop branch! thanks!

**Comment by shanapu** [comment]
> Completly untested.

seems to work so far,... but should be better tested before go to master

Thanks for your help!
