### ISSUE TITLE
Help with install.

### ISSUE THREAD

**Issue by edyedyy** [shanapu/MyJailbreak#117]
I install this addons and warden menu and days shop etc don't work. (sorry for bad english.)

**Comment by shanapu** [comment]
with only "don't work", we can't help you...
You must provide us some infos...
...what don't work? everything or only some parts?
...did you do all steps in [install instruction](https://github.com/shanapu/MyJailbreak/wiki/Installation) with success?
...which version of MyJailbreak are you running?
...what's the output of `sm plugin list` in serverconsole?
...some error logs `.../csgo/addons/sourcemod/logs`
...anything?

**Comment by shanapu** [comment]
I assume that you fixed your problem because you haven't provided any further infos. 
closed
