### ISSUE TITLE
Problems with the plugin

### ISSUE THREAD

**Issue by alesteffann** [shanapu/MyJailbreak#118]
Hello guys i installed all as requierd but i get this errors sm plugins list SM] Listing 72 plugins:
01 <Failed> "MyJailbreak - War FFA" (Beta 7.1) by shanapu
02 <Failed> "MyJailbreak - HE Battle" (Beta 7.1) by shanapu
03 "Custom Player Skins (Core)" (1.3.4) by Mitchell, Root
04 "SM File/Folder Downloader and Precacher" (1.4) by SWAT_88
05 <Failed> "MyJailbreak - HideInTheDark" (Beta 7.1) by shanapu
06 <Failed> "MyJailbreak - Suicide Bomber" (Beta 7.1) by shanapu
07 <Failed> "MyJailbreak - Zeus" (Beta 7.1) by shanapu
08 <Error> "Basic Commands" (1.8.0.5928) by AlliedModders LLC
09 "Sound Commands" (1.8.0.5928) by AlliedModders LLC
10 <Failed> "MyJailbreak - CowBoy" (Beta 7.1) by shanapu
11 <Failed> "MyJailbreak - DuckHunt" (Beta 7.1) by shanapu
12 "Admin Menu" (1.8.0.5928) by AlliedModders LLC
13 <Failed> "MyJailbreak - Freeday" (Beta 7.1) by shanapu
14 "Fun Votes" (1.8.0.5928) by AlliedModders LLC
15 "Basic Info Triggers" (1.8.0.5928) by AlliedModders LLC
16 <Failed> "MyJailbreak - Menus" (Beta 7.1) by shanapu, Franc1sco
17 "Fun Commands" (1.8.0.5928) by AlliedModders LLC
18 "Simple Chat Processor (Redux)" (2.1.0) by Simple Plugins, Mini
19 <Failed> "MyJailbreak - KnifeFight" (Beta 7.1) by shanapu
20 "Client Preferences" (1.8.0.5928) by AlliedModders LLC
21 "Random Player Models (CPS)" (1.0.2) by Mitchell
22 <Failed> "MyJailbreak - Drunk" (Beta 7.1) by shanapu
23 <Failed> "MyJailbreak - DealDamage" (Beta 7.1) by shanapu
24 <Failed> "MyJailbreak - NoScope" (Beta 7.1) by shanapu
25 "Reserved Slots" (1.8.0.5928) by AlliedModders LLC
26 "Basic Ban Commands" (1.8.0.5928) by AlliedModders LLC
27 <Failed> "MyJailbreak - Zombie" (Beta 7.1) by shanapu
28 <Failed> "Nextmap" (1.8.0.5928) by AlliedModders LLC
29 "Admin File Reader" (1.8.0.5928) by AlliedModders LLC
30 "Anti-Flood" (1.8.0.5928) by AlliedModders LLC
31 <Failed> "MyJailbreak - Warden" (Beta 7.1) by shanapu, ecca, ESKO & .#zipcore
32 <Failed> "MyJailbreak - Ratio" (Beta 7.1) by shanapu, Addicted
33 <Failed> "MyJailbreak - Player HUD" (Beta 7.1) by shanapu
34 <Failed> "MyJailbreak - Weapons" (Beta 7.1) by shanapu, Franc1sco
35 <Failed> "VoiceAnnounceEx" (2.1.1) by Franc1sco franug, Mini and GoD-Tony
36 "Player Commands" (1.8.0.5928) by AlliedModders LLC
37 "Admin Help" (1.8.0.5928) by AlliedModders LLC
38 "Basic Votes" (1.8.0.5928) by AlliedModders LLC
39 <Failed> "MyJailbreak - Last Guard Rule" (Beta 7.1) by shanapu
40 <Failed> "MyJailbreak - Core" (Beta 7.1) by shanapu
41 <Failed> "MyJailbreak - Torch Relay" (Beta 7.1) by shanapu
42 <Failed> "MyJailbreak - PlayerTags" (Beta 7.1) by shanapu
43 <Failed> "MyJailbreak - Request" (Beta 7.1) by shanapu
44 <Failed> "MyJailbreak - War" (Beta 7.1) by shanapu
45 "Basic Chat" (1.8.0.5928) by AlliedModders LLC
46 <Failed> "MyJailbreak - Catch & Freeze" (Beta 7.1) by shanapu
47 "Basic Comm Control" (1.8.0.5928) by AlliedModders LLC
48 <Failed> "MyJailbreak - War FFA" (Beta 7.1) by shanapu
49 <Failed> "MyJailbreak - HE Battle" (Beta 7.1) by shanapu
50 <Failed> "MyJailbreak - HideInTheDark" (Beta 7.1) by shanapu
51 <Failed> "MyJailbreak - Suicide Bomber" (Beta 7.1) by shanapu
52 <Failed> "MyJailbreak - Zeus" (Beta 7.1) by shanapu
53 <Failed> "MyJailbreak - CowBoy" (Beta 7.1) by shanapu
54 <Failed> "MyJailbreak - DuckHunt" (Beta 7.1) by shanapu
55 <Failed> "MyJailbreak - Freeday" (Beta 7.1) by shanapu
56 <Failed> "MyJailbreak - Menus" (Beta 7.1) by shanapu, Franc1sco
57 <Failed> "MyJailbreak - KnifeFight" (Beta 7.1) by shanapu
58 <Failed> "MyJailbreak - Drunk" (Beta 7.1) by shanapu
59 <Failed> "MyJailbreak - DealDamage" (Beta 7.1) by shanapu
60 <Failed> "MyJailbreak - NoScope" (Beta 7.1) by shanapu
61 <Failed> "MyJailbreak - Zombie" (Beta 7.1) by shanapu
62 <Failed> "MyJailbreak - Warden" (Beta 7.1) by shanapu, ecca, ESKO & .#zipcore
63 <Failed> "MyJailbreak - Ratio" (Beta 7.1) by shanapu, Addicted
64 <Failed> "MyJailbreak - Player HUD" (Beta 7.1) by shanapu
65 <Failed> "MyJailbreak - Weapons" (Beta 7.1) by shanapu, Franc1sco
66 <Failed> "MyJailbreak - Last Guard Rule" (Beta 7.1) by shanapu
67 <Failed> "MyJailbreak - Core" (Beta 7.1) by shanapu
68 <Failed> "MyJailbreak - Torch Relay" (Beta 7.1) by shanapu
69 <Failed> "MyJailbreak - PlayerTags" (Beta 7.1) by shanapu
70 <Failed> "MyJailbreak - Request" (Beta 7.1) by shanapu
71 <Failed> "MyJailbreak - War" (Beta 7.1) by shanapu
72 <Failed> "MyJailbreak - Catch & Freeze" (Beta 7.1) by shanapu
Errors:
ffa.smx (MyJailbreak - War FFA): Could not find required plugin "lastrequest"
hebattle.smx (MyJailbreak - HE Battle): Could not find required plugin "lastrequest"
hide.smx (MyJailbreak - HideInTheDark): Could not find required plugin "lastrequest"
suicide.smx (MyJailbreak - Suicide Bomber): Could not find required plugin "lastrequest"
zeus.smx (MyJailbreak - Zeus): Could not find required plugin "lastrequest"
basecommands.smx (Basic Commands): Error detected in plugin startup (see error logs)
cowboy.smx (MyJailbreak - CowBoy): Could not find required plugin "lastrequest"
duckhunt.smx (MyJailbreak - DuckHunt): Could not find required plugin "lastrequest"
freeday.smx (MyJailbreak - Freeday): Could not find required plugin "lastrequest"
menu.smx (MyJailbreak - Menus): Could not find required plugin "lastrequest"
knife.smx (MyJailbreak - KnifeFight): Could not find required plugin "lastrequest"
drunk.smx (MyJailbreak - Drunk): Could not find required plugin "lastrequest"
dealdamage.smx (MyJailbreak - DealDamage): Could not find required plugin "lastrequest"
noscope.smx (MyJailbreak - NoScope): Could not find required plugin "lastrequest"
zombie.smx (MyJailbreak - Zombie): Could not find required plugin "lastrequest"
nextmap.smx (Nextmap): Mapcycle Not Found
warden.smx (MyJailbreak - Warden): Could not find required plugin "lastrequest"
ratio.smx (MyJailbreak - Ratio): Could not find required plugin "lastrequest"
hud.smx (MyJailbreak - Player HUD): Could not find required plugin "lastrequest"
weapons.smx (MyJailbreak - Weapons): Could not find required plugin "lastrequest"
voiceannounce_ex.smx (VoiceAnnounceEx): Required extension "dhooks" file("dhooks.ext") not running
lastguard.smx (MyJailbreak - Last Guard Rule): Could not find required plugin "lastrequest"
myjailbreak.smx (MyJailbreak - Core): Could not find required plugin "lastrequest"
torch.smx (MyJailbreak - Torch Relay): Could not find required plugin "lastrequest"
playertags.smx (MyJailbreak - PlayerTags): Could not find required plugin "lastrequest"
request.smx (MyJailbreak - Request): Could not find required plugin "lastrequest"
war.smx (MyJailbreak - War): Could not find required plugin "lastrequest"
catch.smx (MyJailbreak - Catch & Freeze): Could not find required plugin "lastrequest"
MyJailbreak/ffa.smx (MyJailbreak - War FFA): Could not find required plugin "lastrequest"
MyJailbreak/hebattle.smx (MyJailbreak - HE Battle): Could not find required plugin "lastrequest"
MyJailbreak/hide.smx (MyJailbreak - HideInTheDark): Could not find required plugin "lastrequest"
MyJailbreak/suicide.smx (MyJailbreak - Suicide Bomber): Could not find required plugin "lastrequest"
MyJailbreak/zeus.smx (MyJailbreak - Zeus): Could not find required plugin "lastrequest"
MyJailbreak/cowboy.smx (MyJailbreak - CowBoy): Could not find required plugin "lastrequest"
MyJailbreak/duckhunt.smx (MyJailbreak - DuckHunt): Could not find required plugin "lastrequest"
MyJailbreak/freeday.smx (MyJailbreak - Freeday): Could not find required plugin "lastrequest"
MyJailbreak/menu.smx (MyJailbreak - Menus): Could not find required plugin "lastrequest"
MyJailbreak/knife.smx (MyJailbreak - KnifeFight): Could not find required plugin "lastrequest"
MyJailbreak/drunk.smx (MyJailbreak - Drunk): Could not find required plugin "lastrequest"
MyJailbreak/dealdamage.smx (MyJailbreak - DealDamage): Could not find required plugin "lastrequest"
MyJailbreak/noscope.smx (MyJailbreak - NoScope): Could not find required plugin "lastrequest"
MyJailbreak/zombie.smx (MyJailbreak - Zombie): Could not find required plugin "lastrequest"
MyJailbreak/warden.smx (MyJailbreak - Warden): unexpected error 23 in AskPluginLoad callback
MyJailbreak/ratio.smx (MyJailbreak - Ratio): Could not find required plugin "lastrequest"
MyJailbreak/hud.smx (MyJailbreak - Player HUD): Could not find required plugin "lastrequest"
MyJailbreak/weapons.smx (MyJailbreak - Weapons): Could not find required plugin "lastrequest"
MyJailbreak/lastguard.smx (MyJailbreak - Last Guard Rule): Could not find required plugin "lastrequest"
MyJailbreak/myjailbreak.smx (MyJailbreak - Core): unexpected error 23 in AskPluginLoad callback
MyJailbreak/torch.smx (MyJailbreak - Torch Relay): Could not find required plugin "lastrequest"
MyJailbreak/playertags.smx (MyJailbreak - PlayerTags): Could not find required plugin "lastrequest"
MyJailbreak/request.smx (MyJailbreak - Request): Could not find required plugin "lastrequest"
MyJailbreak/war.smx (MyJailbreak - War): Could not find required plugin "lastrequest"
  

nothing is working

**Comment by shanapu** [comment]
Please take a look to the [FAQ](https://github.com/shanapu/MyJailbreak/wiki/Frequently-Asked-Questions). I think you will find your answer there. You missing one of the [required plugins](https://github.com/shanapu/MyJailbreak/wiki/Installation#requires-plugins).

**Comment by alesteffann** [comment]
Thank you done!
