### ISSUE TITLE
Big BOX RED [everything checked]

### ISSUE THREAD

**Issue by alesteffann** [shanapu/MyJailbreak#119]
Problem with the models i checked everything the models the fast dl everything is good i dont know why the big box is appearing any help ?

**Comment by mrkos9i4ok** [comment]
Has updated fast dl?
Has established on a gallop?
Correct way to model?

**Comment by shanapu** [comment]
Hi, I edited [FAQs Big red error boxes](https://github.com/shanapu/MyJailbreak/wiki/Frequently-Asked-Questions#big-red-error-boxes-instead-of-player-models) a bit.
Are the files get downloaded on client connect? 
What's the URL to your FastDL?
Does custom sounds and overlays work?

**Comment by alesteffann** [comment]
yes they are downloading 
the download is finished 
the custom sounds and overlays work yes

**Comment by alesteffann** [comment]
Downloading http://download.toolz.ro/188.212.107.87//materials/models/player/custom_player/zombie/revenant/body.vmt.bz2.
Error downloading http://download.toolz.ro/188.212.107.87//materials/models/player/custom_player/zombie/revenant/body.vmt.bz2
Downloading http://download.toolz.ro/188.212.107.87//materials/models/player/custom_player/zombie/revenant/body.vmt.
Download finished!
Downloading http://download.toolz.ro/188.212.107.87//materials/models/player/custom_player/zombie/revenant/body.vtf.bz2.
Error downloading http://download.toolz.ro/188.212.107.87//materials/models/player/custom_player/zombie/revenant/body.vtf.bz2
Downloading http://download.toolz.ro/188.212.107.87//materials/models/player/custom_player/zombie/revenant/body.vtf.
Download finished!

this is my console info

**Comment by shanapu** [comment]
after support on steam I found the problem & added it to [FAQ](https://github.com/shanapu/MyJailbreak/wiki/Frequently-Asked-Questions)

> If you inadvertently installed ["Random Player Models (CPS) (1.0.2) by Mitchell"](https://forums.alliedmods.net/showthread.php?p=2140485) together with [CustomPlayerSkins](https://forums.alliedmods.net/showthread.php?t=240703). You don't need it for MyJailbreak. Remove it.
