### ISSUE TITLE
Bug; vote for kick commander

### ISSUE THREAD

**Issue by Include5** [shanapu/MyJailbreak#121]
In voting for the kick is considered the commander of the last voted on as an administrator
or
Shanapu vote > 1/2 > Include vote > 2/2 > print to chat; Admin: Include kick CMD when him is not admin

**Comment by shanapu** [comment]
So so clear this issue. We talked on steam and you explained it much better than here. 

Please take a look to the [FAQ](https://github.com/shanapu/MyJailbreak/wiki/Frequently-Asked-Questions) and read exactly [this part]( https://github.com/shanapu/MyJailbreak/wiki/Frequently-Asked-Questions#what-should-i-consider-if-i-open-a-issue-or-post-on-forum) (What should I consider if I open an issue or post on forum?)

So to the issue:
On a veto vote against warden, when the vote wins. The last player who has voted will be called in chat as admin, right?
Voting remove warden wins-> Chat: "Admin {NAME OF LAST VOTER} removed player %N as warden" right?

I havn't test it on a server, but I read the code more than twice. In both branches. 
There is nowhere a code that print a message on succesfull wardenvote in chat. 

https://github.com/shanapu/MyJailbreak/blob/master/addons/sourcemod/scripting/MyJailbreak/warden.sp#L354-L387
https://github.com/shanapu/MyJailbreak/blob/develop/addons/sourcemod/scripting/MyJailbreak/warden.sp#L413-L446

The function `RemoveTheWarden()` also have no chat output.
Also the translation tag `"warden_removed"` that means "Admin %N removed player %N as warden" is only on admin command `sm_removewarden` and `sm_setwarden`


Are you sure? Maybe you confusing something? or I'm blind and to stoned?

**Comment by shanapu** [comment]
you reacted with a heart emoji but hasn't answered... 

Was that a mistake or did I miss something?

**Comment by Include5** [comment]
http://imgur.com/sIksyHf

WOW.After the kick commander in the chat does not display anything
MYJB 7.1
MyJailbreak.Warden.phrases.txt
https://gist.github.com/Include5/8201ddb816906a0b9f0267566f2bf609
