### ISSUE TITLE
Last Request problem

### ISSUE THREAD

**Issue by alesteffann** [shanapu/MyJailbreak#122]
It seems the !lr command doesnt work i set it for 1 maxim T to be alive enabled it and still dont work any ideas?

**Comment by shanapu** [comment]
Hi, MyJailbreak don't have a Last Request system. LR is a part of sm_hosties. so to open an issue here is the wrong way. 

Of course I will help you with your problem, but first please take a look to the [FAQ](https://github.com/shanapu/MyJailbreak/wiki/Frequently-Asked-Questions) and read exactly [this part]( https://github.com/shanapu/MyJailbreak/wiki/Frequently-Asked-Questions#what-should-i-consider-if-i-open-a-issue-or-post-on-forum) (What should I consider if I open a issue or post on forum?)

I will close this cause this don't seems like an MyJB issue for me but you can still comment here.

**Comment by alesteffann** [comment]
ok but please can you tell me what do to?

**Comment by shanapu** [comment]
read exactly [What should I consider if I open a issue or post on forum]( https://github.com/shanapu/MyJailbreak/wiki/Frequently-Asked-Questions#what-should-i-consider-if-i-open-a-issue-or-post-on-forum)

**Comment by alesteffann** [comment]
sorry for not answering its work in progress not found yet

**Comment by shanapu** [comment]
if you provide some more infos - like I asked indirectly - may we could help you.

**Comment by alesteffann** [comment]
done! thank you for your help shanapu
