### ISSUE TITLE
Commander's conversation

### ISSUE THREAD

**Issue by mrkos9i4ok** [shanapu/MyJailbreak#124]
You couldn't correct defects, of course if so it hasn't been conceived:
-When the commander speaks, mute is given also to the dead
-When the commander speaks, too is given to security guards mute

**Comment by shanapu** [comment]
> -When the commander speaks, mute is given also to the dead

That's right. Many server (i know) have dead can talk to alive enabled. but I will make a cvar for that.

> -When the commander speaks, too is given to security guards mute

It's not in the wiki yet, but in your Warden.cfg   
`sm_warden_talkover_team:  0 - mute prisoner & guards on talkover, 1 - only mute prisoners on talkover`
