### ISSUE TITLE
Menu dont work

### ISSUE THREAD

**Issue by FTRETRTE2312** [shanapu/MyJailbreak#131]
All plugins work but menu dont work . i say on chat !menu but he dont open

**Comment by FTRETRTE2312** [comment]
menu.smx (MyJailbreak - Menus): Native "warden_deputy_exist" was not found
MyJailbreak/ratio.smx (MyJailbreak - Ratio): Native "warden_deputy_isdeputy" was not found
MyJailbreak/warden.smx (MyJailbreak - Warden): unexpected error 23 in AskPluginLoad callback
MyJailbreak/menu.smx (MyJailbreak - Menus): Native "warden_deputy_exist" was not found
MyJailbreak/request.smx (MyJailbreak - Request): Native "warden_deputy_isdeputy" was not found
MyJailbreak/hud.smx (MyJailbreak - Player HUD): Native "warden_get" was not found
MyJailbreak/playertags.smx (MyJailbreak - PlayerTags): Native "warden_deputy_isdeputy" was not found
advcommands.smx (Advanced admin commands): Error detected in plugin startup (see error logs)
playertags.smx (MyJailbreak - PlayerTags): Native "warden_deputy_isdeputy" was not found
togsclantags.smx (TOG Clan Tags): Configuration file addons/sourcemod/configs/togsclantags.cfg not found!

**Comment by shanapu** [comment]
Please take a look to the [FAQ](https://github.com/shanapu/MyJailbreak/wiki/Frequently-Asked-Questions). I think you will find your answer there. If not, just reply here again.

Your search term:
`unexpected error 23 in AskPluginLoad callback `

**Comment by shanapu** [comment]
[(https://github.com/shanapu/MyJailbreak/wiki/Frequently-Asked-Questions#what-should-i-consider-if-i-open-a-issue-or-post-on-forum)
