### ISSUE TITLE
Deputy>Warden

### ISSUE THREAD

**Issue by mrkos9i4ok** [shanapu/MyJailbreak#132]
To do so, for example, when WARDEN dies, his DEPUTY automatically becomes WARDEN and next DEPUTY gets out.

**Comment by shanapu** [comment]
`sm_warden_deputy_warden_dead - 0 - Deputy will removed on warden death, 1 - Deputy will be new warden`

**Comment by mrkos9i4ok** [comment]
sm_warden_deputy_warden_dead "1"
don`t worled
