### ISSUE TITLE
New Forward OnClientJoinQueue

### ISSUE THREAD

**Issue by good-live** [shanapu/MyJailbreak#133]
https://github.com/shanapu/MyJailbreak/blob/master/addons/sourcemod/scripting/MyJailbreak/ratio.sp#L380

Would love to see such a forward instead of hardcoded support for databombs CT-Ban.

This would allow to easily add different checks (CT-Ban, Playtime, ...).
Support for CT-Ban from databomb should get moved to an optional plugin then.

**Comment by good-live** [comment]
Or call it OnClientJoinCT idk ^^

**Comment by shanapu** [comment]
b5f96796720a95dc127e434787288e7c00a5c3a1

**Comment by good-live** [comment]
Thanks goign to check it out when i have some time :+1:

**Comment by shanapu** [comment]
added many Add-ons for different plugins support
may someone got some of these installed for testing.

- CTBans
- RankMe
- Kento RankMe
- Reputation
- Stamm
- TeamBans

any ideas anything missing?

**Comment by good-live** [comment]
I hadnt got the chance to test those yet.
But for me theres nothing missing :)

**Comment by shanapu** [comment]
I close this in the hope that the other plugins work too.
