### ISSUE TITLE
Error: on remove weapon: Weapon 'N' is not owned by client 'N'

### ISSUE THREAD

**Issue by mrkos9i4ok** [shanapu/MyJailbreak#134]
```
L 09/29/2016 - 13:02:36: [SM] Exception reported: Weapon 92 is not owned by client 2
L 09/29/2016 - 13:02:36: [SM] Blaming: MyJailbreak/weapons.smx()
L 09/29/2016 - 13:02:36: [SM] Call stack trace:
L 09/29/2016 - 13:02:36: [SM]   [0] SDKHooks_DropWeapon
L 09/29/2016 - 13:02:36: [SM]   [1] Line 76, D:\Code\MyJailbreak\addons\sourcemod\scripting\include\mystocks.inc::StripAllPlayerWeapons()
L 09/29/2016 - 13:02:36: [SM]   [2] Line 303, MyJailbreak/weapons.sp::GiveSavedWeapons()
L 09/29/2016 - 13:02:36: [SM]   [3] Line 736, MyJailbreak/weapons.sp::Timer_GetWeapons()
```

**Comment by mrkos9i4ok** [comment]
L 10/01/2016 - 23:20:29: [SM] Exception reported: Weapon 74 is not owned by client 4
L 10/01/2016 - 23:20:29: [SM] Blaming: MyJailbreak/warden.smx()
L 10/01/2016 - 23:20:29: [SM] Call stack trace:
L 10/01/2016 - 23:20:29: [SM]   [0] SDKHooks_DropWeapon
L 10/01/2016 - 23:20:29: [SM]   [1] Line 479, MyJailbreak/Modules/Warden/handcuffs.sp::StripZeus()
L 10/01/2016 - 23:20:29: [SM]   [2] Line 314, MyJailbreak/Modules/Warden/handcuffs.sp::HandCuffs_OnWardenRemoved()
L 10/01/2016 - 23:20:29: [SM]   [3] Line 1136, MyJailbreak/warden.sp::Forward_OnWardenRemoved()
L 10/01/2016 - 23:20:29: [SM]   [4] Line 695, MyJailbreak/warden.sp::OnClientDisconnect()

**Comment by shanapu** [comment]
I assume you still use [these](https://github.com/shanapu/MyJailbreak/issues/129#issuecomment-247804222) plugins. What does `77 "csgoweapon.smx"` do? I guess there could be a conflict cause is never seen these errors before.

**Comment by mrkos9i4ok** [comment]
csgoweapon.smx 
He takes away weapon from last round (well that didn't remain with T m4a4 or ak-47 from last round).

**Comment by shanapu** [comment]
do this errors still appear? 
anyone else got these errors?

**Comment by shanapu** [comment]
#138

**Comment by shanapu** [comment]
this error is really weird. How a weapon that is force dropped by a client not owned by client?

Here this same error by @caaine from closed #138

> L 10/21/2016 - 12:57:40: [SM] Exception reported: Weapon 271 is not owned by client 2
> L 10/21/2016 - 12:57:40: [SM] Blaming: MyJailbreak/noscope.smx
> L 10/21/2016 - 12:57:40: [SM] Call stack trace:
> L 10/21/2016 - 12:57:40: [SM] [0] SDKHooks_DropWeapon
> L 10/21/2016 - 12:57:40: [SM] [1] Line 76, D:\Code\MyJailbreak\addons\sourcemod\scripting\include\mystocks.inc::StripAllPlayerWeapons
> L 10/21/2016 - 12:57:40: [SM] [2] Line 435, MyJailbreak/noscope.sp::Event_RoundStart

Does anyone have an idea?

**Comment by shanapu** [comment]
has this error `Weapon 'N' is not owned by client 'N'` ever occurs agains? 
I assume this was a temporarily bug caused by sm/valve(?).

**Comment by shanapu** [comment]
server operators report back error is gone... close.
