### ISSUE TITLE
zombie: knockback fix

### ISSUE THREAD

**Issue by shanapu** [shanapu/MyJailbreak#135]
ok, there is there first one asking for it. I will include a knockback fix for zombie event day so soon as possible.

**Comment by mrkos9i4ok** [comment]
https://www.youtube.com/watch?v=mB1sZDXHEV4&feature=youtu.be

**Comment by shanapu** [comment]
I assume you want to tell me with this video that knockback works fine? yay!
Is `"sm_zombie_knockback" "20.0"` a good default value?

**Comment by shanapu** [comment]
Knockbackfix is fine?

> Is "sm_zombie_knockback" "20.0" a good default value?

Can I check off this?

**Comment by shanapu** [comment]
seems fine. close
