### ISSUE TITLE
Handcuffs - Push Button to use Paperclip

### ISSUE THREAD

**Issue by shanapu** [shanapu/MyJailbreak#136]
Cuffed player must hold a button (+use) to use the paperclip. Maybe with progress bar & more paperclips (maybe native for jailshop?)

**Comment by shanapu** [comment]
07870909a0cca6641cfc9d4804dfe7d0bda7f9b0

**Comment by mrkos9i4ok** [comment]
It is used as simple Zeus, it is possible to use once and when using on the opponent - kills.

**Comment by shanapu** [comment]
Player has per default 2 Handcuffs. If these handcuffs are used (cuff player & free them) the zeus going to be a normal taser that kills.

**Comment by mrkos9i4ok** [comment]
![image](https://cloud.githubusercontent.com/assets/20227450/19610275/3b2e66bc-97e4-11e6-8f44-2afdee2c38c7.png)
And well I in the first round something had not that) In handcuffs places, and when using (+use) nothing occurs.

**Comment by shanapu** [comment]
> no progress bar yet

only sound appears on pressing/holding +use

for testing maybe use:  `sm_warden_handcuffs_paperclip_chance 1` & `sm_warden_handcuffs_unlock_chance 1`

**Comment by mrkos9i4ok** [comment]
Writes what gives a paper clip, but I can't get out of handcuffs in any way.

**Comment by shanapu** [comment]
I pushed a update with a small progress bar.   on all my tests It works with **sm_warden_handcuffs_paperclip_chance 1 & sm_warden_handcuffs_unlock_chance 1** everytime to uncuff

**Comment by mrkos9i4ok** [comment]
Oh nice worked) Though actually I thought it will be that that like overlays.

**Comment by mrkos9i4ok** [comment]
/26/2016 - 17:22:20: [SM] Exception reported: Client 4 is not in game
L 10/26/2016 - 17:22:20: [SM] Blaming: MyJailbreak/warden.smx
L 10/26/2016 - 17:22:20: [SM] Call stack trace:
L 10/26/2016 - 17:22:20: [SM]   [0] PrintCenterText
L 10/26/2016 - 17:22:20: [SM]   [1] Line 342, MyJailbreak/Modules/Warden/handcuffs.sp::Timer_Progress

**Comment by shanapu** [comment]
error is fixed

> Oh nice worked) Though actually I thought it will be that that like overlays.

I worked on various kinds of progressbars. But I'm not happy with the results. 
That's why I make this small progressbar-placeholder for you to see the lockpicking status.

**Comment by shanapu** [comment]
here a small youtube video with another progress animation.

[![handcuffs video](https://img.youtube.com/vi/B4ov7Mvy5yg/0.jpg)](http://www.youtube.com/watch?v=B4ov7Mvy5yg)

**Comment by shanapu** [comment]
hi, new progress bar is up! 7ea1f999c5c1fa01c3f5acf5cda323c1a8179c2d please test! error should be fixed too.
sry for a long time no response. real life.

**Comment by shanapu** [comment]
I forgot to remove my test command `!cuff` (cuff yourself). So you can use it for testing. best config for testing
`
sm_warden_handcuffs_number "20" // or x
sm_warden_handcuffs_paperclip_chance "1" //get paperclip everytime
sm_warden_handcuffs_unlock_chance "2" //or 1 = evertime unlock
sm_warden_handcuffs_unlock_mintime "10.0"
sm_warden_handcuffs_unlock_maxtime "15.0"
`

**Comment by shanapu** [comment]
removed !cuff in 30d72e82c524fd98d20fba47d1aa4dade084b863
close.
