### ISSUE TITLE
Warden: orders

### ISSUE THREAD

**Issue by shanapu** [shanapu/MyJailbreak#137]
https://forums.alliedmods.net/showpost.php?p=2456153&postcount=262

**Comment by shanapu** [comment]
a early version is online, but not finsihed. 
overlays file missing but feature ready to work
sound files missing but feature ready to work
command feature work in progress.

**Comment by mrkos9i4ok** [comment]
I do not understand the logic of it) Well, the type of run that thing, and wrote in a chat that you need to do.

**Comment by shanapu** [comment]
yeah, sorry for the lack of description.

The order module provide a menu (!orders) for the warden with preconfigured orders like:

- Go to the pool
- Everybody frozen and petrified
- Go to medic room
- ...

This orders can be configured to be shown as:

- overlay (set time, choose team)
- chat (colors)
- hud (colors)
- sound

And you can config to disable a single order on a specific map. e.g if there is no pool on map the order pools will not be shown...

**Comment by shanapu** [comment]
> edit:3 customs commands for a order coming soon

done. custom commands for all orders
