### ISSUE TITLE
error.log

### ISSUE THREAD

**Issue by Caaine** [shanapu/MyJailbreak#138]
L 10/13/2016 - 16:58:42: [SM] Exception reported: Invalid entity (2 - 2)
L 10/13/2016 - 16:58:42: [SM] Blaming: MyJailbreak/request.smx
L 10/13/2016 - 16:58:42: [SM] Call stack trace:
L 10/13/2016 - 16:58:42: [SM]   [0] GetEntityNetClass
L 10/13/2016 - 16:58:42: [SM]   [1] Line 481, D:\Code\MyJailbreak\addons\sourcemod\scripting\include\entity.inc::GetEntSendPropOffs
L 10/13/2016 - 16:58:42: [SM]   [2] Line 440, D:\Code\MyJailbreak\addons\sourcemod\scripting\include\entity_prop_stocks.inc::SetEntityRenderColor
L 10/13/2016 - 16:58:42: [SM]   [3] Line 364, MyJailbreak/Modules/Request/capitulation.sp::Timer_RebelNoAction
L 10/13/2016 - 16:59:08: [SM] Exception reported: Handle 542e0849 is invalid (error 1)
L 10/13/2016 - 16:59:08: [SM] Blaming: MyJailbreak/request.smx
L 10/13/2016 - 16:59:08: [SM] Call stack trace:
L 10/13/2016 - 16:59:08: [SM]   [0] CloseHandle
L 10/13/2016 - 16:59:08: [SM]   [1] Line 174, MyJailbreak/Modules/Request/capitulation.sp::Capitulation_Event_RoundStart

**Comment by shanapu** [comment]
should be fixed.

**Comment by Caaine** [comment]
L 10/21/2016 - 12:57:40: [SM] Exception reported: Weapon 271 is not owned by client 2
L 10/21/2016 - 12:57:40: [SM] Blaming: MyJailbreak/noscope.smx
L 10/21/2016 - 12:57:40: [SM] Call stack trace:
L 10/21/2016 - 12:57:40: [SM]   [0] SDKHooks_DropWeapon
L 10/21/2016 - 12:57:40: [SM]   [1] Line 76, D:\Code\MyJailbreak\addons\sourcemod\scripting\include\mystocks.inc::StripAllPlayerWeapons
L 10/21/2016 - 12:57:40: [SM]   [2] Line 435, MyJailbreak/noscope.sp::Event_RoundStart

**Comment by shanapu** [comment]
hmm.. same error like #134 
Can't figure out why a weapon that will be dropped by the player is not more owned by him.

**Comment by mrkos9i4ok** [comment]
The plug-in which erases weapon from the previous round is installed.
http://hlmod.ru/threads/problemy-s-tochkami-spauna.34387/#post-237003 Example.

**Comment by shanapu** [comment]
i close this first error is fixed with 6ce951d3688005dac5a73bdc6e63d641b83ad4b7

still open error "Weapon 271 is not owned by client" on https://github.com/shanapu/MyJailbreak/issues/134
