### ISSUE TITLE
Friendly fire conflict with KissLicks TeamGames

### ISSUE THREAD

**Issue by mrkos9i4ok** [shanapu/MyJailbreak#139]
When I use https://github.com/KissLick/TeamGames there is a problem with games, namely players of identical team can't kill each other.
I got it. that it is connected with:
```
// 0 = do nothing "mp_friendlyfire"
// 1 = set "mp_friendlyfire 1" every map start (after configs are loaded)
// 2 = set "mp_friendlyfire 1" when game is in progress and set "mp_friendlyfire 0" otherwise.
// -
// Default: "1"
tg_cvar_friendlyfire "2"
```
But if to deliver something except 2, then games won't work.

**Comment by shanapu** [comment]
Try this: https://github.com/shanapu/MyJB-TG_friendlyfire

need tg_team_none_attack "0"
I will include this in next MyJB update.

**Comment by mrkos9i4ok** [comment]
not helped

**Comment by mrkos9i4ok** [comment]
Now at inclusion of a loss according to the menus in the commander has ceased to work, also in team games there is no loss.

**Comment by shanapu** [comment]
> not helped

It works for me and other people. "not helped" is not helpful.

Again:
It's very hard to understand you in all your requests.
Please, mrkos9i4ok try to explain your problems more detailed in better English. 
I know it's hard to learn a new language. Try to use different translators, don't copy paste a translation without a recheck. **Ask a friend who speaks english, maybe he can correct you.**
I'm sorry, but **I getting crazy** with some of your posts...

> Now at inclusion of a loss according to the menus in the commander has ceased to work, also in team games there is no loss.

What?

**Comment by mrkos9i4ok** [comment]
When I include team game, the loss on the doesn't go. When I include a loss according to the menus in the commander, the loss doesn't go. There are no mistakes. Has established everything as you wrote.
