### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by sword134** [shanapu/MyJailbreak#141]
Im having some installation issues.

Most parts of the plugin wont work. The part that does however work is the colored chat. I have followed all the install instructions, downloaded, removed and redownloaded the different requirements several times. Tried both SM Hosties beta branch and the 2.20 branch. I have lurked around the Issues page for an hour or so trying to find a solution.

My sourcemod error log displays the following:

> L 10/27/2016 - 17:21:25: SourceMod error session started
L 10/27/2016 - 17:21:25: Info (map "workshop/134820868/ba_jail_electric_vip_v3") (file "errors_20161027.log")
L 10/27/2016 - 17:21:25: [SM] Exception reported: Fatal error creating dynamic native!
L 10/27/2016 - 17:21:25: [SM] Blaming: warden.smx
L 10/27/2016 - 17:21:25: [SM] Call stack trace:
L 10/27/2016 - 17:21:25: [SM]   [0] CreateNative
L 10/27/2016 - 17:21:25: [SM]   [1] Line 55, warden.sp::AskPluginLoad2
L 10/27/2016 - 17:21:25: [SM] Failed to load plugin "warden.smx": unexpected error 23 in AskPluginLoad callback.
L 10/27/2016 - 17:21:25: [SM] Unable to load plugin "MyJailbreak\catch.smx": Could not find required plugin "smartjaildoors"
L 10/27/2016 - 17:21:25: [SM] Unable to load plugin "MyJailbreak\cowboy.smx": Could not find required plugin "smartjaildoors"
L 10/27/2016 - 17:21:25: [SM] Unable to load plugin "MyJailbreak\dealdamage.smx": Could not find required plugin "smartjaildoors"
L 10/27/2016 - 17:21:25: [SM] Unable to load plugin "MyJailbreak\drunk.smx": Could not find required plugin "smartjaildoors"
L 10/27/2016 - 17:21:25: [SM] Unable to load plugin "MyJailbreak\duckhunt.smx": Could not find required plugin "smartjaildoors"
L 10/27/2016 - 17:21:25: [SM] Unable to load plugin "MyJailbreak\ffa.smx": Could not find required plugin "smartjaildoors"
L 10/27/2016 - 17:21:25: [SM] Unable to load plugin "MyJailbreak\freeday.smx": Could not find required plugin "smartjaildoors"
L 10/27/2016 - 17:21:25: [SM] Unable to load plugin "MyJailbreak\hebattle.smx": Could not find required plugin "smartjaildoors"
L 10/27/2016 - 17:21:25: [SM] Unable to load plugin "MyJailbreak\hide.smx": Could not find required plugin "smartjaildoors"
L 10/27/2016 - 17:21:25: [SM] Unable to load plugin "MyJailbreak\knife.smx": Could not find required plugin "smartjaildoors"
L 10/27/2016 - 17:21:25: [SM] Unable to load plugin "MyJailbreak\lastguard.smx": Could not find required plugin "smartjaildoors"
L 10/27/2016 - 17:21:25: [SM] Unable to load plugin "MyJailbreak\menu.smx": Could not find required plugin "smartjaildoors"
L 10/27/2016 - 17:21:25: [SM] Unable to load plugin "MyJailbreak\noscope.smx": Could not find required plugin "smartjaildoors"
L 10/27/2016 - 17:21:25: [SM] Unable to load plugin "MyJailbreak\request.smx": Could not find required plugin "smartjaildoors"
L 10/27/2016 - 17:21:25: [SM] Unable to load plugin "MyJailbreak\suicide.smx": Could not find required plugin "smartjaildoors"
L 10/27/2016 - 17:21:25: [SM] Unable to load plugin "MyJailbreak\torch.smx": Could not find required plugin "smartjaildoors"
L 10/27/2016 - 17:21:25: [SM] Unable to load plugin "MyJailbreak\war.smx": Could not find required plugin "smartjaildoors"
L 10/27/2016 - 17:21:25: [SM] Unable to load plugin "MyJailbreak\warden.smx": Could not find required plugin "smartjaildoors"
L 10/27/2016 - 17:21:25: [SM] Unable to load plugin "MyJailbreak\weapons.smx": Could not find required plugin "warden"
L 10/27/2016 - 17:21:25: [SM] Unable to load plugin "MyJailbreak\zeus.smx": Could not find required plugin "smartjaildoors"
L 10/27/2016 - 17:21:25: [SM] Unable to load plugin "MyJailbreak\zombie.smx": Could not find required plugin "smartjaildoors"
L 10/27/2016 - 17:21:27: Error log file session closed.
L 10/27/2016 - 17:21:27: SourceMod error session started
L 10/27/2016 - 17:21:27: Info (map "workshop/134820868/ba_jail_electric_vip_v3") (file "errors_20161027.log")
L 10/27/2016 - 17:21:27: [SM] Unable to load plugin "MyJailbreak\hud.smx": Could not find required plugin "warden"
L 10/27/2016 - 17:21:27: [SM] Unable to load plugin "MyJailbreak\playertags.smx": Could not find required plugin "warden"
L 10/27/2016 - 17:21:27: [SM] Unable to load plugin "MyJailbreak\ratio.smx": Could not find required plugin "warden"

> 

So I spotted that the warden.smx was the issue. So I reinstalled the official warden plugin by Ecca. Then later removed it and installed the MyJailbreak warden. None of that worked.

These are the plugins it says are installed.
] sm plugins
 "Admin File Reader" (1.8.0.5948) by AlliedModders LLC
 "Admin Join Sound" (1.7) by KK
 "Admin Help" (1.8.0.5948) by AlliedModders LLC
 "Admin Menu" (1.8.0.5948) by AlliedModders LLC
 "Anti-Flood" (1.8.0.5948) by AlliedModders LLC
 "Basic Ban Commands" (1.8.0.5948) by AlliedModders LLC
 "Basic Chat" (1.8.0.5948) by AlliedModders LLC
 "Basic Comm Control" (1.8.0.5948) by AlliedModders LLC
 "Basic Commands" (1.8.0.5948) by AlliedModders LLC
 "Basic Info Triggers" (1.8.0.5948) by AlliedModders LLC
To see more, type "sm plugins 11"
] sm plugins 11
 "Basic Votes" (1.8.0.5948) by AlliedModders LLC
 "Chat-Processor" (1.1.2) by Keith Warren (Drixevel)
 "Client Preferences" (1.8.0.5948) by AlliedModders LLC
 "Console Welcome Message" (1.1.2) by exvel
 "CS:GO Goremod" (1.3) by Joe 'DiscoBBQ' Maley
 "Custom Player Skins (Core)" (1.3.4) by Mitchell, Root
 "Fun Commands" (1.8.0.5948) by AlliedModders LLC
 "Fun Votes" (1.8.0.5948) by AlliedModders LLC
 "MyJailbreak - Core" (Beta 8.1) by shanapu
 "Nextmap" (1.8.0.5948) by AlliedModders LLC
 "Player Commands" (1.8.0.5948) by AlliedModders LLC
To see more, type "sm plugins 22"
] sm plugins 22
 "Reserved Slots" (1.8.0.5948) by AlliedModders LLC
 "SM File/Folder Downloader and Precacher" (1.4) by SWAT_88
 "SM_Hosties v2" (2.2.0) by databomb & dataviruset & comando
 "Sound Commands" (1.8.0.5948) by AlliedModders LLC
 "Test Messages" (1.0.1) by Keith Warren (Drixevel)
 "VoiceAnnounceEx" (2.1.1) by Franc1sco franug, Mini and GoD-Tony

**Comment by mrkos9i4ok** [comment]
https://github.com/Kailo97/smartjaildoors

**Comment by sword134** [comment]
As said. I have all the requirements. I have reinstalled them all several times. I reinstalled the smartjaildoors again and it still doesnt work.

**Comment by shanapu** [comment]
Please take a look to the [FAQ](https://github.com/shanapu/MyJailbreak/wiki/Frequently-Asked-Questions). I think you will find your answer there. 

> L 10/27/2016 - 17:21:25: [SM] Failed to load plugin "warden.smx": unexpected error 23 in AskPluginLoad callback.

"[Seems you have two warden plugins installed. Remove your old warden plugin and use only MyJailbreak Warden.](https://github.com/shanapu/MyJailbreak/wiki/Frequently-Asked-Questions#i-have-this-error)"

> L 10/27/2016 - 17:21:25: [SM] Unable to load plugin "MyJailbreak\warden.smx": Could not find required plugin "smartjaildoors"

"[You have not installed the required plugin Smart Jail Doors or the plugin has a problem to load.](https://github.com/shanapu/MyJailbreak/wiki/Frequently-Asked-Questions#i-have-this-error)"

> As said. I have all the requirements. I have reinstalled them all several times. I reinstalled the smartjaildoors again and it still doesnt work.

But, on the plugin list you posted above there is no smartjaildoors running...:

> These are the plugins it says are installed.
> ] sm plugins
>....

**Comment by sword134** [comment]
Removed the old one and reinstalled MyJailbreak. 

And as stated above I already reinstalled smartdoors atleast 5 times today. Did it one more time now aswell. However it still doesnt work.

**Comment by shanapu** [comment]
So you tried to install SJD ~5 times and it won't work?
And there are no SJD relevant errors? 
On `sm plugin list` SJD is not shown?  
Are you sure you installed SJD correctly?

sry to say but can't believe that.
But if so, the best is to request help from the smartjaildoors author. About this weird problem.

**Comment by sword134** [comment]
Tried reinstalling soucemod and then download smartdoors again. This time I didnt use the github version and now it all works. However everytime I do !warden it says its deactivated. I put sm_warden_enable "1"  and sm_warden_become "1" in my server.cfg. It still doesnt work.

**Comment by shanapu** [comment]
>  However everytime I do !warden it says its deactivated.

Sounds like you are in a freeday on the first round. `sm_freeday_firstround "1"` is set as default. 
On eventdays the warden is disabled with `sm_warden_enable "0" .` 
Do `sm_freeday_firstround "0"` _or_ disable freedays plugin _or_ wait until 2nd round and try again.

>  I put sm_warden_enable "1" and sm_warden_become "1" in my server.cfg. It still doesnt work.

You don't need to put these ConVars in your server.cfg. Just edit them in their plugins-config files. (...csgo/cfg/MyJailbreak)

**Comment by shanapu** [comment]
>  This time I didnt use the github version and now it all works. 
On smartjaildoors github there are only the sourcecode files and no compiled plugins binarys (*.smx).
You have to compile them foryourself or use the download pack on Alliedmodders. 
I think this was the first issue.

**Comment by sword134** [comment]
Thank you alot for the responce!

1 last thing however. Sourcemod doesnt change the default language to English even though I set AllowClLanguageVar "off" in the core.cfg.

**Comment by sword134** [comment]
Thank you for the fast response and support.

You may mark this as solved now 👍
