### ISSUE TITLE
Request: error Client index -1

### ISSUE THREAD

**Issue by Caaine** [shanapu/MyJailbreak#142]
_L 11/02/2016 - 01:48:56: [SM] Blaming: MyJailbreak/warden.smx
L 11/02/2016 - 01:48:56: [SM] Call stack trace:
L 11/02/2016 - 01:48:56: [SM]   [0] PrintCenterText
L 11/02/2016 - 01:48:56: [SM]   [1] Line 346, MyJailbreak/Modules/Warden/handcuffs.sp::Timer_Progress
L 11/02/2016 - 01:48:57: [SM] Exception reported: Client 2 is not in game
L 11/02/2016 - 01:48:57: [SM] Blaming: MyJailbreak/warden.smx
L 11/02/2016 - 01:48:57: [SM] Call stack trace:
L 11/02/2016 - 01:48:57: [SM]   [0] PrintCenterText
L 11/02/2016 - 01:48:57: [SM]   [1] Line 351, MyJailbreak/Modules/Warden/handcuffs.sp::Timer_Progress
L 11/02/2016 - 01:48:58: [SM] Exception reported: Client 2 is not in game
L 11/02/2016 - 01:48:58: [SM] Blaming: MyJailbreak/warden.smx
L 11/02/2016 - 01:48:58: [SM] Call stack trace:
L 11/02/2016 - 01:48:58: [SM]   [0] PrintCenterText
L 11/02/2016 - 01:48:58: [SM]   [1] Line 356, MyJailbreak/Modules/Warden/handcuffs.sp::Timer_Progress
L 11/02/2016 - 01:48:59: [SM] Exception reported: Client 2 is not in game
L 11/02/2016 - 01:48:59: [SM] Blaming: MyJailbreak/warden.smx
L 11/02/2016 - 01:48:59: [SM] Call stack trace:
L 11/02/2016 - 01:48:59: [SM]   [0] PrintCenterText
L 11/02/2016 - 01:48:59: [SM]   [1] Line 341, MyJailbreak/Modules/Warden/handcuffs.sp::Timer_Progress
L 11/02/2016 - 02:25:27: Error log file session closed._

L 11/04/2016 - 18:25:46: [SM] Exception reported: Client index -1 is invalid
L 11/04/2016 - 18:25:46: [SM] Blaming: MyJailbreak/warden.smx
L 11/04/2016 - 18:25:46: [SM] Call stack trace:
L 11/04/2016 - 18:25:46: [SM]   [0] VFormat
L 11/04/2016 - 18:25:46: [SM]   [1] Line 174, D:\Code\MyJailbreak\addons\sourcemod\scripting\include\colors.inc::CPrintToChatAll
L 11/04/2016 - 18:25:46: [SM]   [2] Line 230, MyJailbreak/Modules/Warden/deputy.sp::Command_ExitDeputy
L 11/04/2016 - 18:25:46: [SM]   [4] FakeClientCommand
L 11/04/2016 - 18:25:46: [SM]   [5] Line 1059, MyJailbreak/menu.sp::JBMenuHandler

**Comment by mrkos9i4ok** [comment]
https://github.com/shanapu/MyJailbreak/issues/136

**Comment by mrkos9i4ok** [comment]
Last comment

**Comment by Caaine** [comment]
L 11/01/2016 - 17:29:56: [SM] Exception reported: Client index -1 is invalid
L 11/01/2016 - 17:29:56: [SM] Blaming: MyJailbreak/request.smx
L 11/01/2016 - 17:29:56: [SM] Call stack trace:
L 11/01/2016 - 17:29:56: [SM]   [0] GetClientAbsOrigin
L 11/01/2016 - 17:29:56: [SM]   [1] Line 424, MyJailbreak/Modules/Request/freekill.sp::RespawnHandler
L 11/01/2016 - 17:35:07: Error log file session closed.

**Comment by shanapu** [comment]
hi mates, 
the Timer_Progress error should be fixed with latest commit.

now i going on search for the request error.

@Caaine Please open one Issue per errors/problem. Split many/different errors/problems to different Issues. Helps me on overview and don't forget things. Thanks!

**Comment by shanapu** [comment]
close cause fixed. if not please open new issue.
