### ISSUE TITLE
Voice + Warden problem 

### ISSUE THREAD

**Issue by Hexer10** [shanapu/MyJailbreak#144]
When a player get swapped to CTs with !guard (MyJailBreak Ratio plugin) it bugs with sm_hosties and for the first 45 seconds the CTs swapped can't talk.
And the warden when a mod type !fw (firewarden) it doens't  leave.

**Comment by shanapu** [comment]
> When a player get swapped to CTs with !guard (MyJailBreak Ratio plugin) it bugs with sm_hosties and for the first 45 seconds the CTs swapped can't talk.

should be easy to fix. I'm on it

> And the warden when a mod type !fw (firewarden) it doens't leave.

hmm.. works like charm for me. Does your "mods" got `ADMFLAG_GENERIC = "b" `?

**Comment by Hexer10** [comment]
Yes, in the change i can see  that the command executed (the warden was fire by...) but he actualy stay.

**Comment by shanapu** [comment]
The Voice problem should be fixed in dev branch. please test.

> i can see that the command executed (the warden was fire by...) but he actualy stay

can't reproduce this. for and some others I asked this works like charm.

BTW.
Please open one Issue  per request/errors/problems. Split many requests/errors/problems to different Issues. Thanks!

**Comment by Hexer10** [comment]
Ok thanks, i solved the bug watching one console log:
`L 11/15/2016 - 13:46:10: "Hexah<80><STEAM_1:0:********><TERRORIST>" say "!fw"
L 11/15/2016 - 13:46:10: [SM] Exception reported: Could not open file "/home/tcagame/db5817ba/2251/csgo/addons/sourcemod/logs/MyJailbreak/MyJB-16-11-14.log"
L 11/15/2016 - 13:46:10: [SM] Blaming: warden.smx
L 11/15/2016 - 13:46:10: [SM] Call stack trace:
L 11/15/2016 - 13:46:10: [SM]   [0] LogToFileEx
L 11/15/2016 - 13:46:10: [SM]   [1] Line 495, MyJailbreak/warden.sp::AdminCommand_RemoveWarden`

and create manually this file: MyJB-16-11-14.log (csgo/addons/sourcemod/logs/MyJailbreak/MyJB-16-11-14.log)

**Comment by shanapu** [comment]
you don't need to create the the file, just the folder was missing `csgo/addons/sourcemod/logs/MyJailbreak`
