### ISSUE TITLE
Zombie round FriendlyFire

### ISSUE THREAD

**Issue by Hexer10** [shanapu/MyJailbreak#146]
In the Zombie round the FriendlyFire turn on, is this normal, if yes there is a CVar to disable it?

**Comment by shanapu** [comment]
will fix this at weekend

**Comment by shanapu** [comment]
I fixed that issue. this should be the final version for TG compatibility.
Consider that the old(https://github.com/shanapu/MyJB-TG_friendlyfire) is obsolent and the plugin is merged to MYJB main dev repo. TeamGames 1.1.0.7

**Comment by mrkos9i4ok** [comment]
I'm such a start to the game (Zombies) and zombies spawn with weapons)))

**Comment by shanapu** [comment]
to clarify:
On eventday 'Zombie' the CTs (zombies) can pick up weapons? right?
Thats shouldn't happen. I will test it when I'm at home in 2-3hours.

do you use KissLicks TeamGames?
Does the other eventday (hide, suicide) where only one team got weapon the same problem?
Any errors?

**Comment by mrkos9i4ok** [comment]
No,pick up weapons must not.Weapons issued at the weapon menu in weapon.smx.

**Comment by shanapu** [comment]
sry, what?
please use proper english.
This issue is about a conflict with TeamGames. please open an new issue if you got an issue.

**Comment by shanapu** [comment]
I need to implement FF toggle in warden menu.

**Comment by mrkos9i4ok** [comment]
L 11/23/2016 - 19:21:28: [SM] Exception reported: Invalid convar handle 0 (error 4)
L 11/23/2016 - 19:21:28: [SM] Blaming: MyJailbreak/myjailbreak_teamgames.smx
L 11/23/2016 - 19:21:28: [SM] Call stack trace:
L 11/23/2016 - 19:21:28: [SM]   [0] ConVar.IntValue.get
L 11/23/2016 - 19:21:28: [SM]   [1] Line 79, MyJailbreak/Add-ons/myjailbreak_teamgames.sp::Event_RoundStart_Post

if  tg_cvar_friendlyfire "0" all ff not worked

if tg_cvar_friendlyfire "1" TG work,mejailbreak not(ff in menu and games)

if tg_cvar_friendlyfire "2" TG work,mejailbreak not(ff in menu and games)

**Comment by shanapu** [comment]
> me: do you use KissLicks TeamGames?

> you: **I do not use KissLicks TeamGames**

Please talk to me! give me informations! Do you use TeamGames now?

- If you don't use Kisslicks TeamGames, you don't need myjailbreak_teamgames.smx 
- If you use Kisslicks TeamGames, you need the latest version of TG (1.1.0.7)

**Comment by mrkos9i4ok** [comment]
1)if i don`t use Kisslicks TeamGames,all works!Me don`t need myjailbreak_teamgames.smx
