### ISSUE TITLE
Remove CTs Armor ( sm_weapons_kevlar) on Last request

### ISSUE THREAD

**Issue by shanapu** [shanapu/MyJailbreak#152]
request by hexah to strip kevlar & helm on a last request.
Im not sure to implement this into weapons, core or an standalone plugin.

`
		int iHelmet = FindSendPropInfo("CCSPlayer", "m_bHasHelmet");
		int iKevlar = FindSendPropInfo("CCSPlayer", "m_ArmorValue");
		
		SetEntData(client, iHelmet, 0);
		SetEntData(client, iKevlar, 0);`

**Comment by good-live** [comment]
That should be part oft hosties or a standalone Plugin.

**Comment by shanapu** [comment]
new plugin Hosties - Remove Kevlar & Helmet on Last Request
https://github.com/shanapu/Hosties---Remove-Armor-on-LR

this is a first fast solution. I will improve it to only strip armor of last request counterparties.

`//Includes
#include <sourcemod>
#include <sdktools>
#include <sdkhooks>
#include <hosties>
#include <lastrequest>


//Compiler Options
#pragma semicolon 1
#pragma newdecls required


//Info
public Plugin myinfo =
{
	name = "Hosties - Remove Armor on LR", 
	author = "shanapu", 
	description = "Hosties - Remove Kevlar & Helmet on Last Request", 
	version = "1.0", 
	url = "https://github.com/shanapu"
};


//Start Timer on Last Request
public int OnAvailableLR(int Announced)
{
	for (int i = 1; i <= MaxClients; i++) if(IsPlayerAlive(i))
	{
		SetEntProp(i, Prop_Send, "m_ArmorValue", 0);
		SetEntProp(i, Prop_Send, "m_bHasHelmet", 0);
	}
}`

**Comment by mrkos9i4ok** [comment]
```
L 12/27/2016 - 23:57:03: [SM] Exception reported: Client 2 is not in game
L 12/27/2016 - 23:57:03: [SM] Blaming: MyJailbreak/RemoveArmorLR.smx
L 12/27/2016 - 23:57:03: [SM] Call stack trace:
L 12/27/2016 - 23:57:03: [SM]   [0] IsPlayerAlive
L 12/27/2016 - 23:57:03: [SM]   [1] Line 28, D:\Code\MyJailbreak\addons\sourcemod\scripting\RemoveArmorLR.sp::OnAvailableLR
L 12/27/2016 - 23:57:03: [SM]   [3] Call_Finish
L 12/27/2016 - 23:57:03: [SM]   [4] Line 936, hosties/lastrequest.sp::LastRequest_RoundFreezeEnd
```

**Comment by shanapu** [comment]
ok, stupid one. thanks for report!
fixed version
https://github.com/shanapu/Hosties---Remove-Armor-on-LR

**Comment by shanapu** [comment]
I think this is a 'good workaround' so far. 


> I will improve it to only strip armor of last request counterparties.

I don't think it is necessary, maybe sometime - when I'm bored.

**Comment by shanapu** [comment]
https://github.com/dataviruset/sm-hosties/pull/65
