### ISSUE TITLE
Dropped Jan from server: Pure server: file

### ISSUE THREAD

**Issue by Rundruf** [shanapu/MyJailbreak#161]
Hello,

I Need help to fix my error:
"Dropped Jan from server: Pure server: file [GAME]\materials/decals\myjailbreak\terror-fix.vmt does not match the server's file."

[STEAM_1:1:113864178] Pure server: file: GAME\materials/models/gmod_tower/starglass.vtf ( 1 6032 1640 ) could not open file to hash ( benign for now ) : 31cc6e7334615d9f692e85a14c6dc86a :

[STEAM_1:1:113864178] Pure server: file: GAME\materials/sprites/store/trails/doublerainbow.vmt ( 1 121 79 ) could not open file to hash ( benign for now ) : 12370414a66b9def018752437092196b :

[STEAM_1:1:113864178] Pure server: file: GAME\materials/models/weapons/v_models/cso_knife/cso_katana.vmt ( 1 179 b3 ) could not open file to hash ( benign for now ) : fc7052482775f6ec19d30aa51b3c2a95 :

[STEAM_1:1:113864178] Pure server: file: GAME\materials/particle/flgod_fix/letter_g.vmt ( 1 242 f2 ) could not open file to hash ( benign for now ) : b3811c228fa6a7042ff4a1bfdf044c6e :

[STEAM_1:1:113864178] Pure server: file: GAME\materials/particle/particle_modulate_01_noz_nodepth.vmt ( 1 119 77 ) could not open file to hash ( benign for now ) : 19c5943221b4021d509932acc083bf63 :

[STEAM_1:1:113864178] Pure server: file: GAME\materials/sprays/plg/plg4.vmt ( 1 122 7a ) could not open file to hash ( benign for now ) : 8e38adf7648d85e0a3bdefb16c320b79 :

[STEAM_1:1:113864178] Pure server: file: GAME\materials/models/weapons/v_models/arms/eminem/cloud_9/ct_base_glove_color.vtf ( 1 1398672 155640 ) could not open file to hash ( benign for now ) : 06fc5e06a580d85f4d0dfe31f7a18d7a :

[STEAM_1:1:113864178] Pure server: file: GAME\sound/misc/tecnohard/plg_res_07.mp3 ( 1 156621 263cd ) could not open file to hash ( benign for now ) : 5ecee3b82cba35cd8d9aceb2174c9577 :

[STEAM_1:1:113864178] Pure server: file: GAME\materials/models/weapons/v_models/battery_hands/arms.vmt ( 1 565 235 ) could not open file to hash ( benign for now ) : 31380c8bc5df017950cff565e5cd461a :

[STEAM_1:1:113864178] Pure server: file: GAME\materials/models/weapons/v_models/lightsaber/1blazer.vmt ( 1 143 8f ) could not open file to hash ( benign for now ) : e3f89f639c5aa60afdc63077d738de86 :

[STEAM_1:1:113864178] Pure server: file: GAME\models/effects/bday_gib01.phy ( 1 881 371 ) could not open file to hash ( benign for now ) : 6f7cc1216b8e45f8bd72cc77cf6548bf :

[STEAM_1:1:113864178] Pure server: file: GAME\models/weaponf/v_knife_tridagger_v2.mdl ( 1 15904 3e20 ) could not open file to hash ( benign for now ) : 75a82fff94d860dcb5e3e0429c08df4e :

[STEAM_1:1:113864178] Pure server: file: GAME\particles/nade_trails_v1.pcf ( 1 30678 77d6 ) could not open file to hash ( benign for now ) : 278bd1ab550c36e72922a3f41eee0e24 :

[STEAM_1:1:113864178] Pure server: file: GAME\materials/models/weapons/lily_hand/female04_eu_arms_d.vtf ( 1 1398324 155634 ) could not open file to hash ( benign for now ) : 9012b729024ae2b52e6a17e132972cca :

[STEAM_1:1:113864178] Pure server: file: GAME\materials/models/weapons/v_models/knife_dtail/dragontail_ref.vtf ( 1 699568 aab60 ) could not open file to hash ( benign for now ) : 8d7bfe704d18dbd9f715712dda883be3 :

[STEAM_1:1:113864178] Pure server: file: GAME\materials/models/weaponf/kabar/kabar.vtf ( 1 2097633 200091 ) could not open file to hash ( benign for now ) : bc62179f16ac18c14901fcd14f2c7604 :

[STEAM_1:1:113864178] Pure server: file: GAME\materials/models/gmod_tower/3dglasses.vmt ( 1 115 73 ) could not open file to hash ( benign for now ) : 958a2c40349334b640d7b381ed236e7e :

[STEAM_1:1:113864178] Pure server: file: GAME\materials/models/weapons/v_models/battery_hands/btr_af01_mask.vtf ( 1 699608 aab88 ) could not open file to hash ( benign for now ) : 861c684e8517ed1aa15c7e51c8d4235f :

[STEAM_1:1:113864178] Pure server: file: GAME\materials/sprites/store/trails/arrowrainbow.vmt ( 1 120 78 ) could not open file to hash ( benign for now ) : 06e4b083f74bdd27645301150afd5346 :

[STEAM_1:1:113864178] Pure server: file: GAME\materials/models/weapons/v_models/arms/eminem/virtus_pro/ct_base_glove.vmt ( 1 710 2c6 ) could not open file to hash ( benign for now ) : 73e9602b820852fe4f446a71eadab11e :

[STEAM_1:1:113864178] Pure server: file: GAME\materials/models/weaponf/v_models/dtb_dagger/dtb_exp.vtf ( 1 5592976 555640 ) could not open file to hash ( benign for now ) : 282e8f17b394508539a74e04f3400405 :

[STEAM_1:1:113864178] Pure server: file: GAME\materials/sprites/store/trails/potleaf.vmt ( 1 115 73 ) could not open file to hash ( benign for now ) : 655923cdd98a325d31ce02f42f2b93d0 :

[STEAM_1:1:113864178] Pure server: file: GAME\materials/models/weapons/v_models/battery_hands/btr_af01_normal.vtf ( 1 5592948 555624 ) could not open file to hash ( benign for now ) : 558c0ce1b37e5deb87c4453c0fdfa658 :

[STEAM_1:1:113864178] Pure server: file: GAME\materials/sprites/store/trails/arrowrainbow.vtf ( 1 16800 4050 ) could not open file to hash ( benign for now ) : 7a8271c45e8da183cd61ac38b875c67f :

[STEAM_1:1:113864178] Pure server: file: GAME\materials/sprites/store/trails/potleaf.vtf ( 1 16928 40d0 ) could not open file to hash ( benign for now ) : 88baf239ff8a991ed48da0a72370425e :

[STEAM_1:1:113864178] Pure server: file: GAME\materials/models/weapons/v_models/request cso/frame water rifle back.vmt ( 1 225 e1 ) could not open file to hash ( benign for now ) : 9388d51739ac261922bc65a2cc00d1dc :

[STEAM_1:1:113864178] Pure server: file: GAME\materials/models/gmod_tower/3dglasses.vtf ( 1 350096 55640 ) could not open file to hash ( benign for now ) : 72bf327567082861a13896638cebdbf9 :

[STEAM_1:1:113864178] Pure server: file: GAME\materials/models/weaponf/kabar/kabar.vmt ( 1 659 293 ) could not open file to hash ( benign for now ) : 02cfc8eafef7e826b7ffa24ec21eaad7 :

[STEAM_1:1:113864178] Pure server: file: GAME\materials/decals/myjailbreak/terror-fix.vmt ( 1 90 5a ) file does not match : 9ae261d8926fbced38f088caad52af1e : c9d7efe86dd15d1430a7c8ded78c8ac2

**Comment by Rundruf** [comment]
//close https://developer.valvesoftware.com/wiki/Pure_Servers

**Comment by shanapu** [comment]
[FAQ - I get kicked with reason: "Disconnect: Pure server: file [GAME]\materials/overlays\myjailbreak\XXX does not match the server's file"](https://github.com/shanapu/MyJailbreak/wiki/Frequently-Asked-Questions#i-get-kicked-with-reason-disconnect-pure-server-file-gamematerialsoverlaysmyjailbreakxxx-does-not-match-the-servers-file)
