### ISSUE TITLE
Bug; admin menu - MyJailBreak

### ISSUE THREAD

**Issue by Include5** [shanapu/MyJailbreak#162]
Name functions does not display fully
![1](https://cloud.githubusercontent.com/assets/20662946/21849534/4b1f24a8-d817-11e6-8953-0e03ca82f97f.png)
![1](https://cloud.githubusercontent.com/assets/20662946/21849535/4b1f5248-d817-11e6-9238-a780a183786a.png)
Other longer functions in Russian displayed fully

**Comment by shanapu** [comment]
This bug was already mentioned here: #55 

and this was my [end result](https://github.com/shanapu/MyJailbreak/issues/55#issuecomment-262589201).

> After longer research and talk with some other devs, I don't see a solution for this. This is an hardcoded valve issue.
> I just see to shorten the text.
