### ISSUE TITLE
Apearing on server's chat "Client: 1 Status: 0" when left click on the mouse

### ISSUE THREAD

**Issue by EsTaNG9** [shanapu/MyJailbreak#163]
So the problem is this: http://prnt.sc/dxex31

What appears in the server's chat:
Client: 1
Status: 0
Client: 1
Status: 0
...

I took a llok at the code and I didnt find anything.

Ty for the help

**Comment by shanapu** [comment]
Why do you think this comes from MyJailbreak?

**Comment by EsTaNG9** [comment]
When I remove the entire MyJailbreak this menssage doesnt appear

**Comment by shanapu** [comment]
In the whole MyJailbreak code there is no "Client:" nor "Status:".
Please post your sm plugins list output.

**Comment by shanapu** [comment]
I assume you fixed this. I close this.
If you still got problems, comment here or open a new issue.

**Comment by shanapu** [comment]
My Magic glass ball said: 
He is using baras TeamBans. 
He has not read the install instruction. 
He inadvertently installed teambans_api.smx
