### ISSUE TITLE
[REQ]Enable join CT after a certain play time.

### ISSUE THREAD

**Issue by Hexer10** [shanapu/MyJailbreak#165]
Hi,
Is possible to disable to join to CT team (!guard) until the player played an certain amount of time (like 2h-1h of playtime).
Thanks in advance

**Comment by shanapu** [comment]
It's possible to make a ratio support plugin for 
MostActive - https://forums.alliedmods.net/showthread.php?p=1751973
and Player Analytics - https://forums.alliedmods.net/showthread.php?p=2067976
maybe and other?

Both don't ship a native for an "easy" check. I have to query their database. need some time, cause low priority, now.

**Comment by shanapu** [comment]
be04a8ceaad389b3c174552bf58fa2c12ff5471b here is guard/warden restriction with frans1cos most active playtime.

**Comment by shanapu** [comment]
since Player Analytics doesn't ship natives for an easy check and I'm more familar with mostactive.
I won't support Player Analytics in near future and close this.
