### ISSUE TITLE
Download doesn't have complete files

### ISSUE THREAD

**Issue by ngx3** [shanapu/MyJailbreak#167]
When I go to download from https://shanapu.de/MyJailbreak/ the master branch doesn't have the .sp files, neither does github. So where do I download the full release? I don't think you can compile smx files.

**Comment by shanapu** [comment]
On https://shanapu.de/MyJailbreak/ are precompiled binarys (.smx).
If you want the sourcefiles (.sp) you find them here on github.
https://github.com/shanapu/MyJailbreak/tree/master/addons/sourcemod/scripting/MyJailbreak

If you need help to compile the files take a look here: https://github.com/shanapu/MyJailbreak/wiki/Compile-MyJailbreak

**Comment by ngx3** [comment]
> edit: maybe take a look here:
https://github.com/shanapu/MyJailbreak/wiki/Installation

I followed this and it's not working? Was it suppose to work without .sp files? Or do you want me to download master (smx) and dev(sp)? Sorry kinda confused here.

**Comment by shanapu** [comment]
.sp files are the sourcefiles. You don't need them to run the plugins on your server. You only need the .sp files when you want to (edit and) compile the sourcecode to a binary (.smx).

If you followed the installation guide myjailbreak should run fine. Have you looked through the [FAQ](https://github.com/shanapu/MyJailbreak/wiki/Frequently-Asked-Questions)? 

the different between master & dev
master - all features are tested well. this version will not be changed for month.
dev - updates & new features on weekly may daily updates. May a bit buggy.

**Comment by shanapu** [comment]
I added the source to the builds on http://shanapu.de/myjailbreak
all builds after https://github.com/shanapu/MyJailbreak/commit/5e7fb5d279d1bd03725ad7f45861e1dd307887be master 
&
https://github.com/shanapu/MyJailbreak/commit/26eb3ef902dd3d924b678248052699a41217e709 dev
got their sources.

sry for any discontent
