### ISSUE TITLE
Error: on remove weapon: Weapon 'N' is not owned by client 'N'

### ISSUE THREAD

**Issue by Hexer10** [shanapu/MyJailbreak#168]
When using the menu sometimes happen this:

```
L 01/29/2017 - 19:56:57: [SM] Exception reported: Weapon 1516 is not owned by client 3
L 01/29/2017 - 19:56:57: [SM] Blaming: weapons.smx
L 01/29/2017 - 19:56:57: [SM] Call stack trace:
L 01/29/2017 - 19:56:57: [SM]   [0] CS_DropWeapon
L 01/29/2017 - 19:56:57: [SM]   [1] Line 82, /home/travis/build/shanapu/MyJailbreak/addons/sourcemod/scripting/include/mystocks.inc::StripAllPlayerWeapons
L 01/29/2017 - 19:56:57: [SM]   [2] Line 346, addons/sourcemod/scripting/MyJailbreak/weapons.sp::GiveSavedWeapons
L 01/29/2017 - 19:56:57: [SM]   [3] Line 760, addons/sourcemod/scripting/MyJailbreak/weapons.sp::Menu_Secondary
```

**Comment by shanapu** [comment]
thanks for the report.
I saw [this error before](https://github.com/shanapu/MyJailbreak/issues/134) and tried to fix it, without success.
This is a really weird one. "Weapon X (dropped by client Y) is not owned by client Y"? Idk why.
But it should be harmless, so it don't affect the gameplay. 
I'm on it, but could need help.

**Comment by Hexer10** [comment]
Sometimes the clients dont have any weapon when using the menu, and they have to redo !guns > Same Weapon a couple of times.

**Comment by shanapu** [comment]
Im not sure but maybe this last commit fix it. It's a weird one.
Need some testers. Thx

**Comment by shanapu** [comment]
any new errors on this?

**Comment by Hexer10** [comment]
Seems no more errors in console (In games too)

**Comment by shanapu** [comment]
last fix has bugged the weapons plugin, here is a new try, pls report back if new errors appears
