### ISSUE TITLE
Beacon last player(s)

### ISSUE THREAD

**Issue by shanapu** [shanapu/MyJailbreak#17]
1. Beacon for the last CT on Last Guard Rule
2. Beacon for last alive player in a Team on a EventDay
3. Beacon for all alive players after x time on a Eventday

**Comment by devu4** [comment]
Really think you should add this feature in next update

**Comment by shanapu** [comment]
how should we integrate beacon to all event days? is this correct thinking?

All with cvar to dis/enable beacon feature & choose last alive count / time left ( _x_ )

Catch
Beacon last _x_ free prisoners 
Beacon on _x_ time left (Guards & prisoners or just prisoner? Fairness? or even a cvar to choose? cvar necessary?)

Cowboy
Beacon last _x_ players
Beacon All on _x_ time left 

DealDamage
Beacon All with slow interval

Drunk
Beacon last _x_ players
Beacon All on _x_ time left 

Duckhunt
Beacon _x_ last ducks
Beacon ducks on _x_ time left 

Free for All
Beacon last _x_ players
Beacon All on _x_ time left 

HE Battle
Beacon last _x_ players
Beacon All on _x_ time left 

Hide
Beacon last _x_ prisoner
Beacon All on _x_ time left 

Knife Fight
Beacon last _x_ players
Beacon All on _x_ time left 

No Scope
Beacon last _x_ players
Beacon All on _x_ time left 

Suicide bomber
Beacon _x_ last guards
Beacon guards on _x_ time left 

Torch Relay
No beacon -> #96

War
Beacon last _x_ guards
Beacon last _x_ prisoner
Beacon All on _x_ time left 

Zeus
Beacon last _x_ players
Beacon All on _x_ time left 

Zombie
Beacon last _x_ humans
Beacon all zombies with slow interval

I did 2 new natives for easy use:

`/*********************************************************
 * Set client Beacon
 *
 *
 * @noreturn
 *********************************************************/
native void BeaconOn(int client, float interval);


/*********************************************************
 * Remove client Beacon
 *
 *
 * @noreturn
 *********************************************************/
native void BeaconOff(int client);`

**Comment by devu4** [comment]
I think beacon all players to make it fair on all event days and lastguard and have a cvar to disable this. 

I don't think beacon when there is x prisoners and x humans is needed.

**Comment by devu4** [comment]
OK as getting round time left is hard and sometimes buggy, I thin you should have 2 cvars. 
One TimeTillBeacon which is timer value to enable beacon and EnableBeacon. This is cvar for all days and lastguard.

**Comment by shanapu** [comment]
> I think beacon all players to make it fair on all event days

ok

> TimeTillBeacon which is timer value to enable beacon and EnableBeacon. These are cvars for all days and lastguard.

`sm_myjb_beacon_enable` - has an effect on all days & lgr
or
`sm_war_beacon_enable, sm_ffa_beacon_enable, ...` - every single day has its own cvar?

**Comment by devu4** [comment]
I think have cvar for each day cause some people will want to disable it for certain days.
So sm_war_beacon_enable, sm_ffa_beacon_enable is better.
