### ISSUE TITLE
Warden Friendly fire: enable feature on TeamGames

### ISSUE THREAD

**Issue by Hexer10** [shanapu/MyJailbreak#170]
Is there anyway the get the warden plugin (ff module) works without conflicts with TeamGames (by KissLick)
Thanks!

**Comment by shanapu** [comment]
hmm... the friendly fire module of myjailbreaks warden should be auto disabled when you use TeamGames & myjailbreak_teamgames.smx. 
I going to test it when I'm back at home. Are there any other conflicts except FF?

**Comment by Hexer10** [comment]
> hmm... the friendly fire module of myjailbreaks warden should be auto disabled when you use TeamGames & myjailbreak_teamgames.smx.

I didn't know that, but is there any way the get they work 'good' togheter?
 
For now no more issues with TeamGames.

**Comment by shanapu** [comment]
hmm just tested it, and for me the friendly fire module was auto disabled, so there should no conflict with TG.
but I try to make the FF compatible to TG, but need some time. maybe a it need a edit on TGs side

**Comment by Hexer10** [comment]
Yes It get disabled, I would ask if the FF module can get enabled while using TG,

> but I try to make the FF compatible to TG, but need some time.

Thanks

**Comment by Hexer10** [comment]
mhh seems not works, beacause the comms doesn't load:
sm_warden_ff "1"
sm_warden_cmds_ff "isff, friendlyfire"

but when i do /isff the command appears like it doesn't exits

**Comment by shanapu** [comment]
just tested it this morning.
With Teamgames installed & latest myjailbreak_teamgames the menu items & commands for warden & their function works well.
be sure you have latest myjailbreak_teamgames

**Comment by Hexer10** [comment]
Yeah, thats worked (After updating all),
Thanks for the updates!
