### ISSUE TITLE
Ratio: steamgroups support plugin 

### ISSUE THREAD

**Issue by shanapu** [shanapu/MyJailbreak#173]
a new support plugin for ratio, so only members of define steamgroups can join ct

**Comment by good-live** [comment]
You should geht the group status upon connecting. The steamworks request could take some time. It's not really a good idea to send that within a event forward.

**Comment by shanapu** [comment]
I am not surprised.
I was stoned, tired and lazy this night... first time with steamworks. I already thought " it was to easy".
Thanks for the hint!

**Comment by shanapu** [comment]
i moved the check to 
```
public void OnClientPostAdminCheck(int client)
{
	if (SteamWorks_GetUserGroupStatus(client, gc_iGroupsID.IntValue))
	{
		IsMember[client] = true;
	}
}
```

**Comment by good-live** [comment]
You should also reset the IsMember[client] variable, when the client is disconnecting or when the client isn't in the group.

**Comment by shanapu** [comment]
Much Thanks for your advise!
