### ISSUE TITLE
Warden: change forward warden_OnWardenCreated from void to Action

### ISSUE THREAD

**Issue by shanapu** [shanapu/MyJailbreak#176]
I want to change the forward` void warden_OnWardenCreated` to `Action warden_OnWardenCreate` to give possibility to block player from become warden for 3th party plugins. 
So I would extend the ratio support plugins to support warden too. 
Like e.g. `sm_ratio_stamm "500"` & `sm_warden_stamm "800"`

In this way I want to change wardens plugin libary name to "mywarden" & rename the natives/forwards from `warden_*` to `MyWarden_*`. 
I want to rename them, cause MyJailbreaks warden differs to much from the originals plugins.

What do you think? Good idea, or should we still use the old to keep compatibility?

**Comment by Hexer10** [comment]
for me is best to keep compatibility for plugin like teamgames warden module or your  version of soccerjam (I didn't tested but i think i will)
