### ISSUE TITLE
TeamGames: AutoStop an minigame when last guard.

### ISSUE THREAD

**Issue by Hexer10** [shanapu/MyJailbreak#177]
If the guard start the last guard event while the Ts are doing a minigame they use !guns menu but can hit the CT beacuse as I sad they are doing a minigame

**Comment by shanapu** [comment]
43181d219009b9938e2bb8d6a87ca19cea1b7842
I have make a new forward `MyJailbreak_OnLastGuardRuleStart ` an addes this to myjailbreak'_teamgames to end the current teamgame, remove the teams & remove the fences.

untested.

**Comment by shanapu** [comment]
@Hexer10 had you time to test this?

**Comment by Hexer10** [comment]
Let me update MyJailBreak and i'll do it.
