### ISSUE TITLE
Support for my new CT Bans plugin

### ISSUE THREAD

**Issue by oaaron99** [shanapu/MyJailbreak#180]
I will be releasing this on Alliedmodders soon once I have more time to test for bugs but it would be nice to have support in the ratio plugin so that if anyone switches over they can use it...

https://github.com/oaaron99/CTBans/blob/master/include/ctbans.inc

Let me know if you want any other natives

**Comment by shanapu** [comment]
great work! 
I just pushed a new support plugin to dev branch, just tell me before your release, so I merge it to master.

**Comment by oaaron99** [comment]
Released:
https://forums.alliedmods.net/showthread.php?p=2496711

**Comment by shanapu** [comment]
Beta 11 is out!
