### ISSUE TITLE
Zombie: respawn dead terrors as zombie

### ISSUE THREAD

**Issue by shanapu** [shanapu/MyJailbreak#182]
Idea by DoLMaT
23:38 - DoLMaT: We need to do that to a team T became zombie after death

**Comment by shanapu** [comment]
20:10 - DoLMaT: Everything works except those who were infected did not see through walls


???
12:44 - DoLMaT: If the player has been dropped or has sunk it does not become a zombie
13:52 - DoLMaT: And yet necessary function is to ask the new players CT that would test their knowledge of the rules of jail
???

**Comment by good-live** [comment]
Let me guess:

> DoLMaT: If the player has been dropped or has sunk it does not become a zombie

Means when somebody get's killed by world damage he won't become a zombie.

Problem seems to be that you check if the attacker is valid in the PlayerDeath Callback. (Haven't looked in the IsValidClient Function, but i think 0 isn't considered as a valid client)
https://github.com/shanapu/MyJailbreak/commit/c4fa6923e9b1f4f902e1bf4610cc9bbf42692d5e#diff-83666c32207f299d80f4867f7142bf7cR818

**Comment by shanapu** [comment]
yeah, that's right. 
I assumed to do that like in zombie movies. You must get bitten to transform to a zombie. 
Not everyone is made to be a zombie.

**Comment by shanapu** [comment]
I will make a cvar for that. (yeah, more cvars!)
I would prefer the "bitten-version" but also understand the suicide way.
