### ISSUE TITLE
Unable to load plugin

### ISSUE THREAD

**Issue by RED4911** [shanapu/MyJailbreak#183]
[SM] Unable to load plugin "MyJailbreak/warden.smx": Could not find required plugin "basecomm"

**Comment by Hexer10** [comment]
You must have default  sourcemod plugins that comes when you install sm...
or compile them : https://github.com/alliedmodders/sourcemod/tree/master/plugins

**Comment by shanapu** [comment]
I heard that "SourceBans - Material Design / materialadmin" auto move basecomm and other plugins to disabled folder. I don't know why. 
Maybe I will make basecomm optional.

**Comment by RED4911** [comment]
thx.

**Comment by shanapu** [comment]
should now work with sourcebans - Material Design / materialadmin
