### ISSUE TITLE
Error compiling lastguard.sp

### ISSUE THREAD

**Issue by Hexer10** [shanapu/MyJailbreak#184]
On line 611 is write:
```
public void OnAvailableLR(int Announced)
{
	g_bIsLR = true;

	delete g_hTimerBeacon;
}
```

And it give me back this error:
fuction return type differs from prototype. expeted 'int', but go 'void'.
I think it should be:
```
public int OnAvailableLR(int Announced)
{
	g_bIsLR = true;

	delete g_hTimerBeacon;
}
```

**Comment by shanapu** [comment]
use fixed/latest lastrequest.inc from dev branch or inc shipped with myjailbreak.  
https://github.com/dataviruset/sm-hosties/blob/beta/addons/sourcemod/scripting/include/lastrequest.inc
https://github.com/dataviruset/sm-hosties/blob/beta/addons/sourcemod/scripting/include/lastrequest.inc#L111 void

dev branch of hosties is already in 1.7 syntax
