### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by RED4911** [shanapu/MyJailbreak#185]
L 02/25/2017 - 15:40:36: SourceMod error session started
L 02/25/2017 - 15:40:36: Info (map "jb_sg_dojo_v4-1") (file "errors_20170225.log")
L 02/25/2017 - 15:40:36: [SM] Exception reported: Fatal error creating dynamic native!
L 02/25/2017 - 15:40:36: [SM] Blaming: MyJailbreak/voiceannounce_ex.smx
L 02/25/2017 - 15:40:36: [SM] Call stack trace:
L 02/25/2017 - 15:40:36: [SM]   [0] CreateNative
L 02/25/2017 - 15:40:36: [SM]   [1] Line 37, C:\Users\Администратор\Desktop\MyJAILBREAK\gameserver\addons\sourcemod\scripting\MyJailbreak\voiceannounce_ex.sp::AskPluginLoad2
L 02/25/2017 - 15:40:36: [SM] Failed to load plugin "MyJailbreak/voiceannounce_ex.smx": unexpected error 23 in AskPluginLoad callback.

**Comment by shanapu** [comment]
you have voiceannounce_ex installed two times!
remove on copy.
