### ISSUE TITLE
Myjailbreak MENU is not working

### ISSUE THREAD

**Issue by alesteffann** [shanapu/MyJailbreak#187]
This is my error Errors:
MyJailbreak/menu.smx (MyJailbreak - Menus): Could not find required plugin "smartjaildoors"
MyJailbreak/smartjaildoors.smx (Smart Jail Doors): unexpected error 23 in AskPluginLoad callback

 the plugin smartjaildoors is installed

**Comment by shanapu** [comment]
> MyJailbreak/**smartjaildoors.smx (Smart Jail Doors): unexpected error 23 in AskPluginLoad callback**

This error seems like you have smartjaildoors installed twice.

**Comment by alesteffann** [comment]
yea that was right but the menu still doesnt work

**Comment by shanapu** [comment]
same error? if it still not work it should be an new error...

**Comment by alesteffann** [comment]
reinstalled the server all good now probably the problem occured because the override of the smrtjail
