### ISSUE TITLE
FF in TeamGame and warden menu don`t work

### ISSUE THREAD

**Issue by mrkos9i4ok** [shanapu/MyJailbreak#188]
Error list :

L 02/27/2017 - 18:34:18: [SM] Exception reported: Invalid convar handle 0 (error 4)
L 02/27/2017 - 18:34:18: [SM] Blaming: MyJailbreak/warden.smx
L 02/27/2017 - 18:34:18: [SM] Call stack trace:
L 02/27/2017 - 18:34:18: [SM]   [0] ConVar.IntValue.set
L 02/27/2017 - 18:34:18: [SM]   [1] Line 94, MyJailbreak/Modules/Warden/friendlyfire.sp::Command_FriendlyFire
L 02/27/2017 - 18:34:18: [SM]   [3] FakeClientCommand
L 02/27/2017 - 18:34:18: [SM]   [4] Line 1534, menu.sp::JBMenuHandler

L 02/27/2017 - 19:26:13: [SM] Exception reported: Invalid convar handle 0 (error 4)
L 02/27/2017 - 19:26:13: [SM] Blaming: MyJailbreak/myjailbreak_teamgames.smx
L 02/27/2017 - 19:26:13: [SM] Call stack trace:
L 02/27/2017 - 19:26:13: [SM]   [0] ConVar.IntValue.get
L 02/27/2017 - 19:26:13: [SM]   [1] Line 75, myjailbreak_teamgames.sp::Event_RoundStart_Post

cfg teamgame:

// Force set convar "ff_damage_reduction_bullets", "ff_damage_reduction_grenade", "ff_damage_reduction_grenade_self" and "ff_damage_reduction_other" to "1" every map start? Only for CS:GO. (1 = true, 0 = false)
// -
// Default: "1"
tg_cvar_ff_reduction "1"
// 0 = do nothing "mp_friendlyfire"
// 1 = set "mp_friendlyfire 1" every map start (after configs are loaded)
// 2 = set "mp_friendlyfire 1" when game is in progress and set "mp_friendlyfire 0" otherwise.
// -
// Default: "1"
tg_cvar_friendlyfire "1"
// Force set convar "mp_tkpunish 0" every map start? (1 = true, 0 = false)
// -
// Default: "1"
tg_cvar_tkpunish "1"

**Comment by shanapu** [comment]
I assume you are not on the latest TeamGames. Latest is "1.1.0.7"
