### ISSUE TITLE
Translation issues

### ISSUE THREAD

**Issue by MindaugasR** [shanapu/MyJailbreak#190]
There is some files there you can't understand in what language is translated. I'm talking about English main files:

https://github.com/shanapu/MyJailbreak/blob/master/addons/sourcemod/translations/MyJailbreak.DuckHunt.phrases.txt (Last 2 items - duckhunt_wait)

https://github.com/shanapu/MyJailbreak/blob/master/addons/sourcemod/translations/MyJailbreak.CowBoy.phrases.txt ( cowboy_info_title section)

Maybe later will found more, but at this moments only these 2 files.

**Comment by shanapu** [comment]
fixed.
Thank you!
