### ISSUE TITLE
Skins: new add skins T and CT(random)

### ISSUE THREAD

**Issue by mrkos9i4ok** [shanapu/MyJailbreak#192]
Example:
   cfg: https://github.com/TiBarification/Jail-Warden-Pro/tree/master/cfg/jwp/skin
   sp: https://github.com/TiBarification/Jail-Warden-Pro/blob/master/addons/sourcemod/scripting/jwp_skin.sp

**Comment by shanapu** [comment]
I will not include that. just use [skinchooser](https://forums.alliedmods.net/showthread.php?p=780243) or any other skins plugin. There are enough working out there.
