### ISSUE TITLE
CT Bans

### ISSUE THREAD

**Issue by gastirt** [shanapu/MyJailbreak#193]
Make detailed instructions please. On how I can turn on "CT Bans"

**Comment by good-live** [comment]
CT Bans isn't a native functionality by MaJailbreak. You'll need to choose an existing plugin.
Here you can find the currently supported filters by the ratio system from MyJailbreak: https://github.com/shanapu/MyJailbreak/tree/master/addons/sourcemod/scripting/MyJailbreak/Add-ons

There are also 3 CT Bans plugin supported (Just google and you'll find them)

**Comment by shanapu** [comment]
Yeah Myjailbreak don't have its own CT Ban system included but support different third party plugins.

I updated the [forums post at alliedmodders](https://forums.alliedmods.net/showthread.php?p=2422609) with links to the latest supported plugins.
