### ISSUE TITLE
menu doesnt work

### ISSUE THREAD

**Issue by aishaaisha** [shanapu/MyJailbreak#199]
hi my menu is tottaly not working i installed it and i type in chat !menu and nothing happens but the wepaon menu always when round starts came out just when i type !menu it doesnt show up :)

**Comment by shanapu** [comment]
Without any Infos I can't help you. Please provide an errorlog and take a look here: https://github.com/shanapu/MyJailbreak/wiki/Frequently-Asked-Questions#what-should-i-consider-if-i-open-a-issue-or-post-on-forum

**Comment by aishaaisha** [comment]
my source mod version is : 1.8.0
my meta mod version is : 1.10.6
i have not logs in csgo/addons/sourcemod/log/myjb 
myjb version is : myjb-dev-latest i tried myjb-master-latest but it not working too :)
when i type in console sm_menu menu dont show up :) i think i installed it correctly 

contact me pls on steam:
my steam--http://steamcommunity.com/id/poweredbyaisha/

**Comment by shanapu** [comment]
do you installed all required plugins (e.g smartjaildoors,...)? 
Do you have and error log file in csgo/addons/sourcemod/log/ like errors_20171104.log ?

**Comment by aishaaisha** [comment]
i think that erro i have

**Comment by aishaaisha** [comment]
there is i copied the text at error_20171104.log ::

L 04/11/2017 - 15:48:40: SourceMod error session started
L 04/11/2017 - 15:48:40: Info (map "") (file "errors_20170411.log")
L 04/11/2017 - 15:48:40: Failed lookup of gEntList directly - Reverting to lookup via LevelShutdown
L 04/11/2017 - 15:48:40: Failed lookup of gEntList - Reverting to networkable entities only
L 04/11/2017 - 15:48:45: Error log file session closed.
L 04/11/2017 - 15:48:45: SourceMod error session started
L 04/11/2017 - 15:48:45: Info (map "de_dust2") (file "errors_20170411.log")
L 04/11/2017 - 15:48:45: [SDKTOOLS] Invalid detour address passed - Disabling detour to prevent crashes
L 04/11/2017 - 16:31:13: Error log file session closed.
L 04/11/2017 - 20:15:21: SourceMod error session started
L 04/11/2017 - 20:15:21: Info (map "ba_jail_minecraftparty_v6") (file "errors_20170411.log")
L 04/11/2017 - 20:15:21: [nextmap.smx] FATAL: Cannot load map cycle. Nextmap not loaded.
L 04/11/2017 - 20:15:21: [SM] Exception reported: Mapcycle Not Found
L 04/11/2017 - 20:15:21: [SM] Blaming: nextmap.smx
L 04/11/2017 - 20:15:21: [SM] Call stack trace:
L 04/11/2017 - 20:15:21: [SM]   [0] SetFailState
L 04/11/2017 - 20:15:21: [SM]   [1] Line 139, D:\builds\build-sourcemod-msvc12\windows-1.8\build\plugins\nextmap.sp::FindAndSetNextMap
L 04/11/2017 - 20:15:21: [SM]   [2] Line 109, D:\builds\build-sourcemod-msvc12\windows-1.8\build\plugins\nextmap.sp::OnConfigsExecuted
L 04/11/2017 - 20:31:24: SourceMod error session started
L 04/11/2017 - 20:31:24: Info (map "ba_jail_minecraftparty_v6") (file "errors_20170411.log")
L 04/11/2017 - 20:31:24: [SM] Fatal error encountered parsing translation file "MyJailbreak.Warden.phrases.txt"
L 04/11/2017 - 20:31:24: [SM] Error (line 0, column 0): Stream failed to open
L 04/11/2017 - 20:31:24: [SM] Unable to load plugin "MyJailbreak/playertags.smx": Could not find required plugin "chat-processor"
L 04/11/2017 - 20:31:24: [SM] Exception reported: Language phrase "warden_red" not found (arg 6)
L 04/11/2017 - 20:31:24: [SM] Blaming: MyJailbreak/warden.smx
L 04/11/2017 - 20:31:24: [SM] Call stack trace:
L 04/11/2017 - 20:31:24: [SM]   [0] Format
L 04/11/2017 - 20:31:24: [SM]   [1] Line 92, addons/sourcemod/scripting/MyJailbreak/MyJailbreak/Modules/Warden/marker.sp::PrepareMarkerNames
L 04/11/2017 - 20:31:24: [SM]   [2] Line 86, addons/sourcemod/scripting/MyJailbreak/MyJailbreak/Modules/Warden/marker.sp::Marker_OnPluginStart
L 04/11/2017 - 20:31:24: [SM]   [3] Line 232, addons/sourcemod/scripting/MyJailbreak/warden.sp::OnPluginStart
L 04/11/2017 - 20:31:24: [SM] Unable to load plugin "MyJailbreak/warden.smx": Error detected in plugin startup (see error logs)
L 04/11/2017 - 20:31:24: [SM] Unable to load plugin "MyJailbreak/request.smx": Could not find required plugin "warden"
L 04/11/2017 - 20:31:36: Error log file session closed.
L 04/11/2017 - 20:31:36: SourceMod error session started
L 04/11/2017 - 20:31:36: Info (map "ba_jail_minecraftparty_v6") (file "errors_20170411.log")
L 04/11/2017 - 20:31:36: [SM] Fatal error encountered parsing translation file "MyJailbreak.Warden.phrases.txt"
L 04/11/2017 - 20:31:36: [SM] Error (line 0, column 0): Stream failed to open
L 04/11/2017 - 20:31:36: [SM] Unable to load plugin "MyJailbreak/hud.smx": Could not find required plugin "warden"
L 04/11/2017 - 20:31:36: [SM] Unable to load plugin "MyJailbreak/menu.smx": Could not find required plugin "warden"
L 04/11/2017 - 20:31:36: [nextmap.smx] FATAL: Cannot load map cycle. Nextmap not loaded.
L 04/11/2017 - 20:31:36: [SM] Exception reported: Mapcycle Not Found
L 04/11/2017 - 20:31:36: [SM] Blaming: nextmap.smx
L 04/11/2017 - 20:31:36: [SM] Call stack trace:
L 04/11/2017 - 20:31:36: [SM]   [0] SetFailState
L 04/11/2017 - 20:31:36: [SM]   [1] Line 139, D:\builds\build-sourcemod-msvc12\windows-1.8\build\plugins\nextmap.sp::FindAndSetNextMap
L 04/11/2017 - 20:31:36: [SM]   [2] Line 109, D:\builds\build-sourcemod-msvc12\windows-1.8\build\plugins\nextmap.sp::OnConfigsExecuted
L 04/11/2017 - 20:35:58: [SM] Exception reported: Plugin not runnable
L 04/11/2017 - 20:35:58: [SM] Exception reported: Plugin not runnable
L 04/11/2017 - 20:35:58: [SM] Exception reported: Plugin not runnable
L 04/11/2017 - 20:35:58: [SM] Exception reported: Plugin not runnable
L 04/11/2017 - 20:35:58: [SM] Exception reported: Plugin not runnable
L 04/11/2017 - 20:35:58: [SM] Exception reported: Plugin not runnable
L 04/11/2017 - 20:35:58: Error log file session closed.
L 04/11/2017 - 20:37:03: SourceMod error session started
L 04/11/2017 - 20:37:03: Info (map "ba_jail_minecraftparty_v6") (file "errors_20170411.log")
L 04/11/2017 - 20:37:03: [SM] Fatal error encountered parsing translation file "MyJailbreak.Warden.phrases.txt"
L 04/11/2017 - 20:37:03: [SM] Error (line 0, column 0): Stream failed to open
L 04/11/2017 - 20:37:03: [SM] Unable to load plugin "MyJailbreak/playertags.smx": Could not find required plugin "chat-processor"
L 04/11/2017 - 20:37:03: [SM] Exception reported: Language phrase "warden_red" not found (arg 6)
L 04/11/2017 - 20:37:03: [SM] Blaming: MyJailbreak/warden.smx
L 04/11/2017 - 20:37:03: [SM] Call stack trace:
L 04/11/2017 - 20:37:03: [SM]   [0] Format
L 04/11/2017 - 20:37:03: [SM]   [1] Line 92, addons/sourcemod/scripting/MyJailbreak/MyJailbreak/Modules/Warden/marker.sp::PrepareMarkerNames
L 04/11/2017 - 20:37:03: [SM]   [2] Line 86, addons/sourcemod/scripting/MyJailbreak/MyJailbreak/Modules/Warden/marker.sp::Marker_OnPluginStart
L 04/11/2017 - 20:37:03: [SM]   [3] Line 232, addons/sourcemod/scripting/MyJailbreak/warden.sp::OnPluginStart
L 04/11/2017 - 20:37:03: [SM] Unable to load plugin "MyJailbreak/warden.smx": Error detected in plugin startup (see error logs)
L 04/11/2017 - 20:37:03: [SM] Unable to load plugin "MyJailbreak/request.smx": Could not find required plugin "warden"
L 04/11/2017 - 20:37:10: Error log file session closed.
L 04/11/2017 - 20:37:10: SourceMod error session started
L 04/11/2017 - 20:37:10: Info (map "ba_jail_minecraftparty_v6") (file "errors_20170411.log")
L 04/11/2017 - 20:37:10: [SM] Fatal error encountered parsing translation file "MyJailbreak.Warden.phrases.txt"
L 04/11/2017 - 20:37:10: [SM] Error (line 0, column 0): Stream failed to open
L 04/11/2017 - 20:37:10: [SM] Unable to load plugin "MyJailbreak/hud.smx": Could not find required plugin "warden"
L 04/11/2017 - 20:37:10: [SM] Unable to load plugin "MyJailbreak/menu.smx": Could not find required plugin "warden"
L 04/11/2017 - 20:37:10: [nextmap.smx] FATAL: Cannot load map cycle. Nextmap not loaded.
L 04/11/2017 - 20:37:10: [SM] Exception reported: Mapcycle Not Found
L 04/11/2017 - 20:37:10: [SM] Blaming: nextmap.smx
L 04/11/2017 - 20:37:10: [SM] Call stack trace:
L 04/11/2017 - 20:37:10: [SM]   [0] SetFailState
L 04/11/2017 - 20:37:10: [SM]   [1] Line 139, D:\builds\build-sourcemod-msvc12\windows-1.8\build\plugins\nextmap.sp::FindAndSetNextMap
L 04/11/2017 - 20:37:10: [SM]   [2] Line 109, D:\builds\build-sourcemod-msvc12\windows-1.8\build\plugins\nextmap.sp::OnConfigsExecuted
L 04/11/2017 - 20:37:37: Error log file session closed.
L 04/11/2017 - 20:37:37: SourceMod error session started
L 04/11/2017 - 20:37:37: Info (map "ba_jail_minecraftparty_v6") (file "errors_20170411.log")
L 04/11/2017 - 20:37:37: [SM] Fatal error encountered parsing translation file "MyJailbreak.Warden.phrases.txt"
L 04/11/2017 - 20:37:37: [SM] Error (line 0, column 0): Stream failed to open
L 04/11/2017 - 20:37:38: [nextmap.smx] FATAL: Cannot load map cycle. Nextmap not loaded.
L 04/11/2017 - 20:37:38: [SM] Exception reported: Mapcycle Not Found
L 04/11/2017 - 20:37:38: [SM] Blaming: nextmap.smx
L 04/11/2017 - 20:37:38: [SM] Call stack trace:
L 04/11/2017 - 20:37:38: [SM]   [0] SetFailState
L 04/11/2017 - 20:37:38: [SM]   [1] Line 139, D:\builds\build-sourcemod-msvc12\windows-1.8\build\plugins\nextmap.sp::FindAndSetNextMap
L 04/11/2017 - 20:37:38: [SM]   [2] Line 109, D:\builds\build-sourcemod-msvc12\windows-1.8\build\plugins\nextmap.sp::OnConfigsExecuted

**Comment by aishaaisha** [comment]
i found one more error log name is-- L20171104

L 04/11/2017 - 15:48:45: SourceMod log file session started (file "L20170411.log") (Version "1.9.0.5983")
L 04/11/2017 - 15:48:45: -------- Mapchange to de_dust2 --------
L 04/11/2017 - 16:31:13: -------- Mapchange to de_dust2 --------
L 04/11/2017 - 16:31:14: [UPDATER] Successfully updated gamedata file "sm-cstrike.games/master.games.txt"
L 04/11/2017 - 16:31:14: [UPDATER] Successfully updated gamedata file "sm-cstrike.games/game.csgo.txt"
L 04/11/2017 - 16:31:14: [UPDATER] Successfully updated gamedata file "core.games/engine.csgo.txt"
L 04/11/2017 - 16:31:14: [UPDATER] Successfully updated gamedata file "core.games/blacklist.plugins.txt"
L 04/11/2017 - 16:31:14: [UPDATER] Successfully updated gamedata file "core.games/common.games.txt"
L 04/11/2017 - 16:31:14: [UPDATER] Successfully updated gamedata file "sdkhooks.games/game.doi.txt"
L 04/11/2017 - 16:31:14: [UPDATER] Successfully updated gamedata file "sdkhooks.games/game.fof.txt"
L 04/11/2017 - 16:31:14: [UPDATER] Successfully updated gamedata file "sdkhooks.games/game.empires.txt"
L 04/11/2017 - 16:31:14: [UPDATER] Successfully updated gamedata file "sdkhooks.games/engine.ep2v.txt"
L 04/11/2017 - 16:31:14: [UPDATER] Successfully updated gamedata file "sdkhooks.games/engine.insurgency.txt"
L 04/11/2017 - 16:31:14: [UPDATER] Successfully updated gamedata file "sm-tf2.games.txt"
L 04/11/2017 - 16:31:14: [UPDATER] Successfully updated gamedata file "sdktools.games/game.doi.txt"
L 04/11/2017 - 16:31:14: [UPDATER] Successfully updated gamedata file "sdktools.games/game.tf.txt"
L 04/11/2017 - 16:31:14: [UPDATER] Successfully updated gamedata file "sdktools.games/engine.csgo.txt"
L 04/11/2017 - 16:31:14: [UPDATER] Successfully updated gamedata file "sdktools.games/game.empires.txt"
L 04/11/2017 - 16:31:14: [UPDATER] Successfully updated gamedata file "sdktools.games/engine.insurgency.txt"
L 04/11/2017 - 16:31:14: [UPDATER] SourceMod has been updated, please reload it or restart your server.
L 04/11/2017 - 16:32:07: Log file closed.
L 04/11/2017 - 19:33:11: SourceMod log file session started (file "L20170411.log") (Version "1.9.0.5983")
L 04/11/2017 - 19:33:11: -------- Mapchange to de_dust2 --------
L 04/11/2017 - 19:34:16: -------- Mapchange to de_dust2 --------
L 04/11/2017 - 19:34:17: [UPDATER] Successfully updated gamedata file "sm-cstrike.games/master.games.txt"
L 04/11/2017 - 19:34:17: [UPDATER] Successfully updated gamedata file "sm-cstrike.games/game.csgo.txt"
L 04/11/2017 - 19:34:17: [UPDATER] Successfully updated gamedata file "core.games/engine.csgo.txt"
L 04/11/2017 - 19:34:17: [UPDATER] Successfully updated gamedata file "core.games/blacklist.plugins.txt"
L 04/11/2017 - 19:34:17: [UPDATER] Successfully updated gamedata file "core.games/common.games.txt"
L 04/11/2017 - 19:34:17: [UPDATER] Successfully updated gamedata file "sdkhooks.games/game.doi.txt"
L 04/11/2017 - 19:34:17: [UPDATER] Successfully updated gamedata file "sdktools.games/game.doi.txt"
L 04/11/2017 - 19:34:17: [UPDATER] Successfully updated gamedata file "sdktools.games/engine.csgo.txt"
L 04/11/2017 - 19:34:17: [UPDATER] SourceMod has been updated, please reload it or restart your server.
L 04/11/2017 - 19:40:52: SourceMod log file session started (file "L20170411.log") (Version "1.9.0.5983")
L 04/11/2017 - 19:40:52: -------- Mapchange to de_dust2 --------
L 04/11/2017 - 19:41:29: -------- Mapchange to de_dust2 --------
L 04/11/2017 - 20:13:10: SourceMod log file session started (file "L20170411.log") (Version "1.9.0.5983")
L 04/11/2017 - 20:13:10: Log file closed.
L 04/11/2017 - 20:13:42: SourceMod log file session started (file "L20170411.log") (Version "1.9.0.5983")
L 04/11/2017 - 20:13:42: Log file closed.
L 04/11/2017 - 20:13:50: SourceMod log file session started (file "L20170411.log") (Version "1.9.0.5983")
L 04/11/2017 - 20:13:50: -------- Mapchange to ba_jail_minecraftparty_v6 --------
L 04/11/2017 - 20:15:21: -------- Mapchange to ba_jail_minecraftparty_v6 --------
L 04/11/2017 - 20:20:02: [basecommands.smx] "ゑAiSHAぬ<2><STEAM_1:0:150693439><>" refreshed the admin cache.
L 04/11/2017 - 20:31:24: SourceMod log file session started (file "L20170411.log") (Version "1.9.0.5983")
L 04/11/2017 - 20:31:24: -------- Mapchange to ba_jail_minecraftparty_v6 --------
L 04/11/2017 - 20:31:36: -------- Mapchange to ba_jail_minecraftparty_v6 --------
L 04/11/2017 - 20:35:58: Log file closed.
L 04/11/2017 - 20:37:03: SourceMod log file session started (file "L20170411.log") (Version "1.9.0.5983")
L 04/11/2017 - 20:37:03: -------- Mapchange to ba_jail_minecraftparty_v6 --------
L 04/11/2017 - 20:37:10: -------- Mapchange to ba_jail_minecraftparty_v6 --------
L 04/11/2017 - 20:37:37: -------- Mapchange to ba_jail_minecraftparty_v6 --------

**Comment by aishaaisha** [comment]
btw when i join in server it shows jb-- freeday started or something like that so some plugins working butmenu nah and i want so much that menu :)

**Comment by shanapu** [comment]
just a few samples: `L 04/11/2017 - 20:31:24: [SM] Unable to load plugin "MyJailbreak/playertags.smx": Could not find required plugin "chat-processor"` you have not installed a required plugin (chat-processor)
`L 04/11/2017 - 20:37:03: [SM] Fatal error encountered parsing translation file "MyJailbreak.Warden.phrases.txt"` Translation file is missing/corrupt you have edit the file or not installed MyJailbreak correctly. 
Check steps from [installation guide](https://github.com/shanapu/MyJailbreak/wiki/Installation) twice! 

And lease take a look to the [FAQ](https://github.com/shanapu/MyJailbreak/wiki/Frequently-Asked-Questions). And take a strong eye at the last part [What should I consider if I open a issue or post on forum?](https://github.com/shanapu/MyJailbreak/wiki/Frequently-Asked-Questions#what-should-i-consider-if-i-open-a-issue-or-post-on-forum).
