### ISSUE TITLE
warden is always turned off

### ISSUE THREAD

**Issue by aishaaisha** [shanapu/MyJailbreak#200]
i reinstalled myjb and its working :D but now its always typing when i type in chat: !w this show up-> warden is currently off i tried to type in console sm_warden_enable 1 but not worked

**Comment by aishaaisha** [comment]
there are the newest errors :
OnConfigsExecuted
L 04/11/2017 - 21:33:43: SourceMod error session started
L 04/11/2017 - 21:33:43: Info (map "ba_jail_minecraftparty_v6") (file "errors_20170411.log")
L 04/11/2017 - 21:33:43: [SM] Unable to load extension "dhooks.ext": /hlserver/27632/csgo/addons/sourcemod/extensions/dhooks.ext.so: cannot open shared object file: No such file or directory
L 04/11/2017 - 21:33:43: [SM] Unable to load plugin "voiceannounce_ex.smx": Required extension "dhooks" file("dhooks.ext") not running
L 04/11/2017 - 21:34:20: Error log file session closed.
L 04/11/2017 - 21:34:20: SourceMod error session started
L 04/11/2017 - 21:34:20: Info (map "ba_jail_minecraftparty_v6") (file "errors_20170411.log")
L 04/11/2017 - 21:34:20: [nextmap.smx] FATAL: Cannot load map cycle. Nextmap not loaded.
L 04/11/2017 - 21:34:20: [SM] Exception reported: Mapcycle Not Found
L 04/11/2017 - 21:34:20: [SM] Blaming: nextmap.smx
L 04/11/2017 - 21:34:20: [SM] Call stack trace:
L 04/11/2017 - 21:34:20: [SM]   [0] SetFailState
L 04/11/2017 - 21:34:20: [SM]   [1] Line 139, D:\builds\build-sourcemod-msvc12\windows-1.8\build\plugins\nextmap.sp::FindAndSetNextMap
L 04/11/2017 - 21:34:20: [SM]   [2] Line 109, D:\builds\build-sourcemod-msvc12\windows-1.8\build\plugins\nextmap.sp::OnConfigsExecuted
L 04/11/2017 - 21:49:36: [SM] Exception reported: Plugin not runnable
L 04/11/2017 - 21:49:36: [SM] Exception reported: Plugin not runnable
L 04/11/2017 - 21:49:36: [SM] Exception reported: Plugin not runnable
L 04/11/2017 - 21:49:36: [SM] Exception reported: Plugin not runnable
L 04/11/2017 - 21:49:36: [SM] Exception reported: Plugin not runnable
L 04/11/2017 - 21:49:36: [SM] Exception reported: Plugin not runnable
L 04/11/2017 - 21:49:36: [SM] Exception reported: Plugin not runnable
L 04/11/2017 - 21:49:36: [SM] Exception reported: Plugin not runnable
L 04/11/2017 - 21:49:36: [SM] Exception reported: Plugin not runnable
L 04/11/2017 - 21:49:36: [SM] Exception reported: Plugin not runnable
L 04/11/2017 - 21:49:36: [SM] Exception reported: Plugin not runnable
L 04/11/2017 - 21:49:36: [SM] Exception reported: Plugin not runnable
L 04/11/2017 - 21:49:36: [SM] Exception reported: Plugin not runnable
L 04/11/2017 - 21:49:36: [SM] Exception reported: Plugin not runnable
L 04/11/2017 - 21:49:37: Error log file session closed.

**Comment by aishaaisha** [comment]
my source mod version is : 1.8.0
my meta mod version is : 1.10.6

**Comment by shanapu** [comment]
On default setting the first round ist freeday - on freedays warden is disabled.
