### ISSUE TITLE
idk what is this 

### ISSUE THREAD

**Issue by aishaaisha** [shanapu/MyJailbreak#201]
this error im getting in console Error getting avatar image: playerID(199253670), iIndex(65535)

**Comment by aishaaisha** [comment]
![20170412163806_1](https://cloud.githubusercontent.com/assets/27285502/24963716/aa760686-1f9f-11e7-9d31-d31ed2b0a3a5.jpg)


this is when my friend is alive

**Comment by aishaaisha** [comment]
![20170412163841_2](https://cloud.githubusercontent.com/assets/27285502/24963741/bbddbdb0-1f9f-11e7-8d3c-d76406da066b.jpg)

but when i kill him its good 
pls help idk what is this

**Comment by good-live** [comment]
The model is not downloaded/precached

**Comment by aishaaisha** [comment]
how to fix it?

**Comment by shanapu** [comment]
Dude I pointed you 2 times to the [FAQ](https://github.com/shanapu/MyJailbreak/wiki/Frequently-Asked-Questions). READ IT!

You have a problem with your FastDL files.  
1. Check you have put all nessesary files to your game server([step 3](https://github.com/shanapu/MyJailbreak/wiki/Installation)) & FastDL server([step 4](https://github.com/shanapu/MyJailbreak/wiki/Installation)).  
2. Check you have add the content of `downloads.txt` to your servers `csgo/addons/sourcemod/configs/downloads.ini`([step 5](https://github.com/shanapu/MyJailbreak/wiki/Installation)).  
3. Check on server connect all nessesary files get downloaded. After connection open console and look for something like:  `Downloading http://YourFastDL.tld/csgo/models/player/custom_player/legacy/security/security.mdl.bz2.` 
`Download finished! `
