### ISSUE TITLE
Voice

### ISSUE THREAD

**Issue by szajnimetagross** [shanapu/MyJailbreak#202]
Terrorist cant hear ct if i turn 
sv_alltalk 1 nothing changes

**Comment by bchewy** [comment]
sv_alltalk 1 = Enables Communication between both teams
sv_full_alltalk 1 = Enables Voice/Text-chat for Spectators
sv_deadtalk 1 = Enables that dead people can talk with alive players

else
https://forums.alliedmods.net/showpost.php?p=1807997&postcount=14

**Comment by szajnimetagross** [comment]
Repaired it thanks for help

But can i ask why every round is only 1 minute? Cant change it with mp_roundtime its annoying to extend round every time

**Comment by shanapu** [comment]
"sv_alltalk" = "1" - Deprecated. Replaced with **sv_talk_enemy_dead** and **sv_talk_enemy_living**.

When you round time is only 1 minute: 

- You have not installed MyJailbreak correctly - recheck all installation steps twice.
- You have a 3th party plugin which conflicts with MyJB

please post you plugins list & check you installation

**Comment by shanapu** [comment]
I close this cause the voice problem was solved.
When you still got problems open an new issue.
Please take a look to the [FAQ](https://github.com/shanapu/MyJailbreak/wiki/Frequently-Asked-Questions) before open a new issue.
