### ISSUE TITLE
/lr 

### ISSUE THREAD

**Issue by szajnimetagross** [shanapu/MyJailbreak#204]
I have a bug /lr unlocks when 2 players are left instead of last one.

**Comment by shanapu** [comment]
Last request is part of sm-hosties not of MyJailbreak.
Please check your configs and read the description of the plugins before open an (stupid) issue.

sm_hosties_lr_ts_max "2" The maximum number of terrorists left to enable LR: 0 - LR is always enabled, >0 - maximum number of Ts
