### ISSUE TITLE
Futuristic Nades Event

### ISSUE THREAD

**Issue by Hexer10** [shanapu/MyJailbreak#205]
Hi,
I'd like to see an event with [Futurist Granades](https://forums.alliedmods.net/showthread.php?p=2499362) like an FFA but with that nades, also to see the nades for all player if they are locked to a team.
Thanks!

**Comment by shanapu** [comment]
yeah, I already though about something like this for MyJailShop as shop item. But eventday sounds like fun too!

**Comment by Hexer10** [comment]
To help with this I've done a native: https://github.com/Rachnus/Futuristic-Grenades/pull/1 .

**Comment by shanapu** [comment]
I close this.
Right now I stop developing new events.
Also there is a new cool grenades plugins with nice effects.
https://forums.alliedmods.net/showthread.php?t=309154

I think MyJB got enough event days and should aim of a stable RC.
