### ISSUE TITLE
Update ratio

### ISSUE THREAD

**Issue by mrkos9i4ok** [shanapu/MyJailbreak#208]
Please do so, so that when the guard bans, which alone, do not need to kill everyone, to have new guards.

**Comment by shanapu** [comment]
Do I understand right, when there is only one CT and an admin ban this player from CT, you want a Terror swapped to CT as new guard or an instant roundend?

**Comment by mrkos9i4ok** [comment]
instant roundend

**Comment by mrkos9i4ok** [comment]
swapped to CT as new guard and an instant roundend

**Comment by shanapu** [comment]
I made my thoughts, it's more meaningful when this should be added to the CTbans plugin. 
I going to close this.
