### ISSUE TITLE
Timer_ForceTSide

### ISSUE THREAD

**Issue by Caaine** [shanapu/MyJailbreak#212]
L 05/26/2017 - 23:42:34: [SM] Exception reported: Handle 6710a8f is invalid (error 1)
L 05/26/2017 - 23:42:34: [SM] Blaming: ctbans.smx
L 05/26/2017 - 23:42:34: [SM] Call stack trace:
L 05/26/2017 - 23:42:34: [SM]   [0] CloseHandle
L 05/26/2017 - 23:42:34: [SM]   [1] Line 500, ctbans.sp::Event_PlayerSpawn
L 05/26/2017 - 23:42:34: [SM]   [3] ChangeClientTeam
L 05/26/2017 - 23:42:34: [SM]   [4] Line 1002, ratio.sp::Timer_ForceTSide

https://github.com/oaaron99/CTBans/issues/6

**Comment by oaaron99** [comment]
I already fixed this, you have to update the plugin

**Comment by Caaine** [comment]
its the new Version

**Comment by Caaine** [comment]
L 06/05/2017 - 13:46:04: [SM] Exception reported: Handle 690b0914 is invalid (error 1)
L 06/05/2017 - 13:46:04: [SM] Blaming: ctbans.smx
L 06/05/2017 - 13:46:04: [SM] Call stack trace:
L 06/05/2017 - 13:46:04: [SM]   [0] CloseHandle
L 06/05/2017 - 13:46:04: [SM]   [1] Line 500, ctbans.sp::Event_PlayerSpawn
L 06/05/2017 - 13:46:04: [SM]   [3] ChangeClientTeam
L 06/05/2017 - 13:46:04: [SM]   [4] Line 1003, ratio.sp::Timer_ForceTSide

**Comment by shanapu** [comment]
This belongs to ctbans. if you still got the error please make issue at ctbans repo
