### ISSUE TITLE
Ratio: support for Levels Ranks

### ISSUE THREAD

**Issue by mrkos9i4ok** [shanapu/MyJailbreak#213]
Pls add support 
levels-ranks statistic

**Comment by shanapu** [comment]
can you send me a working download link without registration?
Or the include file (.inc) ?

**Comment by mrkos9i4ok** [comment]
https://drive.google.com/open?id=0B1FT9wO-Nia_bXQwaTBtMVM5alk

**Comment by shanapu** [comment]
so we will block join guard/warden when player rank less than rank xx, right? (xx = cvar)

**Comment by mrkos9i4ok** [comment]
It seems to me better to do, that someone has a higher rank, that one is in the queue before or his first choice in a random move, than others.

**Comment by shanapu** [comment]
A priority adjustment on the queue is not implemented in API & is not planned for the future. 
I made an support plugin working like all other. Restrict join CT/warden when not at leats on level xx.
I hope it fit your needs.

**Comment by mrkos9i4ok** [comment]
I do not quite understand what needs to be written into the cvar.
I use "lr_type_statistics" "1", which gives the rank according to the time that the player spent on the server.
I need to enter the rank that it receives. Or its time.

**Comment by shanapu** [comment]
I used 
```
+ * Получает ранг клиента
 + * 
 + * @param iClient		Индекс клиента.
 + * @return int			Ранг клиента
 + */
 +native int LR_GetClientRank(int iClient);
```
For check. So

 if LR_GetClientRank < sm_ratio_lvlranks restict join.

example: 
shanapu has rank 50
sm_ratio_lvlranks is 40
shanapu can't join CT

shanapu has rank 20
sm_ratio_lvlranks is 40
shanapu can join CT

**Comment by mrkos9i4ok** [comment]
`example:
shanapu has rank 50
sm_ratio_lvlranks is 40
shanapu can't join CT

shanapu has rank 20
sm_ratio_lvlranks is 40
shanapu can join CT`
It seems to me the opposite))

Ну я понял.Это какое звание.Он использует стандартные(Сильвер-1,сильвер-2 и т.п.).От 1 до 18 только.

**Comment by shanapu** [comment]
so, does it works for you, with ranks 1-18? I don't have this plugin so I can't test it for myself.

**Comment by mrkos9i4ok** [comment]
It seems so, until errors are seen!

**Comment by shanapu** [comment]
https://forums.alliedmods.net/showthread.php?t=299311

There is a new version 2.3.1 of level ranks and the API differs complete. 
Right now I don't see a way on new API to get players level.
I remove MyJBs support plugin from repo until it's uptodate.

**Comment by shanapu** [comment]
won't support this since it's unapproved on AM.
Closed
