### ISSUE TITLE
ArmsRace cause random client crashes.

### ISSUE THREAD

**Issue by Hexer10** [shanapu/MyJailbreak#220]
It explains it self, sometimes It crashes, sometimes not, and not to all clients.
I use latest sm, & myjb version.
I think you'll need more infos so tell me

**Comment by shanapu** [comment]
When do the clients crash? 
round_start, get a new weapon, get killed, get respawn, round_end?
I assume there is no error in any logs?
Do the clients get any error? As win window or in client console?

Does anyone else get this issue?

**Comment by Hexer10** [comment]
Sorry for late reply, It still crashing without armsrace.smx but when I start that event it makes more "probably" the client crash
I think i'll go deeper myself.
