### ISSUE TITLE
Night crawler Event day IDEA!

### ISSUE THREAD

**Issue by devu4** [shanapu/MyJailbreak#221]
Would be nice if you could add this event day.

- All Ts get m4a1-S at start of the round
- All CTs become invisible to Ts, have only knifes, small increase in speed and no footsteps.
- CTs can also climb walls by aiming and pressing E. (Like in CS 1.6) ** don't know if it is possible in CS:GO.
- CTs must kill the Ts before being killed themselves. Last remaining T gets LR.

Would be a cool addition!

****Based on night crawler servers in CS 1.6

**Comment by shanapu** [comment]
I done this time ago but was not happy with the balancing (there is no balance - NC is OP) & handling you can test/use it if you like. but won't be a part of myjb.
https://gist.github.com/shanapu/69aa1f3dc2eaf2379259be62da036228
Right now I stop developing new events and concentrate to an RC.
