### ISSUE TITLE
RoundTime 

### ISSUE THREAD

**Issue by fkMain** [shanapu/MyJailbreak#223]
Hello, where can i change roundtime cvar? Because by default roundtime set to 60seconds,i think.I tried change it in gamemodes,server.cfg ,but nothing.Thank you

**Comment by shanapu** [comment]
you set the roundtime with 'mp_roundtime' in you gamemodes_xxx.cfg.
Seems there is a bug with freeday on first round. try set sm_freeday_firstround '0' in cfg/myjailbreaks/events/freeday.cfg

and please take a look [here](https://github.com/shanapu/MyJailbreak/wiki/Frequently-Asked-Questions#what-should-i-consider-if-i-open-a-issue-or-post-on-forum), some more infos like version number would be cool...

**Comment by fkMain** [comment]
Already set mp_roundtime 8 mp_roundtime_hostage 8 mp_roundtime_defuse 8 at server.cfg and gamemeodes_xx.cfg | and  sm_freeday_firstround '0' at freeday.cfg too

Plugins list:
  01 "[TG] ReloadBattle" (0.5) by Raska
  02 "Knife choice INTERFASE MONUL - Выбор ножа МОДУЛЬ ИНТЕРФЕЙСА" (1.1) by Phoenix - Феникс
  03 "[Личный Кабинет] Core [PRIVATE]" (3.1.7) by 1mpulse (skype:potapovdima1)
  04 "[VIP] Dissolve Body" (1.2.1) by KOROVKA, R1KO
  05 "Реклама" (1.4) by Pheonix (‰7Феникс7‰)
  06 "Map Nominations" (1.8.0.6014) by AlliedModders LLC
  07 "[VIP] No Self Damage" (1.0.0) by R1KO (skype: vova.andrienko1)
  08 "[VIP] Heavy Armor" (1.0.0) by R1KO (skype: vova.andrienko1)
  09 "[VIP] Endurance" (1.0.0) by R1KO (skype: vova.andrienko1)
  10 "[VIP] Fire Damage" (1.0.0) by R1KO & AlmazON
  11 "[VIP] MULTI JUMP" (1.0) by Pheonix (‰7Феникс7‰)
  12 "[VIP] HP" (1.1) by R1KO (skype: vova.andrienko1)
  13 "[VIP] COIN" (1.1.0) by Pheonix (‰7Феникс7‰) & R1KO
  14 "[VIP] No Fall Damage" (1.0.0) by R1KO (skype: vova.andrienko1)
  15 "[VIP] Test" (1.0.3) by R1KO (skype: vova.andrienko1)
  16 "[VIP] Vampirism" (1.0.2) by R1KO
  17 "[VIP] Tag" (1.0.0) by R1KO
  18 "[VIP] Admin Privileges" (1.0.2) by R1KO (skype: vova.andrienko1)
  19 "[VIP] Keys " (1.0.5) by R1KO (skype: vova.andrienko1)
  20 "[VIP] Top Icon" (1.1) by R1KO
  21 "[VIP] Healthshot" (1.0.1) by R1KO (skype: vova.andrienko1)
  22 "[VIP] Armor" (1.0.1) by R1KO (skype: vova.andrienko1)
  23 "[VIP] Regen Armor" (1.0.4) by R1KO
  24 "[VIP] Language" (1.1) by R1KO
  25 "[VIP] Nade Models (CS:GO)" (1.0.0) by R1KO
  26 "[VIP] Tagrenade" (1.1) by R1KO (skype: vova.andrienko1)
  27 "[VIP] Electro Effects" (1.0.3) by R1KO
  28 "[VIP] Water Effect (CS:GO)" (1.0.0) by R1KO
  29 "[VIP] CHAT (cp)" (3.2) by R1KO
  30 "[VIP] Colored Flash" (1.0) by Franc1sco franug & iDragon & Smoke
  31 "[VIP] Gravity" (1.0.0) by R1KO (skype: vova.andrienko1)
  32 "[VIP] Spawn Effects" (1.2) by Mr.ToNik
  33 "[VIP] Core" (2.1.1 R) by R1KO (skype: vova.andrienko1)
  34 "[VIP] Regen HP" (1.0.4) by R1KO
  35 "[VIP] Skins" (2.0) by R1KO (skype: vova.andrienko1)
  36 "[VIP] Speed" (1.0.0) by R1KO (skype: vova.andrienko1)
  37 "Weapon Skin" (2.3.5PRE REV 3 PRIVATE) by Phoenix (‰7Феникс7‰)
  38 "Admin File Reader" (1.8.0.6014) by AlliedModders LLC
  39 "Rock The Vote" (1.8.0.6014) by AlliedModders LLC
  40 "Dynamic" (0.0.26) by Neuro Toxin
  41 "VoiceAnnounceEx" (2.1.2) by Franc1sco franug, Mini and GoD-Tony
  42 "[TG] TaserMania" (0.3) by Raska
  43 "menu_fd.smx"
  44 "Disable HUD money" (1.0) by Pheonix (‰7Феникс7‰)
  45 "MyJailShop" (1.3.1-67881c9) by shanapu
  46 "Reset Score" (1.0.3) by GoDtm666 (www.MyArena.ru)
  47 "[LK MODULE] Перевод Денег" (2.1) by 1mpulse (skype:potapovdima1)
  48 "SM SKINCHOOSER" (4.8) by Andi67
  49 "IP Name & Say Block" (2.0) by R1KO
  50 "Chat-Processor" (2.0.8) by Keith Warren (Drixevel)
  51 "Disable Radar" (1.2) by Internet Bully
  52 "Knife choice CORE - Выбор ножа ЯДРО" (2.4.1) by Phoenix - Феникс
  53 "[TG] DrunkenRambo" (0.9) by Raska
  54 "[LK MODULE] Покупка VIP (VIP R1KO)" (2.2) by 1mpulse (skype:potapovdima1)
  55 "Last Request: Hp Fight" (1.3) by EGood
  56 "Flashlight" (1.3.63) by Mitch
  57 "AFK Ping Control" (1.3) by wS (World-Source.Ru)
  58 "MapChooser" (1.8.0.6014) by AlliedModders LLC
  59 "[LK MODULE] Админ Меню" (2.0) by 1mpulse (skype:potapovdima1)
  60 "[LK MODULE] Покупка SHOP кредитов" (2.1) by 1mpulse (skype:potapovdima1)
  61 "[TG] HEGrenades" (0.8) by Raska
  62 "JailBreak Pahan(MyJailBreakWarden)" (1.0.8) by SN(Kaneki)
  63 "SourceBans: Admin Config Loader" ((SB++) 1.5.5-dev) by AlliedModders LLC, Sarabveer(VEER)
  64 "[TG] ChickenRoulette" (0.1) by Raska
  65 "TeamGames" (1.0.0.0) by Raska
  66 "[LK MODULE] Управление доступом (VIP R1KO)" (2.1) by 1mpulse (skype:potapovdima1)
  67 "Client Preferences" (1.8.0.6014) by AlliedModders LLC
  68 "[Source 2013] Custom Chat Colors" (3.1.0 CP) by Dr. McKay, Fixed up by Keith Warren (Drixevel)
  69 "[TG] BombToss" (0.8) by Raska
  7  71 "[TG] WildWest" (0.4) by Raska
  72 "Basic Comm Control" (1.8.0.6014) by AlliedModders LLC
  73 "[TG] MoreMarks" (0.2) by Raska
  74 "[VIP] PLAYER COLOR" (1.0.0) by Drimer
  75 "Basic Commands" (1.8.0.6014) by AlliedModders LLC
  76 "[Shop] Coins" (1.1.0) by White Wolf (HLModders LLC)
  77 "[Shop] Aura" (1.2) by R1KO
  78 "Basic Chat" (1.8.0.6014) by AlliedModders LLC
  79 "[TG] NoZoom" (0.5) by Raska
  80 "[ANY] Blank Credits System" (1.1.9.1) by Headline
  81 "[TG] ChickenHunt" (0.3) by Raska
  82 "MyJailShop - Use credits from Shop by FrozDark" (1.0) by shanapu
  83 "[TG] Warden" (0.6) by Raska
  84 "Test Messages" (1.0.0) by Keith Warren (Drixevel)
  85 "[LK MODULE] Info Menu" (2.1) by 1mpulse (skype:potapovdima1)
  86 "CT Bans" (1.5) by Addicted
  87 "SourceComms" ((SB++) 1.5.4.6) by Alex, Sarabveer(VEER)
  88 "Basic Votes" (1.8.0.6014) by AlliedModders LLC
  89 "Anti-Flood" (1.8.0.6014) by AlliedModders LLC
  90 "[TG] HeadShotOnly" (0.6) by Raska
  91 "Блокирование sm plugins" (1.1) by Pheonix (‰7Феникс7‰)
  92 "Token Auto Updater" (1.3.1) by ‰7Феникс7‰
  93 "SM_Hosties v2" (2.2.3) by databomb & dataviruset & comando
  94 "Basic Info Triggers" (1.8.0.6014) by AlliedModders LLC
  95 "MySteamID" by NoMore
  96 "Show Damage" by SenatoR
  97 "SM Configurable Arms/Gloves Menu" (1.0.1) by Franc1sco franug
  98 "Sound Commands" (1.8.0.6014) by AlliedModders LLC
  99 "Admin Help" (1.8.0.6014) by AlliedModders LLC
  100 "[Shop] Trails CS:GO" (1.1) by FrozDark (HLModders LLC), Pheonix (‰7Феникс7‰)
  101 "MyJailbreak - HE Battle" (Beta 12.0.dev-426afd2) by shanapu
  102 "MyJailbreak - Weapons" (Beta 12.0.dev-426afd2) by shanapu
  103 "MyJailbreak - Drunk" (Beta 12.0.dev-426afd2) by shanapu
  104 "MyJailbreak - Catch & Freeze" (Beta 12.0.dev-426afd2) by shanapu
  105 "MyJailbreak - HideInTheDark" (Beta 12.0.dev-426afd2) by shanapu
  106 "MyJailbreak - Teleport War" (Beta 12.0.dev-426afd2) by shanapu
  107 "MyJailbreak - Arms Race" (Beta 12.0.dev-426afd2) by shanapu
  108 "MyJailbreak - Icons" (Beta 12.0.dev-426afd2) by shanapu
  109 "MyJailbreak - KnifeFight" (Beta 12.0.dev-426afd2) by shanapu
  110 "MyJailbreak - Suicide Bomber" (Beta 12.0.dev-426afd2) by shanapu
  111 "MyJailbreak - Ghosts War" (Beta 12.0.dev-426afd2) by shanapu
  112 "MyJailbreak - Torch Relay" (Beta 12.0.dev-426afd2) by shanapu
  113 "MyJailbreak - Freeday" (Beta 12.0.dev-426afd2) by shanapu
  114 "MyJailbreak - Player HUD" (Beta 12.0.dev-426afd2) by shanapu
  115 "MyJailbreak - Ratio - CT Bans Support" (Beta 12.0.dev-426afd2) by shanapu, Addicted, good_live
  116 "MyJailbreak - Zeus" (Beta 12.0.dev-426afd2) by shanapu
  117 "MyJailbreak - Zombie" (Beta 12.0.dev-426afd2) by shanapu
  118 "MyJailbreak - Ratio" (Beta 12.0.dev-426afd2) by shanapu, Addicted
  119 "MyJailbreak - DealDamage" (Beta 12.0.dev-426afd2) by shanapu
  120 "MyJailbreak - Request" (Beta 12.0.dev-426afd2) by shanapu
  121 "MyJailbreak - CowBoy" (Beta 12.0.dev-426afd2) by shanapu
  122 "MyJailbreak - Warden" (Beta 12.0.dev-426afd2) by shanapu
  123 "MyJailbreak - Last Guard Rule" (Beta 12.0.dev-426afd2) by shanapu
  124 "MyJailbreak - War" (Beta 12.0.dev-426afd2) by shanapu
  125 "MyJailbreak - Core" (Beta 12.0.dev-426afd2) by shanapu
  126 "MyJailbreak - War FFA" (Beta 12.0.dev-426afd2) by shanapu
  127 "MyJailbreak - NoScope" (Beta 12.0.dev-426afd2) by shanapu
  128 "MyJailbreak - Menus" (Beta 12.0.dev-426afd2) by shanapu
  129 "MyJailbreak - DuckHunt" (Beta 12.0.dev-426afd2) by shanapu
  130 "[CS:GO/CS:S] Jailbreak Gangs" (1.1.9.1) by Headline
  131 "[TG] CocktailParty" (0.4) by Raska
  132 "[TG] PistolZoomBattle" (0.3) by Raska
  133 "RoundEndSound" (1.1.2) by GoDtm666 (www.MyArena.ru)
  134 "[TG] OneInTheChamber" (0.1) by Raska
  135 "[TG] HotPotato" (0.6) by Raska
  136 "[TG] KnifeFight" (0.7) by Raska
  137 "Player Commands" (1.8.0.5928) by AlliedModders LLC
  138 "Players Votes (+ VIP)" (1.5.0) by The Resident, pZv!
  139 "[TG] Machines + 500 HP" (0.4) by Raska
0 "Reserved Slots" (1.8.0.6014) by AlliedModders LLC
  71 "[TG] WildWest" (0.4) by Raska
  72 "Basic Comm Control" (1.8.0.6014) by AlliedModders LLC
  73 "[TG] MoreMarks" (0.2) by Raska
  74 "[VIP] PLAYER COLOR" (1.0.0) by Drimer
  75 "Basic Commands" (1.8.0.6014) by AlliedModders LLC
  76 "[Shop] Coins" (1.1.0) by White Wolf (HLModders LLC)
  77 "[Shop] Aura" (1.2) by R1KO
  78 "Basic Chat" (1.8.0.6014) by AlliedModders LLC
  79 "[TG] NoZoom" (0.5) by Raska
  80 "[ANY] Blank Credits System" (1.1.9.1) by Headline
  81 "[TG] ChickenHunt" (0.3) by Raska
  82 "MyJailShop - Use credits from Shop by FrozDark" (1.0) by shanapu
  83 "[TG] Warden" (0.6) by Raska
  84 "Test Messages" (1.0.0) by Keith Warren (Drixevel)
  85 "[LK MODULE] Info Menu" (2.1) by 1mpulse (skype:potapovdima1)
  86 "CT Bans" (1.5) by Addicted
  87 "SourceComms" ((SB++) 1.5.4.6) by Alex, Sarabveer(VEER)
  88 "Basic Votes" (1.8.0.6014) by AlliedModders LLC
  89 "Anti-Flood" (1.8.0.6014) by AlliedModders LLC
  90 "[TG] HeadShotOnly" (0.6) by Raska
  91 "Блокирование sm plugins" (1.1) by Pheonix (‰7Феникс7‰)
  92 "Token Auto Updater" (1.3.1) by ‰7Феникс7‰
  93 "SM_Hosties v2" (2.2.3) by databomb & dataviruset & comando
  94 "Basic Info Triggers" (1.8.0.6014) by AlliedModders LLC
  95 "MySteamID" by NoMore
  96 "Show Damage" by SenatoR
  97 "SM Configurable Arms/Gloves Menu" (1.0.1) by Franc1sco franug
  98 "Sound Commands" (1.8.0.6014) by AlliedModders LLC
  99 "Admin Help" (1.8.0.6014) by AlliedModders LLC
  100 "[Shop] Trails CS:GO" (1.1) by FrozDark (HLModders LLC), Pheonix (‰7Феникс7‰)
  101 "MyJailbreak - HE Battle" (Beta 12.0.dev-426afd2) by shanapu
  102 "MyJailbreak - Weapons" (Beta 12.0.dev-426afd2) by shanapu
  103 "MyJailbreak - Drunk" (Beta 12.0.dev-426afd2) by shanapu
  104 "MyJailbreak - Catch & Freeze" (Beta 12.0.dev-426afd2) by shanapu
  105 "MyJailbreak - HideInTheDark" (Beta 12.0.dev-426afd2) by shanapu
  106 "MyJailbreak - Teleport War" (Beta 12.0.dev-426afd2) by shanapu
  107 "MyJailbreak - Arms Race" (Beta 12.0.dev-426afd2) by shanapu
  108 "MyJailbreak - Icons" (Beta 12.0.dev-426afd2) by shanapu
  109 "MyJailbreak - KnifeFight" (Beta 12.0.dev-426afd2) by shanapu
  110 "MyJailbreak - Suicide Bomber" (Beta 12.0.dev-426afd2) by shanapu
  111 "MyJailbreak - Ghosts War" (Beta 12.0.dev-426afd2) by shanapu
  112 "MyJailbreak - Torch Relay" (Beta 12.0.dev-426afd2) by shanapu
  113 "MyJailbreak - Freeday" (Beta 12.0.dev-426afd2) by shanapu
  114 "MyJailbreak - Player HUD" (Beta 12.0.dev-426afd2) by shanapu
  115 "MyJailbreak - Ratio - CT Bans Support" (Beta 12.0.dev-426afd2) by shanapu, Addicted, good_live
  116 "MyJailbreak - Zeus" (Beta 12.0.dev-426afd2) by shanapu
  117 "MyJailbreak - Zombie" (Beta 12.0.dev-426afd2) by shanapu
  118 "MyJailbreak - Ratio" (Beta 12.0.dev-426afd2) by shanapu, Addicted
  119 "MyJailbreak - DealDamage" (Beta 12.0.dev-426afd2) by shanapu
  120 "MyJailbreak - Request" (Beta 12.0.dev-426afd2) by shanapu
  121 "MyJailbreak - CowBoy" (Beta 12.0.dev-426afd2) by shanapu
  122 "MyJailbreak - Warden" (Beta 12.0.dev-426afd2) by shanapu
  123 "MyJailbreak - Last Guard Rule" (Beta 12.0.dev-426afd2) by shanapu
  124 "MyJailbreak - War" (Beta 12.0.dev-426afd2) by shanapu
  125 "MyJailbreak - Core" (Beta 12.0.dev-426afd2) by shanapu
  126 "MyJailbreak - War FFA" (Beta 12.0.dev-426afd2) by shanapu
  127 "MyJailbreak - NoScope" (Beta 12.0.dev-426afd2) by shanapu
  128 "MyJailbreak - Menus" (Beta 12.0.dev-426afd2) by shanapu
  129 "MyJailbreak - DuckHunt" (Beta 12.0.dev-426afd2) by shanapu
  130 "[CS:GO/CS:S] Jailbreak Gangs" (1.1.9.1) by Headline
  131 "[TG] CocktailParty" (0.4) by Raska
  132 "[TG] PistolZoomBattle" (0.3) by Raska
  133 "RoundEndSound" (1.1.2) by GoDtm666 (www.MyArena.ru)
  134 "[TG] OneInTheChamber" (0.1) by Raska
  135 "[TG] HotPotato" (0.6) by Raska
  136 "[TG] KnifeFight" (0.7) by Raska
  137 "Player Commands" (1.8.0.5928) by AlliedModders LLC
  138 "Players Votes (+ VIP)" (1.5.0) by The Resident, pZv!
  139 "[TG] Machines + 500 HP" (0.4  140 "SourceBans++ TR" (1.5.4.6) by SourceBans Development Team, Sarabveer(VEER), NoTiCE
  141 "Nextmap" (1.8.0.6013) by AlliedModders LLC
  142 "WebLync" (0.0.8) by Neuro Toxin
  143 "Custom Player Skins (Core)" (1.4) by Mitchell, Root
  144 "[TG] GunFight" (0.4) by Raska
  145 "Web Shortcuts CS:GO version" (2.7) by Franc1sco franug and James "sslice" Gray
  146 "Smart Jail Doors" (0.5.2-beta) by Maxim 'Kailo' Telezhenko
  147 "WelcomeInfo.smx"
  148 "Admin Menu" (1.8.0.6014) by AlliedModders LLC
  149 "[Shop] Core" (3.0B:09-04-2017) by FrozDark (Fork by R1KO & White Wolf)
  150 "Thirdperson" (1.6 CS:GO edition) by shavit and Franc1sco franug
  151 "SourceBans Checker" ((SB++) 1.5.4.6) by psychonic, Ca$h Munny, Sarabveer(VEER)
  152 "Rotate server graphic banners" (0.3) by HiTmAnY
  153 "HUD Speclist" (1.1) by ZirionNeft (aka Midnight)
  154 "[LK MODULE] ТОП10 Донатеров" (2.1) 


meta listListing 8 plugins:
  [01] SourceMod (1.8.0.6014) by AlliedModders LLC
  [02] CS Tools (1.8.0.6014) by AlliedModders LLC
  [03] SDK Tools (1.8.0.6014) by AlliedModders LLC
  [04] SteamWorks Extension (1.2.1) by Kyle Sanderson
  [05] SDK Hooks (1.8.0.6014) by AlliedModders LLC
  [06] PTaH (P Tools and Hooks) (1.0.6) by Phoenix (‰7Феникс7‰)
  [07] DHooks (2.1.1) by Dr!fter
  [08] TAU LIB (1.2) by Phoenix (‰7Феникс7‰)

[fd settings in txt.txt](https://github.com/shanapu/MyJailbreak/files/1117777/fd.settings.in.txt.txt)

**Comment by fkMain** [comment]
And 
[gamemode_casual_server in txt.txt](https://github.com/shanapu/MyJailbreak/files/1117784/gamemode_casual_server.in.txt.txt)

**Comment by shanapu** [comment]
To limit this issue to a plugin. 
please move freeday.smx to disabled folder.

**Comment by fkMain** [comment]
Yes,u were right.I'm deleted freeday.smx and this issue has been solved
