### ISSUE TITLE
Start Eventday in current running round

### ISSUE THREAD

**Issue by Stonedestroyer** [shanapu/MyJailbreak#228]
Is it possible event days can be executed same round? As I feel that would be better on some servers so warden has control over the current round and not the next one. 

Also make it possible for there to be warden during event days like freeday?

**Comment by Hexer10** [comment]
Stonedestroyer:
> Is it possible event days can be executed same round? As I feel that would be better on some servers so warden has control over the current round and not the next one.

You mean, like when is FFA i can set the next round Ghost Wars?

>Also make it possible for there to be warden during event days like freeday?
As far as I know in freeday is already enabled the warden (idk since I don't use that), anyway for other events you just need to:
Find this block:
`
	if (gp_bWarden)
	{
		SetCvar("sm_warden_enable", 0);
	}`
and removeit.

**Comment by shanapu** [comment]
> Is it possible event days can be executed same round? As I feel that would be better on some servers so warden has control over the current round and not the next one.

With the current code construction, it is not possible to start an event for the current running round. I was asked that before. I will do this, but need a huge rewrite.

> Also make it possible for there to be warden during event days like freeday?

I will make a cvar so you can choose to enable warden on freeday. 
On all other eventdays, warden-features would be overpowered or gamebreaking.
I don't recommend to enable warden on other eventdays, like hexer10 explained.

**Please open one Issue on github per request/errors/problems. Split many requests/errors/problems to different Issues. Thanks!**

**Comment by shanapu** [comment]
> I will make a cvar so you can choose to enable warden on freeday.

done. https://github.com/shanapu/MyJailbreak/commit/3ed080ec714ab5fd6c6e97d9ed118b05b2428ac9

> With the current code construction, it is not possible to start an event for the current running round. I was asked that before. I will do this, but need a huge rewrite.

I had some ideas and a long night full of "coffie" and It seems doable. I like it and would invest the time to rewrite all events for this. Stay tuned
