### ISSUE TITLE
Icons |Call stack trace

### ISSUE THREAD

**Issue by fkMain** [shanapu/MyJailbreak#232]
Exception reported: Client index 3 is invalid
L 07/20/2017 - 21:11:17: [SM] Blaming: MyJailbreak/icons.smx
L 07/20/2017 - 21:11:17: [SM] Call stack trace:
L 07/20/2017 - 21:11:17: [SM]   [0] ThrowNativeError
L 07/20/2017 - 21:11:17: [SM]   [1] Line 649, addons/sourcemod/scripting/MyJailbreak/icons.sp::Native_BlockIcon
L 07/20/2017 - 21:11:17: [SM]   [3] MyIcons_BlockClientIcon
L 07/20/2017 - 21:11:17: [SM]   [4] Line 1843, addons/sourcemod/scripting/myjailshop.sp::ResetPlayer
L 07/20/2017 - 21:11:17: [SM]   [5] Line 840, addons/sourcemod/scripting/myjailshop.sp::TG_OnGamePrepare
L 07/20/2017 - 21:11:17: [SM]   [7] Call_Finish
L 07/20/2017 - 21:11:17: [SM]   [8] Line 1285, Api.sp::TG_StartGamePreparation
L 07/20/2017 - 21:11:17: [SM]   [9] Line 1131, Api.sp::GameStartMenu_Handler

Ver: MyJailbreak - Core (Beta 12.0-e46b793)
SourceMod (1.8.0.6015)

**Comment by shanapu** [comment]
https://forums.alliedmods.net/showpost.php?p=2536422&postcount=552

> This error comes from MyJail**Shop**. I pushed a fix to dev branch [of MyJailShop].
