### ISSUE TITLE
[Menu] Add forward & natives like myshop.

### ISSUE THREAD

**Issue by Hexer10** [shanapu/MyJailbreak#234]
Hi,
Would it possible to add them like this: https://github.com/shanapu/MyJailShop/commit/dbc1622e8523e446b7aaa9e2203a29518464181c.

**Comment by shanapu** [comment]
great idea! this will make custom menu items so easy. 
I have an additional idea how to make a menu_customs plugin with xtra cfg for easy add own menu item without need to edit source everytime...

**Comment by shanapu** [comment]
> I have an additional idea how to make a menu_customs plugin with xtra cfg for easy add own menu item without need to edit source everytime...

still in mind

**Comment by Hexer10** [comment]
It will be a menu like:

"SomeText"
{
"command" "kill"
}

Or what? What's your idea

**Comment by shanapu** [comment]
yeah and maybe somehing like:
`"role"  "1,2,3,4" // 1 = warden, 2 = deputy, 3 = guard, 4 = prisoner`
