### ISSUE TITLE
Add Global Cvars.

### ISSUE THREAD

**Issue by Hexer10** [shanapu/MyJailbreak#237]
I mean, I dont like the events in a row / that events starts in the same round when they are setted.
So if I'm using the myjailbreak.smx plugin will be created the convars like:
`sm_myjb_global_round_row 0 = Use events options 1 = Disable globaly `
`sm_myjb_global_start_event 0 = Use events options 1 = Enable globaly 2 = Disable globaly`

**Comment by Hexer10** [comment]
Maybe add this also for beacon time, round time...

**Comment by shanapu** [comment]
I think I understand. 
You want to set only these two instead crawling through all .cfgs and set every single cvar of every event. 
I know to edit a default cfg to according to your requirements, could be bad-ass work.
I usually use my editor (np++) & open all cfgs files & use "search&replace" for fast processing.

I don't think I will include this (yet), but perhaps you can persuade me...

**Comment by Hexer10** [comment]
I knew that would be "long" to do.
But how to you use notepad++ ti replace? 
like:
find
`sm_*_cvar "0"`
and replace with
`sm_*_cvar "1"`
I know how to find but not how to replace

**Comment by shanapu** [comment]
i don't search for the full cvar string. only the identical part. like
search:
`_begin_admin "1"` or `_cooldown_start "3"`
replace:
`_begin_admin "0"` or `_cooldown_start "0"`
so my searchterm just ignore the eventname.

**Comment by Hexer10** [comment]
Uh, nice anyway.
(Sorry for late reply)
