### ISSUE TITLE
Enable WallHack for LastCT / After enable beacon.

### ISSUE THREAD

**Issue by Hexer10** [shanapu/MyJailbreak#239]
The name exaplains itself, when a guard beacames lastct / when the beacons starts on eventsday enable the wh too.

**Comment by shanapu** [comment]
good idea. I will do that.

**Comment by shanapu** [comment]
I done the LastGuard wallhack.
A wallhack on beacon is bit different. 
The beacon is a module of myjailbreak.smx and the eventdays toggle these beacon with a native. 
in this way not every event day need his own bacon(code). For eventdays all bacons works the same way (red/blu).
But wallhack on catch/zombie/lastguard/... needs different paramenters(color,victims,...) which will be hard/impossible to build-in as variable in a native. 
Add wallhack code to every eventday would bloat the plugins.

I think about make a "standart" wallhack which in myjailbreak.smx as module like beacon and call them by native on plugins which doesn't have a own wallhack. 
I'm not sure this is a good way, or even this wallhack is necessary - in contrast to last guards wallhack....

**Comment by Hexer10** [comment]
> think about make a "standart" wallhack which in myjailbreak.smx as module like beacon and call them by native on plugins which doesn't have a own wallhack.
> I'm not sure this is a good way, or even this wallhack is necessary - in contrast to last guards wallhack....

Your chose, that isn't very necessary.

**Comment by shanapu** [comment]
I'm undecided. I/we had never problems to find each other after beacons on my test server. but when you as an server operator think it would be a really needed and cool feature. why not? give em a try!

**Comment by shanapu** [comment]
btw, the wallhack features of all plugins should be anyway rewritten.

Cause Mitchell notes this 'everywhere' about his CustomPlayerSkins.

> If you find this useful and want to use it in your plugin **you should pull the code for the skins themselves and use that other then using these natives.**

**Comment by shanapu** [comment]
For a possible wallhack rewrite or wallhack feature on beacon, we'll open a new issue, when it becomes necessary.

**Comment by Kxnrl** [comment]
why not use
``` c
SetEntPropFloat(target, Prop_Send, "m_flDetectedByEnemySensorTime", 99999.0);

**Comment by Bara20** [comment]
@Kxnrl Has that colors support?

**Comment by Kxnrl** [comment]
@Bara20 no, but low cpu usage. and it will not glow teammate. this effect like weapon_tagrenade. if players > 35 & 64tick , CPS will make sv > 20 (tested on 7700k)

**Comment by shanapu** [comment]
nice hint! doesn't know this before. 
will test this sometime when more time. Could replace cps in some places meaningfully.

**Comment by Kxnrl** [comment]
dont forget set
``` sourcepawn
SetEntPropFloat(target, Prop_Send, "m_flDetectedByEnemySensorTime", 0.0);
``` 
on player spawn or death. if u dont do that. will keep wallhack. the float value is GameTime. 
if not set to 0, when ur value > ```GetGameTime``` , wallhack will auto-remove

**Comment by Hexer10** [comment]
I think this would only usefull on the lastguard, since in the FFA this shoud be enable for teammates too (or this works for all with teammates enemy?)

**Comment by Kxnrl** [comment]
if mp_teammates_are_enemies 1 will wallhack with teammates
