### ISSUE TITLE
New Native - MyJailbreak_RemoveEventDayPlanned

### ISSUE THREAD

**Issue by Hexer10** [shanapu/MyJailbreak#240]
The title exaplains itself

**Comment by shanapu** [comment]
do I understand right? example:
"War" is planned for start next round. 
You unload "War" with 'sm unload MyJailbreak/war'
The issue: can't start other event. And war still appears in hud.
right?

I understand the issue if this is what you mean, but why should you unload a event when it is planned?

**Comment by Hexer10** [comment]
I want this for a old bug (i dont rember if was my fair [Probably yes]), but now I think would be "good" es:
I set ffa, then I dont what it but I want TPWar, I do ```sm_teleportwar``` and the previus planned event day would be removed. 
I'd like a native like: ```MyJailbreak_RemoveEventDayPlanned```
Now Idk if it's hard to-do

**Comment by shanapu** [comment]
when you say:

>  I want TPWar, I do `sm_teleportwar`

I assume you mean  sm_**set**teportwar, cause a vote (`sm_teleportwar`) started from a player would remove the planed event (set by admin?)

I understand the meaning of the function but still not how to use it. 
Should this be a part of MyJB core to reset an planned event or is this mean for an extern plugin?

I think reset an planned eventday by setting an new eventday would cause confustion.
I would do an new command for admins in myjailbreak.sp to reset a planned event day. this command calls a forward, like `MyJailbreak_RemoveEventDayPlanned`, so eventdays can listen to this forward an reset the eventday preparation.

would that meet your needs?

**Comment by Hexer10** [comment]
Yeah, sure.

**Comment by shanapu** [comment]
unfortunately, I lost my progress on this.    :/
Will start again when have a longer span of time for coding.

**Comment by shanapu** [comment]
finally done with ff9a21509d5eb61272369f4e4ca1e13c3d120b1e 

command `sm_reseteventday` in myjailbreak.sp trigger forward `MyJailbreak_ResetEventDay()` which end all planned or running eventdays.
