### ISSUE TITLE
RandomKill only players on view

### ISSUE THREAD

**Issue by Hexer10** [shanapu/MyJailbreak#241]
I ask this because sometimes it kill Ts rebels.

**Comment by shanapu** [comment]
There is a check to not kill a terror when he is recognized as rebel by hosties.
Not that beauty but should work.
But I assume you speaking about rebels not (yet) recognized by hosties. So yeah I will do this request, only kill the player on view. I don't think a cvars is needed to disable.

**Comment by shanapu** [comment]
not tested, but should work as indeed.

**Comment by shanapu** [comment]
errors & Script execution timed out...
need rewrite or temporary remove the IsClientInView check
