### ISSUE TITLE
Symbol "<" Breaks down HUD

### ISSUE THREAD

**Issue by mrkos9i4ok** [shanapu/MyJailbreak#243]
Symbol "<" breaks down HUD
Nick player: ™(>M<):M^E^T^O^R^S:™
HUD:
![image](https://user-images.githubusercontent.com/20227450/29171283-affd433c-7de4-11e7-9bd0-dcf45b38e301.png)

**Comment by mrkos9i4ok** [comment]
minifix :3
```
int warden = warden_get();
char name[25], name1[25];
GetClientName(Warden, name, 25);
for(int c = 0; c <= strlen(name); c++)
{
	if(name[c]=='<')
	{
	             name[c]=' ';
	}
}
if(strlen(name) > 24)
	name[24] = 0;
```

**Comment by mrkos9i4ok** [comment]
Also shortens the nickname if it is too long

**Comment by shanapu** [comment]
I will accomplish this with https://sm.alliedmods.net/new-api/string/ReplaceString

**Comment by shanapu** [comment]
also added "%" for warden & last guard which could also break the hud.

**Comment by mrkos9i4ok** [comment]
![image](https://user-images.githubusercontent.com/20227450/29194421-3115e030-7e32-11e7-8d29-9fd31d4f2967.png)
Nick: Fi<en%d
