### ISSUE TITLE
Marker don`t off

### ISSUE THREAD

**Issue by mrkos9i4ok** [shanapu/MyJailbreak#244]
If at the moment when the commander / deputy draws a marker they will be removed from their posts, then the marker will work all the time until they return again.

**Comment by shanapu** [comment]
hmmm... :/
just tested with warden only.
everytime a warden will be removed the markers will be removed too. 
On wardens death, on !uw or admin remove warden :/

sry can't reproduce.

**Comment by mrkos9i4ok** [comment]
Maybe only deputy
Player draws with a marker (he was deputy) and start LR
Deputy is removed,but marker don't off
