### ISSUE TITLE
Cowboy day bug

### ISSUE THREAD

**Issue by bchewy** [shanapu/MyJailbreak#25]
How does it affect players?: So for some event days I.E cowboy if the players spawn without weapons what I thought was we just had to restart the round or slay them all, cause we couldn't fix the thing or kill anyone

How does it affect game-play?: The round gets restarted and the game plays normal but for the rest of the map we're stuck on that event day, I.E if we do cowboy day, and we restart or slay all the next day is also cowboy day, till the map ends

**Comment by shanapu** [comment]
Sounds like an error in Cowboy. Do you have something in Logs?

**Comment by bchewy** [comment]
Will look for the logs right now.

**Comment by bchewy** [comment]
Cowboy.cfg is at default, the problem is that once in a while cowboy day does not end because players don't spawn with the guns.

**Comment by shanapu** [comment]
> the problem is that once in a while cowboy day does not end because players don't spawn with the guns.

I hate it when i can't reproduce a problem :/

do you use this plugin? https://forums.alliedmods.net/showpost.php?p=2396257&postcount=25 
or any other plugin that strips weapon on roundstart/end?

> L 06/09/2016 - 10:11:34: [SM] Native "DispatchSpawn" reported: Entity 9254 (9254) is invalid
> L 06/09/2016 - 10:11:34: [SM] Displaying call stack trace for plugin "MyJailbreak/hide.smx":
> L 06/09/2016 - 10:11:34: [SM] [0] Line 173, MyJailbreak/hide.sp::OnMapStart() and
> 
> We didn't even try to play hide ^^

this error was also reported here https://forums.alliedmods.net/showpost.php?p=2425172&postcount=41 & here https://github.com/shanapu/MyJailbreak/issues/14
and i think this cause of the double useage of this code in two running plugins...

**Comment by bchewy** [comment]
I'll take a look, sorry for the late reply, i've been extremely busy with everything else :<

**Comment by shanapu** [comment]
no need to say sorry! 
I/We have **no deadline**, we do this as **hobby**, we do this **for free**. So **no time pressure**!
I have fortunately much time to work on MyJB. If this will change people have to wait ;D

**Comment by shanapu** [comment]
never heart about this again.... closed?
if still there reopen with more informations
