### ISSUE TITLE
CSS Branch testing

### ISSUE THREAD

**Issue by damian1231** [shanapu/MyJailbreak#256]
Hi Shanapu i have uploaded content to the /logs/ on the hosting with new errors and some screen shots from ingame.

Server is crashing when there is a CT and a T

**Comment by shanapu** [comment]
OK I will have a Look when i hot time. can you Link the logs here for me?

**Comment by damian1231** [comment]
www.N7Gaming.co.uk/fastdl/beta/logs

**Comment by shanapu** [comment]
as i told you twice. please move knife, duckhunt and Ratio to disable folder. To get rid of these errors.

**Comment by damian1231** [comment]
KenSken :  xD
[JB.Freeday] Freeday has ended.
[SM] This server is powered by SM_Hosties v2, enjoy!
[SM] Please follow the rules listed in !rules.
[MyJB.warden] There is no current Warden. Type !w to become the Warden!
[MyJB.requests] KenSken has refused the game!
MP3 initialized with no sound cache, this may cause janking. [ music\myjailbreak\refuse.mp3 ]
Failed to create decoder for MP3 [ music\myjailbreak\refuse.mp3 ]
MP3 initialized with no sound cache, this may cause janking. [ music\myjailbreak\refuse.mp3 ]
Failed to create decoder for MP3 [ music\myjailbreak\refuse.mp3 ]
*** Invalid sample rate (0) for sound 'music\myjailbreak\refuse.mp3'.

**Comment by damian1231** [comment]
then crash

**Comment by damian1231** [comment]
please refresh for updated logs with them plugins disabled my bad!

**Comment by damian1231** [comment]
The bug causing server crash is on !w command.

**Comment by shanapu** [comment]
the error logs tell me nothing. 
screenshots seem ok.
client console is useless.

install https://forums.alliedmods.net/showthread.php?t=277703 and provide crash report.

You should configure your server properly (sv_pure), also reupload the myp3 files.
When the mp3 error still exist please use an mp3 you know it is working on css for this to test.

**Comment by damian1231** [comment]
what should the sv pure be set too? as it was 2, but sprays could not be seen?

**Comment by damian1231** [comment]
I have installed the plugin linked it to my steam account ran it i thought it was ment to dump out into a console on crash but nothing,, is there a crash file it creates?

**Comment by damian1231** [comment]
is this branch getting worked on still ?

**Comment by shanapu** [comment]
As I said, in forum and IRC **more than 5 times**.  I don't have much time for it. So it may take a while.
**Be patience. Don't hurry me.**  

Also, as you know, I don't own CSS so I can't do testings for myself. **I completely rely on your reports.**
If I don't get any crash report or any usefull informations a can't do anything.
Further progress depends on your information. 

I'm willing to work on it, BUT without help of css people I can do a shit.

**Comment by damian1231** [comment]
i have crashed the server over 10 times and nothing reports there i have setup on another server with a dodgy rpg mod and it reports straight away... lol

this is all i get from this server log wise
http://n7gaming.co.uk/fastdl/beta/logs/

**Comment by shanapu** [comment]
Hmmm... what about the other plugins? events days, icons, lastguard, menu, weapons.   do they work as they should?

Maybe try this event logger, too. So we can see where/when the crash occurs.
https://forums.alliedmods.net/showthread.php?p=2031093

**Comment by damian1231** [comment]
i dont think we can triffer anything as we cant get a warden ?

**Comment by shanapu** [comment]
admins/VIPs can start event days, too.

e.g. https://github.com/shanapu/MyJailbreak/wiki/War

**Comment by damian1231** [comment]
No that option does not work either :/ do you accept BTC? donations

**Comment by damian1231** [comment]
i will send you the money to purchase CSS and test but atm only have BTC available lol

**Comment by shanapu** [comment]
I'm in contact with damian1231 
I got a copy of cs:s. So developing will go on.

`fatal error 184: cannot write to file: `
you have to create the folder MyJailbreak/disabled for yourself.

**Comment by damian1231** [comment]
hey mate, i have just tested the latest version and no - one can join the server, it instantly crashes there CSS, i have tested fresh install, SM MM joined worked
+Hostie mod worked
+MYJB crashing my CSS

try yourself
connect 151.236.33.9:27015;password locked

**Comment by shanapu** [comment]
You don't need to tell me this on Steam and here, one channel is enough...

**Comment by damian1231** [comment]
Hey Shanupu is there any progress?
I'd just like to add, using it on CentOS works with the edited sp files.
However on map change it crashes, there is a horrible noise coming that does not stop its like a repeat of the side menu popping up on a constant loop.

**Comment by shanapu** [comment]
sry, no progess, prevented by personal things.
I can't work on myjb all day.
you must be patience or do it yourself.

**Comment by damian1231** [comment]
I have patience i was just asking if there was anything in the pipe line, if not no issues, i can wait.

**Comment by shanapu** [comment]
I forked the css branch to his own repo. https://github.com/shanapu/MyJailbreak-CSS
The css branch in this repo will not develop & maintained anymore. It will be removed with next update -> merge dev to master.
It's too hard and brings up to much work to keep myjb compatible to csgo & css.
Please report css related issues in the new repo.
