### ISSUE TITLE
Randomize event days on !voteday

### ISSUE THREAD

**Issue by shanapu** [shanapu/MyJailbreak#258]
20:06 - Бафик: Hi, I have a suggestion for improvement. Do so that when the voting starts for game day, every time games change randomly in places in menu.
Because I have on the server prisoners **all the time choose games that are on the first page.**

**Comment by shanapu** [comment]
https://github.com/shanapu/MyJailbreak/commit/196c8467b5cc63a57b2145ece453a16f06c65644

there is a new `sorting-eventdays.ini` file in `sourcemod/configs` where you can sort the order of eventdays in menus. 
and a new cvar to shuffle the votingsmenu.
`sm_menu_shuffle", "1", "0 - use 'config/sorting-eventdays.ini' on event day voting / 1 - Shuffle EventDays on voting
`
not very well tested but should work.

**Comment by mrkos9i4ok** [comment]
Menu:
3:freeday
4:hide
5:catch
6:hebattle
All click 5 and start FFA...

**Comment by mrkos9i4ok** [comment]
in sort menu:
3)torch
4)war
5)ffa
6)zombie
7)hide
8)catch

**Comment by mrkos9i4ok** [comment]
Sorry :-3
All nice work

**Comment by mrkos9i4ok** [comment]
maybe add cvar which enable\disable "no game" in the first point

**Comment by shanapu** [comment]
Ok, will do.
