### ISSUE TITLE
[CSS] config files in cfg/MyJailBreak are not loaded when uppercase

### ISSUE THREAD

**Issue by damian1231** [shanapu/MyJailbreak#259]
# Problem
The config files do not load. When i try to load them manually i get this error
```
23:47:24 exec MyJailbreak/Warden.cfg
23:47:24 'MyJailbreak/Warden.cfg' not present; not executing.
```
The server also gets error for all config files on start up in the console. This happens on a CentOS7 server.

# How to reproduce
Create folder
```
cfg/Test
```
note the uppercase t

Create a file `test.cfg` inside, the content don't matter

Try to load it
```
exec Test/test.cfg
```

# Potential fix
Make file names all lowercase
```
myjailbreak/warden.cfg
```

**Comment by good-live** [comment]
Are you sure that this isn't caused by incorrect File/Folder permissions?

**Comment by damian1231** [comment]
yes.

**Comment by damian1231** [comment]
I did tell you many times the files were not executing many many times, its always been the same always. i have sent screenshots of it via steam ???
I had this issue on Ubuntu and CentOS also have someone else testing it right now

**Comment by damian1231** [comment]
which files need edited and i will happily do it ?

**Comment by shanapu** [comment]
Best, search for 
```
AutoExecConfig_SetFile
```

This is were the config file name and folder destination will be set.

**Comment by damian1231** [comment]
damian - Today at 4:21 PM
Does anyone know why Linux wont read the Capital letters on files? e.g  cstrike/cfg/Test/test.cfg wont work, but cstrike/cfg/test/test.cfg will
The script is pointed to the capital letter but claims its none existancing
IRCBOT - Today at 4:24 PM
<psychonic> The valve filesystem layer automatically lowercases everything on some engines
<psychonic> Including that one

So your friend did not test?

**Comment by shanapu** [comment]
> So your friend did not test?

I test, it. 
He setup the server, changed the csgo model to css model.
I joint server. 
typed !w -> no crash -> I left server.

**Comment by damian1231** [comment]
Impossible im saying as ino myself it does not work on Ubuntu, due to the files not being executed.

**Comment by shanapu** [comment]
I will ask him what he done.
Just try lowercase the files for yourself and report back.

Not sure if I can make this change on csgo main branches without breaking running servers.

**Comment by damian1231** [comment]
Hi Shanupu maybe he created a symlink, which im trying to setup now I have however changed it to lowercases, and tried to manually exec warden.cfg and it worked! but this needs manually executed as you can imagine as the script wants to find the uppercase

**Comment by shanapu** [comment]
Haven't you changed 
`
AutoExecConfig_SetFile
`? The plugin should now use the lowercase filenames.

**Comment by damian1231** [comment]
in which file do i edit this please? im not much of a coder but if you can point me in the right direction would be appericated

**Comment by damian1231** [comment]
Have tried everything it is not making a lowercase file i have edited every AutoExecConfig_SetFile

i have edited every sp file that had AutoExecConfig_SetFile

here is my edited files:
www.N7Gaming.co.uk/myjb

**Comment by shanapu** [comment]
eg.
`AutoExecConfig_SetFile("Catch", "myjailbreak/EventDays");`
should be
`AutoExecConfig_SetFile("catch", "myjailbreak/eventdays");`
in your special case.

**Comment by Hexer10** [comment]
Now I use CentOs but before when I had Ubuntu I didn't get any issues.

**Comment by damian1231** [comment]
Are you also testing CentOS? are you having the same issues here?

**Comment by damian1231** [comment]
@Hexer10 try with these files mate

www.N7Gaming.co.uk/myjb

**Comment by shanapu** [comment]
Since it looks like it's a css only problem & I closed this, I please you to keep all css related shit in CSS Branch testing issue #256
