### ISSUE TITLE
ZombieDay dont end

### ISSUE THREAD

**Issue by krysti500** [shanapu/MyJailbreak#26]
Hello i have problem if i start Zombie event this not end after kill all Terrorist in next round i have green screen and timer to unfreeze

**Comment by shanapu** [comment]
do you have something in error logs?

**Comment by krysti500** [comment]
No

**Comment by shanapu** [comment]
does it happen all zombie rounds or only sometimes?
if sometimes, what was the exact sequence?
I need some more informations to reproduce this bug

**Comment by shanapu** [comment]
never heart about this again.... closed?
if still there reopen with more informations
