### ISSUE TITLE
disable friendly fire for cts on wardens !ff

### ISSUE THREAD

**Issue by shanapu** [shanapu/MyJailbreak#261]
as the title says. Add a convar and hook client damage to disable friendly fire for cts on wardens !ff command.

edit link: https://forums.alliedmods.net/showpost.php?p=2558329&postcount=706

**Comment by Hexer10** [comment]
Maybe reset the FF after the round end?

**Comment by shanapu** [comment]
19:00 - TFZMistery: hello i have question about myjb, when is FriendlyFire enabled by warden. Round doesnt end after last prisoner dies
19:00 - TFZMistery: is it a bug or it can be disabled?

This is a bug with 'mp_teammates_are_enemies 1'.
We should add a check on playerdeath and check terror alive player count, and, where appropriate set  'mp_teammates_are_enemies 0' & force end the round.
