### ISSUE TITLE
Mute doesn't work

### ISSUE THREAD

**Issue by vadrozh** [shanapu/MyJailbreak#262]
This cvars doesn't work
> // 0 - disabled, 1 - temporary mutes all client when the warden speaks
> // -
> // Default: "1"
> // Minimum: "0.000000"
> // Maximum: "1.000000"
> sm_warden_talkover "1"
> 
> // 0 - disabled, 1 - temporary mutes all client when the deputy speaks
> // -
> // Default: "1"
> // Minimum: "0.000000"
> // Maximum: "1.000000"
> sm_warden_talkover_deputy "1"
> 
> // 0 - mute prisoner & guards on talkover, 1 - only mute prisoners on talkover
> // -
> // Default: "1"
> // Minimum: "0.000000"
> // Maximum: "1.000000"
> sm_warden_talkover_team "1"
> 
> // 0 - mute death & alive player on talkover, 1 - only mute alive player on talkover
> // -
> // Default: "0"
> // Minimum: "0.000000"
> // Maximum: "1.000000"
> sm_warden_talkover_dead "1"

last version of myjb, sourcebans

**Comment by shanapu** [comment]
Wardens talkover feature requires the voiceannounce_ex extension.

**Comment by shanapu** [comment]
I assume, this solved your issue?
I going to close this. You can answer here again when you got still problems. Don't forget to post your 'sm plugins list' output
