### ISSUE TITLE
Help with scripting - menu

### ISSUE THREAD

**Issue by Javierko** [shanapu/MyJailbreak#266]
Hi coders,

i am making on new menu and i need some help with scripting...

**[HERE IS THE PLUGIN](https://hastebin.com/iwijatexag.cs)**

And i dont know, how i can add into this plugin/menu this command:

`else if (GetClientTeam(client) == CS_TEAM_T) // HERE STARTS THE T MENU`

i will be happy if you answer me early, thanks :)

**Comment by Hexer10** [comment]
Check this out: https://hastebin.com/ufacajobas.cs
btw this is not regarding the myjailbreak, better make a post in alliedmodders scripting.

**Comment by Javierko** [comment]
And when i want warden menu, i will replace:

> if (GetClientTeam(client) == CS_TEAM_CT)

this into

> if (warden_iswarden(client)) 

this?

**Comment by shanapu** [comment]
yes you have to add the warden.inc include
`#include <warden>`

when you want to use other natives in future take a look the addition myjbwarden include.
https://github.com/shanapu/MyJailbreak/blob/dev/addons/sourcemod/scripting/include/warden.inc
https://github.com/shanapu/MyJailbreak/blob/dev/addons/sourcemod/scripting/include/myjbwarden.inc
