### ISSUE TITLE
HudText - need help, this is idea to future

### ISSUE THREAD

**Issue by Javierko** [shanapu/MyJailbreak#271]
Hello shanapu and others who reading this issue.

My friend came to me with idea to make "ShowSyncHudText" and inside this will be write something like this:

**Current warden is: Here will be display name of current warden**
and when warden will be death there will be:
**Warden is death! Guards must choose new warden**
and when warden will disconnect from game:
**Warden leave game! Guards must choose new warden**

I tried to make this but, idk how to get name of current warden..
```
#define PLUGIN_NAME           "Jailbreak Warden"
#define PLUGIN_AUTHOR         "Javierko"
#define PLUGIN_DESCRIPTION    "JB"
#define PLUGIN_VERSION        "1.3 (Beta)"
#define PLUGIN_URL            "github.com/Javierko"

#define LoopClients(%1) for(int %1 = 1; %1 <= MaxClients; %1++) 
  
#include <sourcemod>
#include <cstrike>
#include <sdktools>
#include <sdkhooks>
#include <clientprefs>                     
#include <scp>
#include <smlib>
#include <warden>
#include <mystocks>
#include <myjailbreak>
#include <hosties>
#include <lastrequest>

#pragma semicolon 1
#pragma newdecls required

static Handle HudText = null;

public Plugin myinfo =
{
	name = PLUGIN_NAME,
	author = PLUGIN_AUTHOR,
	description = PLUGIN_DESCRIPTION,
	version = PLUGIN_VERSION,
	url = PLUGIN_URL
};

public void OnPluginStart()
{ 
  HudText = CreateHudSynchronizer();
  
  GetClientName(warden, sWarden, sizeof(sWarden));
	ReplaceString(sWarden, sizeof(sWarden), "<", "", false);  
}

void SetHudTextParams(-1.0, -0.5, 14.0, 255, 255, 255, 255, 2, 0.0, 0.25, 0.25)
{
  int warden = -1;
	if(gp_bMyJBWarden)
	{
		warden = warden_get();
	}
  if (warden != -1)
	{
		GetClientName(warden, sWarden, sizeof(sWarden));
		ReplaceString(sWarden, sizeof(sWarden), "<", "", false);
	}
  LoopClients(i)
  {
    if (!IsFakeClient(i) && IsClientInGame(i))
    {
      ShowSyncHudText(i, HudText, "Current warden is %t", sWarden);
    } 
  }  
}
```

But this dont work...

I will be happy, if somebody tell me how i can make this name of warden client... thanks..
(Btw. in this code i have it, but its undefined and idk how to define it 👍 )

Javierko

**Comment by shanapu** [comment]
on a quick overview:
you have not declared `sWarden`.
you have not declared `gp_bMyJBWarden`
you use a %t for translation instead a %s for string `ShowSyncHudText(i, HudText, "Current warden is %t", sWarden);`
you should not use a macro for a loop `
#define LoopClients(%1) for(int %1 = 1; %1 <= MaxClients; %1++) `

This is like #266 **not related to MyJailbreak.** 
You must make a post in [alliedmodders scripting forum sections](https://forums.alliedmods.net/forumdisplay.php?f=107) in future.
