### ISSUE TITLE
Bug with mods - Deal damage | No scope battle

### ISSUE THREAD

**Issue by Javierko** [shanapu/MyJailbreak#274]
Hello, 

i am using your myjailbreak mods, and after installing new version (MyJB-dev-9f65486 from 31/12/17 - 04:02:56) there is some bugs..

**Deal damage mod**
After warden set deal damage mod, every is frozen, nobody can walk, and after some second (10 seconds) server crash.
**No scope battle**
After Terrorist team kill Counter-Terrorist team, nothing happend and admin must kill everybody to end round.

Sorry for bad english, if you want to more explain, just tell me.

Thanks.

**Comment by Hexer10** [comment]
About the deal damage idk We'll look in to it.
The noscope issue isn't a bug that happens since Noscope battle is an FFA.

**Comment by shanapu** [comment]
Please, in future, split such reports to multiple issues. One issue for one problem/bug/issue/idea or request. thx

I just played DealDamage yesterday night, with latest dev. No permanent freeze. No crash. 

Do you have any error or crash logs? if not - please install Accelerator and collect crash reports.

How do you started the event? As Admin, warden, voting?
What are your config for `sm_EVENTNAME_begin_admin, sm_EVENTNAME_begin_warden, sm_EVENTNAME_begin_vote, sm_EVENTNAME_begin_daysvote`?

Indeed NoScope is an FFA event. No teams.

**Comment by Javierko** [comment]
Yes sorry for that, but if "Indeed NoScope is an FFA event. No teams." why T players cant hit T players?

**Comment by Hexer10** [comment]
I'm using TG too, make sure that you've installed the module of myjb for tg

**Comment by shanapu** [comment]
and also check you are on latest TeamGames which is 1.1.0.7

**Comment by Javierko** [comment]
Okay i will check it, and still i have problem with DealDamage, everybody freeze and after some secs, server shut down.

**Comment by shanapu** [comment]
'bout dealdamage, no error logs, no [crash logs](https://forums.alliedmods.net/showthread.php?t=277703)?

**Comment by shanapu** [comment]
after almost one month without response I close this.
When you still got a problem, please check [FAQ](https://github.com/shanapu/MyJailbreak/wiki/Frequently-Asked-Questions) and if needed open a new issue with all needed informations.
