### ISSUE TITLE
Can't drop gun as CT

### ISSUE THREAD

**Issue by kaniches** [shanapu/MyJailbreak#282]
I have a problem in my server where CTs can't drop their guns. It says "You dropped your gun" in chat but the gun is not dropped. I have sm_warden_gunnodrop "0" and sm_warden_disarm_mode "3" in Warden.cfg.

**Comment by kaniches** [comment]
20:49:45 [SM] Listing 83 plugins:
           01 "Fun Commands" (1.8.0.6040) by AlliedModders LLC
           02 "Admin Menu" (1.8.0.6040) by AlliedModders LLC
           03 "[Shop] Money Distributor" (1.4.2) by FrozDark (HLModders LLC)
           04 "[Shop] Gravity" (1.4) by R1KO
           05 "In-game Help Menu" (0.3) by chundo
           06 "Map Cvar Automator" (1.0) by CaffeinePowered
           07 "Player Stacker" (1.0) by Blodia
           08 "AFK Manager" (4.2.2) by Rothgar
           09 "Basic Comm Control" (1.8.0.6040) by AlliedModders LLC
           10 "Advertisements" (2.0.2) by Tsunami
           11 "Fun Votes" (1.8.0.6040) by AlliedModders LLC
           12 "spawntools7" (0.9) by meng
           13 "Basic Commands" (1.8.0.6040) by AlliedModders LLC
           14 "Chat Processor - Simple Chat Processor Wrapper" (1.0.0) by Keith Warren (Drixevel)
           15 "Basic Ban Commands" (1.8.0.6040) by AlliedModders LLC
           16 "Player Commands" (1.8.0.6040) by AlliedModders LLC
           17 "TeamChange Unlimited" (1.2.2) by Sheepdude
           18 "Dissolve" (1.0.0.1) by L. Duke
           19 "Move Commands ( ResetScore, Switch, Spec )" (2.0.1) by Bara
           20 "[CSGO] Team Limit Bypass" (1.1) by Zephyrus
           21 "Player Respawn" (1.6) by Rogue
           22 "[CS:GO] Spritetrail fix" (1.0.1) by FrozDark
           23 "Force Timelimit" (1.1.203) by <eVa>Dog
           24 "Chat-Processor" (2.0.9) by Keith Warren (Drixevel)
           25 "[UMC] Map Commands" (3.4.6-dev) by Steell
           26 "[UMC] Player Limits" (3.4.6-dev) by Steell
           27 "[UMC] Vote Command" (3.4.6-dev) by Steell
           28 "[UMC] Ultimate Mapchooser Core" (3.4.6-dev) by Steell
           29 "[UMC] Nominations" (3.4.6-dev) by Steell
           30 "[UMC] Rock The Vote" (3.4.6-dev) by Steell
           31 "[UMC] Admin Menu" (3.4.6-dev) by Steell
           32 "[UMC] Time Limits" (3.4.6-dev) by Steell
           33 "[UMC] End of Map Vote Warnings" (3.4.6-dev) by Steell
           34 "[UMC] Echo Nextmap" (3.4.6-dev) by Steell
           35 "[UMC] Prefix Exclusion" (3.4.6-dev) by Steell
           36 "[UMC] End of Map Vote" (3.4.6-dev) by Steell
           37 "[UMC] Post-Played Exclusion" (3.4.6-dev) by Sazpaimon and Steell
           38 "[UMC] Player Count Monitor" (3.4.6-dev) by Steell
           39 "REGEX word filter" (1.2) by Twilight Suzuka
           40 "Basic Votes" (1.8.0.6040) by AlliedModders LLC
           41 "[Shop] Trails" (2.2.3) by FrozDark (HLModders LLC)
           42 "Basic Chat" (1.8.0.6040) by AlliedModders LLC
           43 "MyJailbreak - Last Guard Rule" (Beta 13.0-8ed3412) by shanapu
           44 "MyJailbreak - War" (Beta 13.0-8ed3412) by shanapu
           45 "MyJailbreak - Zeus" (Beta 13.0-8ed3412) by shanapu
           46 "MyJailbreak - Core" (Beta 13.0-8ed3412) by shanapu
           47 "MyJailbreak - Icons" (Beta 13.0-8ed3412) by shanapu
           48 "MyJailbreak - Menus" (Beta 13.0-8ed3412) by shanapu
           49 "MyJailbreak - Weapons" (Beta 13.0-8ed3412) by shanapu
           50 "MyJailbreak - Warden" (Beta 13.0-8ed3412) by shanapu
           51 "[Shop] Core" (2.0.21) by FrozDark
           52 "Admin File Reader" (1.8.0.6040) by AlliedModders LLC
           53 "Remove Ads" (1.3) by Zephyrus
           54 "hextags" (1.17) by Hexah
           55 "Sound Commands" (1.8.0.6040) by AlliedModders LLC
           56 "Reserved Slots" (1.8.0.6040) by AlliedModders LLC
           57 "[Shop] Skins" (2.0.22) by FrozDark
           58 "Dissolve" (1.0.0.2) by L. Duke
           59 "SM_Hosties v2" (2.1.3b) by databomb & dataviruset & comando
           60 "Basic Info Triggers" (1.8.0.6040) by AlliedModders LLC
           61 "Client Preferences" (1.8.0.6040) by AlliedModders LLC
           62 "Map configs" (1.3) by Berni
           63 "SM SKINCHOOSER" (4.9) by Andi67
           64 "Admin Help" (1.8.0.6040) by AlliedModders LLC
           65 "[Shop] Double Jump" (1.1) by R1KO
           66 "[Shop] Top10 Function" (2.0.1) by FrozDark
           67 "[CSS/CS:GO] AbNeR ResetScore" (1.5fix) by AbNeR_CSS
           68 "Anti-Flood" (1.8.0.6040) by AlliedModders LLC
           69 "RankMe" (3.0.3.Kento.27.2) by lok1, Scooby, Kento, pracc, Kxnrl, CrazyHackGUT
           70 "Game_Player_Equip Fix" (1.1.1) by Mitch
           71 "Lastrequest - Revivir" (1.0) by Black Star
           72 "CT Ban" (2.0.3) by databomb
           73 "SM Jail Teams" (1.0.3) by Elad Nava
           74 "End Round Stopper" (1.0) by black_star
           75 "Quake Sounds v3" (3.5.0) by Spartan_C001
           76 "Red Bull: CSGO" (1.0) by ghost
           77 "CSS Medic" (1.0) by tuty
           78 "Ladder Gravity Fixer" (1.0) by CoMaNdO
           79 "CT Noblock Trigger" (1.2) by Ghost
           80 "SM Franug Jail Awards" (1.2 public version) by Franc1sco steam: franug
           81 "Lastrequest - Predator" (1.2) by Black Star
           82 "Flashlight" (1.3.63) by Mitch
           83 "SM Jailed Reasons" (v1.0) by Franc1sco steam: franug

**Comment by shanapu** [comment]
as I told your friend on steam:
I don't see a known conflicting plugin, but I also don't know all of your plugins.
Things you can do:
1. Disable all plugins beside MyJB & the requirements. Reenable plugins one for one to see which plugin causes the issue.
2. Rename Warden.cfg to Warden_backup.cfg (or something else) - MyJB will generate a new one with default config. Check if problem still occurs

**Comment by shanapu** [comment]
any progress/news here?

**Comment by kaniches** [comment]
It was a plugin that made the interference.

**Comment by shanapu** [comment]
can you tell us which plugin as conflicting? 
Maybe when someone else will have same problem.
