### ISSUE TITLE
Can't choose any Mode.

### ISSUE THREAD

**Issue by SturmX** [shanapu/MyJailbreak#284]
When I type !admin and go to the MyJailbreak menu, I can't ready any of the menus because all I see are hieroglyphics.
https://imgur.com/a/qFMAm
When I press one of the numbers the menu disappears.
Do you know a solution?

**Comment by shanapu** [comment]
wow, that looks weird. 
what is your csgo client language?
what is your sourcemod server language? 
```
addons\sourcemod\configs\core.cfg
/**
* Language that multilingual enabled plugins and extensions will use to print messages.
* Only languages listed in languages.cfg are valid.
*
* The default value is "en"
*/
"ServerLang" "en"
```
if not default (en), try change back to en

**Comment by SturmX** [comment]
Both is english :/

**Comment by shanapu** [comment]
phew...
I have no idea what this is causing.
Could you post your servers OS / SM / MM / MyJB version?
Could you post your 'sm plugins list' servers console output?
Do I assume right that there is no related error in ../csgo/addons/sourcemod/logs ?!

Are all other menus 'clean'? only occurs on the !admin menu?

**Comment by shanapu** [comment]
4 month no reply.
I going to close this. 
If the error still occurs please open a new issue with the **detailed error description**.
