### ISSUE TITLE
Error when player join.

### ISSUE THREAD

**Issue by fede1132** [shanapu/MyJailbreak#286]
Hi,

I have an eror with MyJailbreak/sm_hosties, when player join, throw [this](https://pastebin.com/92CNHrvt) error.

Can anyone help me ?

**Comment by shanapu** [comment]
you don't need to open an issue here, make a post on steam community forum and at the same time contact me on steam.

next time just google the error... not a problem of myjb or hosties...
https://forums.alliedmods.net/showthread.php?t=303249
