### ISSUE TITLE
Sounds do not reproduce

### ISSUE THREAD

**Issue by d4d3boss** [shanapu/MyJailbreak#289]
I do not understand why, the sounds of myjailbreak are not played by csgo ... even simply doing the play command does not work

**Comment by shanapu** [comment]
hi, 
are the mp3 files on your pc downloaded?
check your csgo folder   `...\steam\steamapps\common\Counter-Strike Global Offensive\csgo\sound\music\MyJailbreak` on your pc.

if they are not there:
Check when you connecting on server that all nessesary files get downloaded. After connection open console and look for something like: Downloading http://YourFastDL.tld/csgo\sound\music\MyJailbreak\warden.mp3.bz2 Download finished!
If download failed. Try your FastDL URL in a Browser. Files should be downloadable.

**Comment by shanapu** [comment]
2 month no reply.
I going to close this. 
If the error still occurs please open a new issue with the **detailed error description**.
