### ISSUE TITLE
Mod bugs

### ISSUE THREAD

**Issue by Javierko** [shanapu/MyJailbreak#292]
Hello, on my test server i tested MyJB mods, and after test, these mods doesnt work, I tested: Catch, War, NoScope (in new dev fixed), Zombie, DealDamage.

In these mods are bugs:
- after start, nobody can move and shoot
- players can pick warden

If you want more info, tell me.

**Comment by Javierko** [comment]
Blind, fixed maybe..

**Comment by Javierko** [comment]
New update 71fc327 | MyJB-dev-71fc327, still after starting mod i cant move.

**Comment by shanapu** [comment]
you know, some EventDays has a 'freeze time' (can't move), a 'truce time' (can't shoot) and 'blind feature'...

Also, I can't reproduce your warden problem. For me on all days warden is disabled (also on freeday).
IIRC you used an own (edited) version of warden & other plugins last time I had to support you.

Please provide [some infos & follow the suport guidelines](https://github.com/shanapu/MyJailbreak/wiki/Frequently-Asked-Questions#what-should-i-consider-if-i-open-a-issue-or-post-on-forum) like everyone else:

only an extract:

- Use descriptive topic titles & descriptions. i have idea, need Help, Suggestion or don't work isn't helpful & pleasant.
- Try to explain your request with so many details as you can.
- USE PROPER ENGLISH!
- Expound every single step to reproduce your train of thought. We're all no clairvoyant or mindreaders.
- Explain like "I'm an idiot and never I played MyJailbreak before".
- Maybe take a screenshot or make a beautiful picture with paint.
- Provide so many infos as you can. Like your...
- ...sourcemod & metamod version
- ...MyJailbreak version
- ...**sm plugins list server console output**
- ...plugin configs (.cfg)
- ...error logs from .../csgo/addons/sourcemod/logs directory
- ...all other things that could help us helping you!

**Please open one Issue on github per request/errors/problems. Split many requests/errors/problems to different Issues. Thanks**

If you are not capable to do this, I going to ignore you!
