### ISSUE TITLE
Catch and other mods, doesnt work...

### ISSUE THREAD

**Issue by Javierko** [shanapu/MyJailbreak#293]
Hello,
on my test server i am testing all mods, but there is problem, any mod wont work...
When Warden (Simon) start it, nobody can move or use knife or gun. Only info panel is showed.
I am using default cfg´s generated by plugins.

Plugins on server -> https://hastebin.com/nafetowefi.coffeescript
Version of MyJB -> MyJB-dev-71fc327 (12/05/18 - 03:00:48)
Sourcemod version -> 1.8.0.6040
Metamod version -> 1.11.0-dev+1089
Error log -> https://hastebin.com/erebakilaq.cpp

**Comment by shanapu** [comment]
you are not on the required and only supported version of hosties.

`"SM_Hosties(v2.2) - Entity Version" (Entity) by databomb & Entity` - this is badly edited
use https://github.com/dataviruset/sm-hosties/

also `sm plugins` **in client console** is not the same as `sm plugins list` **in server console**.

**Comment by shanapu** [comment]
https://github.com/Sples1/sm-hosties-fixed/issues/1#issuecomment-388655896
