### ISSUE TITLE
Fire with weapon doesnt work? Why?

### ISSUE THREAD

**Issue by Javierko** [shanapu/MyJailbreak#295]
Hello,

I am using version lastest version of MyJB (MyJB-dev-71fc327), but there is problem in mods, i tested mod: Catch and Freeze; Zombie mod. In there mods after truce time nobody can use any gun, he cant shoot from gun, only inspect. After mod end (round end, or when everybody is dead or new round) players still cant use weapons, cant shoot (use left and right mouse button easily). 
I am adding video of it, ignore quality, its recorded on phone. https://www.youtube.com/watch?v=6xi2_9ZrReo

BTW. This is not caused by sm hosties, i had on server only myjb and requied plugins, still catch and freeze; zombie mod doesnt work... 🤙

**Comment by shanapu** [comment]
fixed in catch. 
can't reproduce in zombies.

please difference between "sm hosties" & "ENT hosties".
When recording a video, please switch to english language, so I can read chat and understand whatever happens.

**Comment by Javierko** [comment]
Okay i will test it, and i will test another mods.

**Comment by Javierko** [comment]
After test, every mod works good.

Thanks.
