### ISSUE TITLE
Ton of bugs to report

### ISSUE THREAD

**Issue by voidgaming09** [shanapu/MyJailbreak#300]
Here are the current bugs I have:

Dodgeball LR isn't working - the health changes to 1hp and doesn't give a flash

Gun toss - When both guns are thrown, it shows the distance, but doesn't alert who was the winner or give the winning person a gun to kill the enemy.

Player names - when you look at a player, their name doesn't appear in red text like other JB servers. Not sure if I need an additional setting/cvar?

Duckhunt LR - Whenever I start this LR, I get this in console:
CalcSequenceIndex: can't find 'idle_upper_gren'.
CalcSequenceIndex: can't find 'walk_upper_gren'.
CalcSequenceIndex: can't find 'run_upper_gren'.
CalcSequenceIndex: can't find 'crouch_idle_upper_gren'.
CalcSequenceIndex: can't find 'run_shoot_gren1'.
CalcSequenceIndex: can't find 'walk_shoot_gren1'.

Noscope LR - doesn't give you the gun (This appeared in console:  (Tried to look up command say as if it were a variable.)

Here are all my plugins, let me know if you need more information.

[SM] Listing 65 plugins:
```
01 "MyJailbreak - Ratio" (Beta 13.0-<COMMIT>) by shanapu, Addicted
02 "[CSGO] Team Limit Bypass" (1.1) by Zephyrus
03 "OVERWATCH:Chat" (1.0) by Potatoz
04 "MyJailbreak - KnifeFight" (Beta 13.0-<COMMIT>) by shanapu
05 "MyJailbreak - Catch & Freeze" (Beta 13.0-<COMMIT>) by shanapu
06 "SM_Hosties v2" (2.2.0) by databomb & dataviruset & comando
07 "MyJailbreak - HideInTheDark" (Beta 13.0-<COMMIT>) by shanapu
08 "Sound Commands" (1.8.0.6047) by AlliedModders LLC
09 "Chat-Processor" (2.1.4) by Keith Warren (Shaders Allen)
10 "Basic Info Triggers" (1.8.0.6047) by AlliedModders LLC
11 "Admin Help" (1.8.0.6047) by AlliedModders LLC
12 "gloves_hotfix.smx"
13 "Basic Chat" (1.8.0.6047) by AlliedModders LLC
14 "MyJailbreak - DuckHunt" (Beta 13.0-<COMMIT>) by shanapu
15 "Smart Jail Doors" (0.5.2-beta) by Maxim 'Kailo' Telezhenko
16 "Player Commands" (1.8.0.6047) by AlliedModders LLC
17 "MyJailbreak - NoScope" (Beta 13.0-<COMMIT>) by shanapu
18 "Admin Menu" (1.8.0.6047) by AlliedModders LLC
19 "MyJailbreak - Zeus" (Beta 13.0-<COMMIT>) by shanapu
20 "[Source 2013] Custom Chat Colors" (3.1.0 CP) by Dr. McKay, Fixed up by Keith Warren (Shaders Allen)
21 "MyJailbreak - PlayerTags" (Beta 12.0.dev-184bb6c) by shanapu
22 "SourceBans: Admin Config Loader" ((SB++) 1.5.4.3) by AlliedModders LLC, Sarabveer(VEER™)
23 "MyJailbreak - Torch Relay" (Beta 13.0-<COMMIT>) by shanapu
24 "MyJailbreak - Ghosts War" (Beta 13.0-<COMMIT>) by shanapu
25 "MyJailbreak - Last Guard Rule" (Beta 13.0-<COMMIT>) by shanapu
26 "Anti-Flood" (1.8.0.6047) by AlliedModders LLC
27 "VoiceAnnounceEx" (2.1.2) by Franc1sco franug, Mini and GoD-Tony
28 "Chat Processor - Simple Chat Processor Wrapper" (1.0.0) by Keith Warren (Shaders Allen)
29 "Basic Commands" (1.8.0.6047) by AlliedModders LLC
30 "Fun Commands" (1.8.0.6047) by AlliedModders LLC
31 <Error> "SourceSleuth" ((SB++) 1.5.4.3) by ecca, Sarabveer(VEER™)
32 "OVERWATCH:Death" (1.0) by Potatoz
33 "MyJailbreak - Warden" (Beta 13.0-<COMMIT>) by shanapu
34 "Move Commands ( ResetScore, Switch, Spec )" (2.0.1) by Bara
35 "SourceComms" ((SB++) 1.5.4.3) by Alex, Sarabveer(VEER™)
36 "MyJailbreak - Suicide Bomber" (Beta 13.0-<COMMIT>) by shanapu
37 "MyJailbreak - Freeday" (Beta 13.0-<COMMIT>) by shanapu
38 "MyJailbreak - Menus" (Beta 13.0-<COMMIT>) by shanapu
39 "MyJailbreak - War FFA" (Beta 13.0-<COMMIT>) by shanapu
40 "MyJailbreak - Teleport War" (Beta 13.0-<COMMIT>) by shanapu
41 "Fun Votes" (1.8.0.6047) by AlliedModders LLC
42 "MyJailbreak - Zombie" (Beta 13.0-<COMMIT>) by shanapu
43 "Basic Comm Control" (1.8.0.6047) by AlliedModders LLC
44 "MyJailbreak - Arms Race" (Beta 13.0-<COMMIT>) by shanapu
45 "Custom Player Skins (Core)" (1.4) by Mitchell, Root
46 "MyJailbreak - War" (Beta 13.0-<COMMIT>) by shanapu
47 "SourceBans Checker" ((SB++) 1.5.4.3) by psychonic, Ca$h Munny, Sarabveer(VEER™)
48 "Admin File Reader" (1.8.0.6047) by AlliedModders LLC
49 "MyJailbreak - Weapons" (Beta 13.0-<COMMIT>) by shanapu
50 "SourceBans++" (1.5.4.3) by SourceBans Development Team, Sarabveer(VEER™)
51 "MyJailbreak - Request" (Beta 13.0-<COMMIT>) by shanapu
52 "MyJailbreak - Player HUD" (Beta 13.0-<COMMIT>) by shanapu
53 "MyJailbreak - CowBoy" (Beta 13.0-<COMMIT>) by shanapu
54 "MyJailbreak - OneInTheChamber" (Beta 13.0-<COMMIT>) by Hexah | shanapu
55 "MyJailbreak - HE Battle" (Beta 13.0-<COMMIT>) by shanapu
56 "Client Preferences" (1.8.0.6047) by AlliedModders LLC
57 "MyJailbreak - Icons" (Beta 13.0-<COMMIT>) by shanapu
58 "OVERWATCH:Buttons" (1.0) by Potatoz
59 "MyJailbreak - Drunk" (Beta 13.0-<COMMIT>) by shanapu
60 "MyJailbreak - DealDamage" (Beta 13.0-<COMMIT>) by shanapu
61 "Basic Votes" (1.8.0.6047) by AlliedModders LLC
62 "Test Messages" (1.0.0) by Keith Warren (Shaders Allen)
63 "Reserved Slots" (1.8.0.6047) by AlliedModders LLC
64 "MyJailbreak - Core" (Beta 13.0-<COMMIT>) by shanapu
65 <Failed> "Nextmap" (1.8.0.6047) by AlliedModders LLC
```

**Comment by shanapu** [comment]
> Dodgeball LR isn't working - the health changes to 1hp and doesn't give a flash
> 
> Gun toss - When both guns are thrown, it shows the distance, but doesn't alert who was the winner or give the winning person a gun to kill the enemy.

These are not related to MyJailbreak, these are sm_hosties features.

> Player names - when you look at a player, their name doesn't appear in red text like other JB servers. 

This is not a feature of MyJailbreak. There're many plugins out there for this.

> Duckhunt LR - Whenever I start this LR, I get this in console:
> CalcSequenceIndex: can't find 'idle_upper_gren'.
> ...

Duckhunt is not a LR, it's a event day. This console output is normal and harmless.

>Noscope LR - doesn't give you the gun (This appeared in console: (Tried to look up command say as if it were a variable.)

Noscope is not a LR, it's a event day. This console output is normal and harmless.
Noscope works fine on my side. You don't need any client console output, when you have an issue. We need your `addons/sourcemod/logs/errors_xxxxxxx.log` files. 
Also would be good to know if you use default configs for the issued event(s), if not we weed your .cfgs

> Here are all my plugins, let me know if you need more information.
> [SM] Listing 65 plugins:

phew... 
`31 <Error> "SourceSleuth" ((SB++) 1.5.4.3) by ecca, Sarabveer(VEER™)`
`35 "SourceComms" ((SB++) 1.5.4.3) by Alex, Sarabveer(VEER™)`
very old version. runs doubled
`50 "SourceBans++" (1.5.4.3) by SourceBans Development Team, Sarabveer(VEER™)`
very old version. iirc security issues.
`06 "SM_Hosties v2" (2.2.0) by databomb & dataviruset & comando`
old version.
`21 "MyJailbreak - PlayerTags" (Beta 12.0.dev-184bb6c) by shanapu`
very old version.
`"MyJailbreak - xxxxx" (Beta 13.0-<COMMIT>) by shanapu`
you compiled the most of myjailbreaks files for yourself, so I have to assume you have done some edits to them.
Share your edits or use files from [download page](https://shanapu.de/myjailbreak)

Please take a look at the [faq](https://github.com/shanapu/MyJailbreak/wiki/Frequently-Asked-Questions) and more than anything at this part:

**Open one Issue on github per request/errors/problems. Split many requests/errors/problems to different Issues. Thanks!**

**Comment by KewaiiGamer** [comment]
Even though there is no need for console output in order to report issues, console warning/errors are still a signal that the addon is not optimized.

This might be not related to the issue but it's still an issue.

**Comment by shanapu** [comment]
I agree with you completely, a console warning is still an issue even when it is "(normal and) harmless".

```
CalcSequenceIndex: can't find 'idle_upper_gren'.
CalcSequenceIndex: can't find 'walk_upper_gren'.
CalcSequenceIndex: can't find 'run_upper_gren'.
CalcSequenceIndex: can't find 'crouch_idle_upper_gren'.
CalcSequenceIndex: can't find 'run_shoot_gren1'.
CalcSequenceIndex: can't find 'walk_shoot_gren1'.
```
In this case, the error occurs because of a [bad chicken model](https://github.com/shanapu/MyJailbreak/blob/master/models/chicken/chicken.mdl) with missing animation.
IMHO since these animations are not deciding, I don't see this as a real issue for MyJB. 

Maybe I'll stumble across a better chicken(duck) model in future and will replace it. 
Or if you or anyone else see a need for, I will implement a cvar for changing the chicken model. (to add dragons or some other pets?!)

If you see this not as solved. please open an new issue.

PS: it should also be possible to turn the player into a chicken without an external model? oO
