### ISSUE TITLE
Server crash . Warden problem .

### ISSUE THREAD

**Issue by dimahail** [shanapu/MyJailbreak#304]
The server goes into crash . Here is the logs
Plugin version Beta 13.0.dev-4882445

> L 07/11/2018 - 13:57:39: [SM] Blaming: MyJailbreak/warden.smx
L 07/11/2018 - 13:57:39: [SM] Call stack trace:
L 07/11/2018 - 13:57:39: [SM]   [0] GetClientUserId
L 07/11/2018 - 13:57:39: [SM]   [1] Line 86, addons/sourcemod/scripting/MyJailbreak/MyJailbreak/Modules/Warden/color.sp::Color_OnDeputyRemoved
L 07/11/2018 - 13:57:39: [SM]   [2] Line 677, addons/sourcemod/scripting/MyJailbreak/MyJailbreak/Modules/Warden/deputy.sp::Forward_OnDeputyRemoved
L 07/11/2018 - 13:57:39: [SM]   [3] Line 443, addons/sourcemod/scripting/MyJailbreak/MyJailbreak/Modules/Warden/deputy.sp::Deputy_OnAvailableLR
L 07/11/2018 - 13:57:39: [SM]   [4] Line 1063, addons/sourcemod/scripting/MyJailbreak/warden.sp::OnAvailableLR
L 07/11/2018 - 13:57:39: [SM]   [6] Call_Finish
L 07/11/2018 - 13:57:39: [SM]   [7] Line 1140, hosties/lastrequest.sp::LastRequest_PlayerDeath
L 07/11/2018 - 14:09:14: [SM] Exception reported: Client index 0 is invalid

**Comment by shanapu** [comment]
hi thanks for the report!

The [error is fixed](https://github.com/shanapu/MyJailbreak/commit/9cd9976becff85d9042f2e3dec9745c0a45ec35e), but I can't imagine this error is the reason for a server crash.
