### ISSUE TITLE
Hello, jailbreak crashes server at join

### ISSUE THREAD

**Issue by WolfCZE** [shanapu/MyJailbreak#316]
Hello i tried to add to server jailbreak plugin for sourcemod 1.9 , and second one for sm 1.8 but all is crashing server at join. At join u cannot join any team, just like 10 secs is showing up stats about guards and Ts and its crash server: Up in right corner its write: Bad connection, any fix? I tried all but still not work.

Thanks for reading that. :)

**Comment by Hexer10** [comment]
We need more information, send us any logs, the accelerator crash code and your OS

**Comment by WolfCZE** [comment]
I have csgo server hosted in hicoria.com

**Comment by WolfCZE** [comment]
18:30:37 Initializing Steam libraries for secure Internet server 
18:30:37 Logging into Steam gameserver account with logon token '11B1DBC1xxxxxxxxxxxxxxxxxxxxxxxx' 
18:30:38 Connection to Steam servers successful. 
18:30:38 Public IP is 89.203.248.75. 
18:30:38 Assigned persistent gameserver Steam ID [G:1:2568451]. 
18:30:39 VAC secure mode is activated. 
18:30:39 GC Connection established for server version 803, instance idx 1 
18:31:28 -> Reservation cookie a8aeba78d5fbdc25: reason [R] Connect from 89.177.70.19:27005 
18:31:28 Client "╦óßÁśßÁľ╩│ßÁëßÁÉßÁë" connected (89.177.70.19:27005). 
18:31:28 Server waking up from hibernation 
18:31:29 ---- Host_Changelevel ---- 
18:31:29 *** Map Load: cs_office: Map Group h_customL 11/07/2018 - 18:31:29: -------- Mapchange to cs_office -------- 
18:31:29 L 11/07/2018 - 18:31:29: Error log file session closed. 
18:31:29 GameTypes: missing mapgroupsSP entry for game type/mode (custom/custom). 
18:31:29 GameTypes: missing mapgroupsSP entry for game type/mode (cooperative/cooperative). 
18:31:29 GameTypes: missing mapgroupsSP entry for game type/mode (cooperative/coopmission). 
18:31:29 ammo_grenade_limit_default - 1 
18:31:29 ammo_grenade_limit_flashbang - 1 
18:31:29 ammo_grenade_limit_total - 3 
18:31:29 bot_allow_grenades - 1 
18:31:29 bot_allow_machine_guns - 1 
18:31:29 bot_allow_pistols - 1 
18:31:29 bot_allow_rifles - 1 
18:31:29 bot_allow_rogues - 1 
18:31:29 bot_allow_shotguns - 1 
18:31:29 bot_allow_snipers - 1 
18:31:29 bot_allow_sub_machine_guns - 1 
18:31:29 bot_autodifficulty_threshold_high - 5.0 
18:31:29 bot_autodifficulty_threshold_low - -2.0 
18:31:29 bot_chatter - normal 
18:31:29 bot_defer_to_human_goals - 0 
18:31:29 bot_defer_to_human_items - 1 
18:31:29 bot_difficulty - 1 
18:31:29 bot_quota - 10 
18:31:29 bot_quota_mode - normal 
18:31:29 cash_player_bomb_defused - 300 
18:31:29 cash_player_bomb_planted - 300 
18:31:29 cash_player_damage_hostage - -30 
18:31:29 cash_player_get_killed - 0 
18:31:29 cash_player_interact_with_hostage - 150 
18:31:29 cash_player_killed_enemy_default - 300 
18:31:29 cash_player_killed_enemy_factor - 1 
18:31:29 cash_player_killed_hostage - -1000 
18:31:29 cash_player_killed_teammate - -300 
18:31:29 cash_player_rescued_hostage - 1000 
18:31:29 cash_player_respawn_amount - 0 
18:31:29 cash_team_elimination_bomb_map - 3250 
18:31:29 cash_team_elimination_hostage_map_ct - 2000 
18:31:29 cash_team_elimination_hostage_map_t - 1000 
18:31:29 cash_team_hostage_alive - 0 
18:31:29 cash_team_hostage_interaction - 500 
18:31:29 cash_team_loser_bonus - 1400 
18:31:29 cash_team_loser_bonus_consecutive_rounds - 500 
18:31:29 cash_team_planted_bomb_but_defused - 800 
18:31:29 cash_team_rescued_hostage - 0 
18:31:29 cash_team_survive_guardian_wave - 1000 
18:31:29 cash_team_terrorist_win_bomb - 3500 
18:31:29 cash_team_win_by_defusing_bomb - 3250 
18:31:29 cash_team_win_by_hostage_rescue - 3500 
18:31:29 cash_team_win_by_time_running_out_bomb - 3250 
18:31:29 cash_team_win_by_time_running_out_hostage - 3250 
18:31:29 ff_damage_reduction_bullets - 0.1 
18:31:29 ff_damage_reduction_grenade - 0.25 
18:31:29 ff_damage_reduction_grenade_self - 1 
18:31:29 ff_damage_reduction_other - 0.25 
18:31:29 global_chatter_info - 
18:31:29 mp_afterroundmoney - 0 
18:31:29 mp_anyone_can_pickup_c4 - 0 
18:31:29 mp_autoteambalance - 1 
18:31:29 mp_buy_allow_grenades - 1 
18:31:29 mp_buy_allow_guns - 255 
18:31:29 mp_buy_anywhere - 0 
18:31:29 mp_buy_during_immunity - 0 
18:31:29 mp_buytime - 90 
18:31:29 mp_c4_cannot_be_defused - 0 
18:31:29 mp_c4timer - 40 
18:31:29 mp_consecutive_loss_max - 4 
18:31:29 mp_coop_force_join_ct - 0 
18:31:29 mp_coopmission_bot_difficulty_offset - 0 
18:31:29 mp_coopmission_mission_number - 0 
18:31:29 mp_ct_default_grenades - 
18:31:29 mp_ct_default_melee - weapon_knife 
18:31:29 mp_ct_default_primary - 
18:31:29 mp_ct_default_secondary - weapon_hkp2000 
18:31:29 mp_damage_headshot_only - 0 
18:31:29 mp_damage_scale_ct_body - 1.0 
18:31:29 mp_damage_scale_ct_head - 1.0 
18:31:29 mp_damage_scale_t_body - 1.0 
18:31:29 mp_damage_scale_t_head - 1.0 
18:31:29 mp_damage_vampiric_amount - 0 
18:31:29 mp_death_drop_c4 - 1 
18:31:29 mp_death_drop_defuser - 1 
18:31:29 mp_death_drop_grenade - 2 
18:31:29 mp_death_drop_gun - 1 
18:31:29 mp_deathcam_skippable - 1 
18:31:29 mp_default_team_winner_no_objective - -1 
18:31:29 mp_defuser_allocation - 0 
18:31:29 mp_display_kill_assists - 1 
18:31:29 mp_dm_bonus_percent - 50 
18:31:29 mp_dm_bonus_respawn - 0 
18:31:29 mp_dm_bonusweapon_dogtags - 0 
18:31:29 mp_dm_dogtag_score - 0 
18:31:29 mp_dm_kill_base_score - 10 
18:31:29 mp_dm_teammode - 0 
18:31:29 mp_dm_teammode_bonus_score - 1 
18:31:29 mp_dm_teammode_dogtag_score - 0 
18:31:29 mp_dm_teammode_kill_score - 1 
18:31:29 mp_dogtag_despawn_on_killer_death - 1 
18:31:29 mp_dogtag_despawn_time - 120 
18:31:29 mp_dogtag_pickup_rule - 0 
18:31:29 mp_economy_reset_rounds - 0 
18:31:29 mp_equipment_reset_rounds - 0 
18:31:29 mp_force_assign_teams - 0 
18:31:29 mp_force_pick_time - 15 
18:31:29 mp_forcecamera - 1 
18:31:29 mp_free_armor - 0 
18:31:29 mp_freezetime - 6 
18:31:29 mp_friendlyfire - 0 
18:31:29 mp_ggprogressive_round_restart_delay - 15.0 
18:31:29 mp_ggtr_always_upgrade - 0 
18:31:29 mp_ggtr_bomb_defuse_bonus - 1 
18:31:29 mp_ggtr_bomb_detonation_bonus - 1 
18:31:29 mp_ggtr_bomb_pts_for_flash - 4 
18:31:29 mp_ggtr_bomb_pts_for_he - 3 
18:31:29 mp_ggtr_bomb_pts_for_molotov - 5 
18:31:29 mp_ggtr_bomb_pts_for_upgrade - 2.0 
18:31:29 mp_ggtr_bomb_respawn_delay - 0.0 
18:31:29 mp_ggtr_end_round_kill_bonus - 1 
18:31:29 mp_ggtr_halftime_delay - 0.0 
18:31:29 mp_ggtr_last_weapon_kill_ends_half - 0 
18:31:29 mp_give_player_c4 - 1 
18:31:29 mp_global_damage_per_second - 0.0 
18:31:29 mp_guardian_bot_money_per_wave - 800 
18:31:29 mp_guardian_loc_adjective - 
18:31:29 mp_guardian_loc_condition - 
18:31:29 mp_guardian_loc_icon - 
18:31:29 mp_guardian_loc_mission - default 
18:31:29 mp_guardian_loc_override - 
18:31:29 mp_guardian_loc_weapon - 
18:31:29 mp_guardian_player_dist_max - 2000 
18:31:29 mp_guardian_player_dist_min - 1300 
18:31:29 mp_guardian_special_kills_needed - 10 
18:31:29 mp_guardian_special_weapon_needed - awp 
18:31:29 mp_guardian_target_site - -1 
18:31:29 mp_halftime - 0 
18:31:29 mp_halftime_pausetimer - 0 
18:31:29 mp_heavyassaultsuit_cooldown - 5 
18:31:29 mp_hostagepenalty - 10 
18:31:29 mp_hostages_max - 2 
18:31:29 mp_hostages_spawn_force_positions - 
18:31:29 mp_hostages_spawn_same_every_round - 1 
18:31:29 mp_items_prohibited - 
18:31:29 mp_limitteams - 2 
18:31:29 mp_match_can_clinch - 1 
18:31:29 mp_max_armor - 2 
18:31:29 mp_maxmoney - 16000 
18:31:29 mp_maxrounds - 0 
18:31:29 mp_molotovusedelay - 15.0 
18:31:29 mp_playercashawards - 1 
18:31:29 mp_radar_showall - 0 
18:31:29 mp_randomspawn - 0 
18:31:29 mp_randomspawn_dist - 0 
18:31:29 mp_randomspawn_los - 1 
18:31:29 mp_respawn_immunitytime - 4.0 
18:31:29 mp_respawn_on_death_ct - 0 
18:31:29 mp_respawn_on_death_t - 0 
18:31:29 mp_respawnwavetime_ct - 10.0 
18:31:29 mp_respawnwavetime_t - 10.0 
18:31:29 mp_round_restart_delay - 7.0 
18:31:29 mp_roundtime - 5 
18:31:29 mp_roundtime_defuse - 0 
18:31:29 mp_roundtime_hostage - 0 
18:31:29 mp_solid_teammates - 1 
18:31:29 mp_starting_losses - 0 
18:31:29 mp_startmoney - 800 
18:31:29 mp_t_default_grenades - 
18:31:29 mp_t_default_melee - weapon_knife 
18:31:29 mp_t_default_primary - 
18:31:29 mp_t_default_secondary - weapon_glock 
18:31:29 mp_taser_recharge_time - -1 
18:31:29 mp_teamcashawards - 1 
18:31:29 mp_teammates_are_enemies - 0 
18:31:29 mp_timelimit - 5 
18:31:29 mp_use_respawn_waves - 0 
18:31:29 mp_warmup_pausetimer - 0 
18:31:29 mp_warmuptime - 30 
18:31:29 mp_warmuptime_all_players_connected - 0 
18:31:29 mp_weapon_self_inflict_amount - 0 
18:31:29 mp_weapons_allow_heavy - -1 
18:31:29 mp_weapons_allow_heavyassaultsuit - 0 
18:31:29 mp_weapons_allow_map_placed - 0 
18:31:29 mp_weapons_allow_pistols - -1 
18:31:29 mp_weapons_allow_rifles - -1 
18:31:29 mp_weapons_allow_smgs - -1 
18:31:29 mp_weapons_allow_typecount - 5 
18:31:29 mp_weapons_allow_zeus - 1 
18:31:29 mp_weapons_glow_on_ground - 0 
18:31:29 mp_weapons_max_gun_purchases_per_weapon_per_match - -1 
18:31:29 mp_heavyassaultsuit_speed - 130 
18:31:29 mp_heavyassaultsuit_deploy_timescale - 0.8 
18:31:29 mp_heavyassaultsuit_aimpunch - 1.0 
18:31:29 mp_heavybot_damage_reduction_scale - 1.0 
18:31:29 mp_win_panel_display_time - 3 
18:31:29 occlusion_test_async - 0 
18:31:29 spec_freeze_panel_extended_time - 0.0 
18:31:29 spec_freeze_time - 3.0 
18:31:29 spec_replay_enable - 0 
18:31:29 sv_accelerate - 5.5 
18:31:29 sv_airaccelerate - 12 
18:31:29 sv_allow_votes - 1 
18:31:29 sv_alltalk - 0 
18:31:29 sv_arms_race_vote_to_restart_disallowed_after - 0 
18:31:29 sv_auto_adjust_bot_difficulty - 1 
18:31:29 sv_auto_full_alltalk_during_warmup_half_end - 1 
18:31:29 sv_autobunnyhopping - 0 
18:31:29 sv_autobuyammo - 0 
18:31:29 sv_bot_buy_decoy_weight - 1 
18:31:29 sv_bot_buy_flash_weight - 1 
18:31:29 sv_bot_buy_grenade_chance - 33 
18:31:29 sv_bot_buy_hegrenade_weight - 6 
18:31:29 sv_bot_buy_molotov_weight - 1 
18:31:29 sv_bot_buy_smoke_weight - 1 
18:31:29 sv_bots_force_rebuy_every_round - 0 
18:31:29 sv_bots_get_easier_each_win - 0 
18:31:29 sv_bots_get_harder_after_each_wave - 0 
18:31:29 sv_bounce - 0 
18:31:29 sv_buy_status_override - -1 
18:31:29 sv_deadtalk - 0 
18:31:29 sv_disable_show_team_select_menu - 0 
18:31:29 sv_duplicate_playernames_ok - 0 
18:31:29 sv_enablebunnyhopping - 0 
18:31:29 sv_friction - 5.2 
18:31:29 sv_gravity - 800 
18:31:29 sv_guardian_heavy_all - 0 
18:31:29 sv_guardian_heavy_count - 0 
18:31:29 sv_guardian_max_wave_for_heavy - 0 
18:31:29 sv_guardian_min_wave_for_heavy - 0 
18:31:29 sv_ignoregrenaderadio - 0 
18:31:29 sv_infinite_ammo - 0 
18:31:29 sv_maxspeed - 320 
18:31:29 sv_maxvelocity - 3500 
18:31:29 sv_occlude_players - 1 
18:31:29 sv_staminajumpcost - .080 
18:31:29 sv_staminalandcost - .050 
18:31:29 sv_stopspeed - 80 
18:31:29 sv_talk_enemy_dead - 0 
18:31:29 sv_talk_enemy_living - 0 
18:31:29 sv_vote_to_changelevel_before_match_point - 0 
18:31:29 sv_wateraccelerate - 10 
18:31:29 sv_waterfriction - 1 
18:31:29 tv_delay - 10 
18:31:29 weapon_accuracy_nospread - 0 
18:31:29 weapon_air_spread_scale - 1.0 
18:31:29 weapon_max_before_cleanup - 0 
18:31:29 weapon_recoil_scale - 2.0 
18:31:29 weapon_reticle_knife_show - 0 
18:31:29 ff_damage_reduction_grenade - 0.25 
18:31:29 ff_damage_reduction_grenade_self - 1 
18:31:29 ff_damage_reduction_other - 0.25 
18:31:29 mp_friendlyfire - 0 
18:31:29 mp_warmuptime - 30 
18:31:29 mp_warmuptime_all_players_connected - 0 
18:31:29 Executing dedicated server config file 
18:31:29 Unknown command "sv_maxcmdrate" 
18:31:29 Unknown command "sv_vote_creation_time" 
18:31:29 Writing cfg/banned_user.cfg. 
18:31:29 Writing cfg/banned_ip.cfg. 
18:31:29 Unknown command "allow_spectators" 
18:31:29 exec: couldn't exec gamemode_competitive_server.cfg 
18:31:29 Commentary: Could not find commentary data file 'maps/cs_office_commentary.txt'. 
18:31:29 Error parsing BotProfile.db - unknown attribute 'Rank' 
18:31:29 Error parsing BotProfile.db - unknown attribute 'Rank' 
18:31:29 Error parsing BotProfile.db - unknown attribute 'Rank' 
18:31:29 Error parsing BotProfile.db - unknown attribute 'Rank' 
18:31:29 Error parsing BotProfile.db - unknown attribute 'Rank' 
18:31:29 Error parsing BotProfile.db - unknown attribute 'Rank' 
18:31:29 Error parsing BotProfile.db - unknown attribute 'Rank' 
18:31:29 Error parsing BotProfile.db - unknown attribute 'Rank' 
18:31:33 L 11/07/2018 - 18:31:33: [SM] Exception reported: Failed to locate function 
18:31:33 L 11/07/2018 - 18:31:33: [SM] Blaming: MyJailbreak\playertags.smx 
18:31:33 L 11/07/2018 - 18:31:33: [SM] Call stack trace: 
18:31:33 L 11/07/2018 - 18:31:33: [SM] [0] CS_GetClientClanTag 
18:31:33 L 11/07/2018 - 18:31:33: [SM] [1] Line 351, addons/sourcemod/scripting/MyJailbreak/playertags.sp::OnClientPostAdminCheck 
18:31:33 PutClientInServer: no info_player_start on level

**Comment by WolfCZE** [comment]
18:54:00 L 11/07/2018 - 18:54:00: [SM] Exception reported: Cannot set m_iItemDefinitionIndex with "FollowCSGOServerGuidelines" option enabled. 
18:54:00 L 11/07/2018 - 18:54:00: [SM] Blaming: sm_franugknife.smx 
18:54:00 L 11/07/2018 - 18:54:00: [SM] Call stack trace: 
18:54:00 L 11/07/2018 - 18:54:00: [SM] [0] SetEntProp 
18:54:00 L 11/07/2018 - 18:54:00: [SM] [1] Line 63, C:\Users\barcl\Desktop\sm_franugknife.sp::OnPostWeaponEquip 
18:54:00 L 11/07/2018 - 18:54:00: [SM] [3] ChangeClientTeam 
18:54:00 L 11/07/2018 - 18:54:00: [SM] [4] Line 1263, addons/sourcemod/scripting/MyJailbreak/ratio.sp::Timer_ForceTSide 
18:54:00 L 11/07/2018 - 18:54:00: [SM] Exception reported: Cannot set m_iItemDefinitionIndex with "FollowCSGOServerGuidelines" option enabled. 
18:54:00 L 11/07/2018 - 18:54:00: [SM] Blaming: sm_franugknife.smx 
18:54:00 L 11/07/2018 - 18:54:00: [SM] Call stack trace: 
18:54:00 L 11/07/2018 - 18:54:00: [SM] [0] SetEntProp 
18:54:00 L 11/07/2018 - 18:54:00: [SM] [1] Line 63, C:\Users\barcl\Desktop\sm_franugknife.sp::OnPostWeaponEquip 
18:54:00 L 11/07/2018 - 18:54:00: [SM] [3] GivePlayerItem 
18:54:00 L 11/07/2018 - 18:54:00: [SM] [4] Line 84, hosties/startweapons.sp::StartWeapons_Spawn 
18:54:00 L 11/07/2018 - 18:54:00: [SM] [6] ChangeClientTeam 
18:54:00 L 11/07/2018 - 18:54:00: [SM] [7] Line 1263, addons/sourcemod/scripting/MyJailbreak/ratio.sp::Timer_ForceTSide 
18:54:00 L 11/07/2018 - 18:54:00: World triggered "Game_Commencing"

**Comment by WolfCZE** [comment]
https://www.youtube.com/watch?v=6xlRyjG8WQg

**Comment by WolfCZE** [comment]
its doing this

**Comment by shanapu** [comment]
go to your hoster panel and go to server console. type 'sm plugins list' and copy paste the output.

disable MyJailbreak\playertags.smx until sourcemod get updated. 
https://github.com/alliedmodders/sourcemod/pull/922 this is the related pr

deinstall `sm_franugknife.smx` until you know what you are doing, this plugin can ban your account.

**Comment by WolfCZE** [comment]
07:19:59 01 "Admin File Reader" (1.9.0.6252) by AlliedModders LLC 
07:19:59 02 "Admin Help" (1.9.0.6252) by AlliedModders LLC 
07:19:59 03 "Admin Menu" (1.9.0.6252) by AlliedModders LLC 
07:19:59 04 "Anti-Flood" (1.9.0.6252) by AlliedModders LLC 
07:19:59 05 "Basic Ban Commands" (1.9.0.6252) by AlliedModders LLC 
07:19:59 06 "Basic Chat" (1.9.0.6252) by AlliedModders LLC 
07:19:59 07 "Basic Comm Control" (1.9.0.6252) by AlliedModders LLC 
07:19:59 08 "Basic Commands" (1.9.0.6252) by AlliedModders LLC 
07:19:59 09 "Basic Info Triggers" (1.9.0.6252) by AlliedModders LLC 
07:19:59 10 "Basic Votes" (1.9.0.6252) by AlliedModders LLC 
07:19:59 11 "Client Preferences" (1.9.0.6252) by AlliedModders LLC 
07:19:59 12 "Fun Commands" (1.9.0.6252) by AlliedModders LLC 
07:19:59 13 "Fun Votes" (1.9.0.6252) by AlliedModders LLC 
07:19:59 14 "MyJailbreak - Arms Race" (Beta 14.0-58f4b42) by shanapu 
07:19:59 15 "MyJailbreak - Catch & Freeze" (Beta 14.0-58f4b42) by shanapu 
07:19:59 16 "MyJailbreak - CowBoy" (Beta 14.0-58f4b42) by shanapu 
07:19:59 17 "MyJailbreak - DealDamage" (Beta 14.0-58f4b42) by shanapu 
07:19:59 18 "MyJailbreak - Drunk" (Beta 14.0-58f4b42) by shanapu 
07:19:59 19 "MyJailbreak - DuckHunt" (Beta 14.0-58f4b42) by shanapu 
07:19:59 20 "MyJailbreak - War FFA" (Beta 14.0-58f4b42) by shanapu 
07:19:59 21 "MyJailbreak - Freeday" (Beta 14.0-58f4b42) by shanapu 
07:19:59 22 "MyJailbreak - Ghosts War" (Beta 14.0-58f4b42) by shanapu 
07:19:59 23 "MyJailbreak - HE Battle" (Beta 14.0-58f4b42) by shanapu 
07:19:59 24 "MyJailbreak - HideInTheDark" (Beta 14.0-58f4b42) by shanapu 
07:19:59 25 "MyJailbreak - Player HUD" (Beta 14.0-58f4b42) by shanapu 
07:19:59 26 "MyJailbreak - Icons" (Beta 14.0-58f4b42) by shanapu 
07:19:59 27 "MyJailbreak - KnifeFight" (Beta 14.0-58f4b42) by shanapu 
07:19:59 28 "MyJailbreak - Last Guard Rule" (Beta 14.0-58f4b42) by shanapu 
07:19:59 29 "MyJailbreak - Menus" (Beta 14.0-58f4b42) by shanapu 
07:19:59 30 "MyJailbreak - Core" (Beta 14.0-58f4b42) by shanapu 
07:19:59 31 "MyJailbreak - NoScope" (Beta 14.0-58f4b42) by shanapu 
07:19:59 32 "MyJailbreak - OneInTheChamber" (Beta 14.0-58f4b42) by Hexah | shanapu 
07:19:59 33 "MyJailbreak - Ratio" (Beta 14.0-58f4b42) by shanapu, Addicted 
07:19:59 34 "MyJailbreak - Request" (Beta 14.0-58f4b42) by shanapu 
07:19:59 35 "MyJailbreak - Suicide Bomber" (Beta 14.0-58f4b42) by shanapu 
07:19:59 36 "MyJailbreak - Teleport War" (Beta 14.0-58f4b42) by shanapu 
07:19:59 37 "MyJailbreak - Torch Relay" (Beta 14.0-58f4b42) by shanapu 
07:19:59 38 "MyJailbreak - War" (Beta 14.0-58f4b42) by shanapu 
07:19:59 39 "MyJailbreak - Warden" (Beta 14.0-58f4b42) by shanapu 
07:19:59 40 "MyJailbreak - Weapons" (Beta 14.0-58f4b42) by shanapu 
07:19:59 41 "MyJailbreak - Zeus" (Beta 14.0-58f4b42) by shanapu 
07:19:59 42 "MyJailbreak - Zombie" (Beta 14.0-58f4b42) by shanapu 
07:19:59 43 "Nextmap" (1.9.0.6252) by AlliedModders LLC 
07:19:59 44 "Player Commands" (1.9.0.6252) by AlliedModders LLC 
07:19:59 45 "Reserved Slots" (1.9.0.6252) by AlliedModders LLC 
07:19:59 46 "Smart Jail Doors" (0.5.2-beta) by Maxim 'Kailo' Telezhenko 
07:19:59 47 "SM_Hosties v2" (2.2.0) by databomb & dataviruset & comando 
07:19:59 48 "Sound Commands" (1.9.0.6252) by AlliedModders LLC

**Comment by WolfCZE** [comment]
07:20:30 SourceMod Version Information: 
07:20:30 SourceMod Version: 1.9.0.6252 
07:20:30 SourcePawn Engine: 1.9.0.6252, jit-x86 (build 1.9.0.6252) 
07:20:30 SourcePawn API: v1 = 4, v2 = 12 
07:20:30 Compiled on: Sep 12 2018 07:37:26 
07:20:30 Built from: https://github.com/alliedmodders/sourcemod/commit/14eaa097 
07:20:30 Build ID: 6252:14eaa097 
07:20:30 http://www.sourcemod.net/

**Comment by WolfCZE** [comment]
and the server still doing same...

**Comment by Hexer10** [comment]
The ClanTag signature was update 15 hour ago: https://github.com/alliedmodders/sourcemod/commit/a084b3295e8c81a74e859d6f3e3be9a026e121cc

**Comment by WolfCZE** [comment]
yes but still not work

**Comment by shanapu** [comment]
'still not work' is not a proper error message / description. not a bit helpful. We're here to help you. 
But you must help us, helping you!

please post updated helpful info: 
https://github.com/shanapu/MyJailbreak/wiki/Frequently-Asked-Questions#what-should-i-consider-if-i-open-a-issue-or-post-on-forum

btw. if I've seen it right on your video, you haven't even restart your server after installing.

**Comment by shanapu** [comment]
Tip: 
1. disable all plugins
2. enable plugin one by one
3. check after every plugin for errors
4. keep bad plugin with error disabled, keep on.
5. report bad plugin to plugin author

this is how to find a bad plugin.

**Comment by shanapu** [comment]
:/ 


> [22:46]
> ˢᵘᵖʳᵉᵐᵉ:
> 	ey bro? can u lock my issue? i reinstalled server tried it with new version and it works.
https://steamcommunity.com/profiles/76561198867886154
