### ISSUE TITLE
Server crashed for some reason = icons.smx | warden.smx

### ISSUE THREAD

**Issue by nanociaglia** [shanapu/MyJailbreak#317]
This is the crash url: https://crash.limetech.org/h2h75pdiubrk

Now accelerator tell you what plugin is causing the crash, so:

http://prntscr.com/lgont1
http://prntscr.com/lgonuu

**Comment by shanapu** [comment]
> Now accelerator tell you what plugin is causing the crash...

sweet! didn't knew.

I going to investigate this. 
Do you have steps to reproduce the crash? 
seems like it occurs when the warden disconnects!?

**Comment by nanociaglia** [comment]
It was a random crash🤷‍♂️
We were playing and the server crashed at the middle of the round

**Comment by shanapu** [comment]
uff, I tried ~one hour with a mate to reproduce this crash. We tried all way we imagine disconnecting as warden (..., while tasing), force closing, ... to make it crash. But no crash :/

Did it happen for you again or more than once?

**Comment by nanociaglia** [comment]
This didn't happen after that, maybe was a random crash that won't happen again

**Comment by shanapu** [comment]
ok, thanks for the reply. 
I going to close this. If this happens again, please open a new issue with reference.
