### ISSUE TITLE
Event days dont show up in the event day menu for wardens & admins

### ISSUE THREAD

**Issue by Garlicvideos** [shanapu/MyJailbreak#318]
In the event day category of the warden menu, there is nothing there. Admins dont have any event days listed in their menu either. I have all the event day plugins loaded, nothing related to eventdays shows up in the error logs. None of the plugins have trouble loading.

Heres my plugin list

> 01 "Basic Chat" (1.9.0.6261) by AlliedModders LLC
  02 "Admin File Reader" (1.9.0.6261) by AlliedModders LLC
  03 "MyJailbreak - Suicide Bomber" (Beta 14.0-58f4b42) by shanapu
  04 "MyJailbreak - MostActive Support for Ratio & Warden" (Beta 14.0-58f4b42) by shanapu, Addicted, good_live
  05 "MyJailbreak - NoScope" (Beta 14.0-58f4b42) by shanapu
  06 "MyJailbreak - Teleport War" (Beta 14.0-58f4b42) by shanapu
  07 "MyJailbreak - Request" (Beta 14.0-58f4b42) by shanapu
  08 "MyJailbreak - HideInTheDark" (Beta 14.0-58f4b42) by shanapu
  09 "MyJailbreak - Arms Race" (Beta 14.0-58f4b42) by shanapu
  10 "MyJailbreak - Custom Menu items" (Beta 14.0-58f4b42) by shanapu
  11 "MyJailbreak - Catch & Freeze" (Beta 14.0-58f4b42) by shanapu
  12 "MyJailbreak - Ratio" (Beta 14.0-58f4b42) by shanapu, Addicted
  13 "MyJailbreak - Menus" (Beta 14.0-58f4b42) by shanapu
  14 "MyJailbreak - Core" (Beta 14.0-58f4b42) by shanapu
  15 "MyJailbreak - Wardens Freeday Support for Zephyrus Store" (Beta 14.0-58f4b42) by shanapu
  16 "MyJailbreak - KnifeFight" (Beta 14.0-58f4b42) by shanapu
  17 "MyJailbreak - Warden" (Beta 14.0-58f4b42) by shanapu
  18 "MyJailbreak - Ratio - CT Ban Support - Databomb" (Beta 14.0-58f4b42) by shanapu, Addicted, good_live
  19 "MyJailbreak - Freeday" (Beta 14.0-58f4b42) by shanapu
  20 "MyJailbreak - DealDamage" (Beta 14.0-58f4b42) by shanapu
  21 "MyJailbreak - Torch Relay" (Beta 14.0-58f4b42) by shanapu
  22 "MyJailbreak - HE Battle" (Beta 14.0-58f4b42) by shanapu
  23 "MyJailbreak - PlayerTags" (Beta 14.0-58f4b42) by shanapu
  24 "MyJailbreak - DuckHunt" (Beta 14.0-58f4b42) by shanapu
  25 "MyJailbreak - Icons" (Beta 14.0-58f4b42) by shanapu
  26 "MyJailbreak - Drunk" (Beta 14.0-58f4b42) by shanapu
  27 "MyJailbreak - OneInTheChamber" (Beta 14.0-58f4b42) by Hexah | shanapu
  28 "MyJailbreak - Wardens Paperclips Support for Zephyrus Store" (Beta 14.0-58f4b42) by shanapu
  29 "MyJailbreak - Zeus" (Beta 14.0-58f4b42) by shanapu
  30 "MyJailbreak - Weapons" (Beta 14.0-58f4b42) by shanapu
  31 "MyJailbreak - Zombie" (Beta 14.0-58f4b42) by shanapu
  32 "MyJailbreak - War" (Beta 14.0-58f4b42) by shanapu
  33 "MyJailbreak - War FFA" (Beta 14.0-58f4b42) by shanapu
  34 "MyJailbreak - Ghosts War" (Beta 14.0-58f4b42) by shanapu
  35 "MyJailbreak - Last Guard Rule" (Beta 14.0-58f4b42) by shanapu
  36 "MyJailbreak - Player HUD" (Beta 14.0-58f4b42) by shanapu
  37 "MyJailbreak - CowBoy" (Beta 14.0-58f4b42) by shanapu
  38 "Admin Menu" (1.9.0.6261) by AlliedModders LLC
  39 "Player-Teleport by Dr. HyperKiLLeR" (1.2.0.0) by Dr. HyperKiLLeR
  40 "Admin Help" (1.9.0.6261) by AlliedModders LLC
  41 "SwapTeam" (1.2.6) by Rogue - Originally by MistaGee
  42 "Fun Commands" (1.9.0.6261) by AlliedModders LLC
  43 "Smart Jail Doors" (0.5.2-beta) by Maxim 'Kailo' Telezhenko
  44 "SM Parachute" (2.5) by SWAT_88
  45 "MapChooser" (1.9.0.6261) by AlliedModders LLC
  46 "SQL Admin Manager" (1.9.0.6261) by AlliedModders LLC
  47 "Map Nominations" (1.9.0.6261) by AlliedModders LLC
  48 "SM_Hosties v2" (2.2.3) by databomb & dataviruset & comando
  49 "SM Jail Teams" (1.0.3) by Elad Nava
  50 "Store" (1.2-dev) by Zephyrus
  51 "Chat-Processor" (2.1.5) by Keith Warren (Shaders Allen)
  52 "Sound Commands" (1.9.0.6261) by AlliedModders LLC
  53 "Client Preferences" (1.9.0.6261) by AlliedModders LLC
  54 "MOTDgd Adverts" (3.0.1) by Blackglade, Ixel and Zephyrus
  55 "SQL Admins (Prefetch)" (1.9.0.6261) by AlliedModders LLC
  56 "Suicide Bomber" (1.04) by Invex | Byte
  57 "Basic Commands" (1.9.0.6261) by AlliedModders LLC
  58 "Button Watcher" (2.0) by Franc1sco franug
  59 "CT Ban" (2.0.3) by databomb
  60 "Basic Info Triggers" (1.9.0.6261) by AlliedModders LLC
  61 "Basic Ban Commands" (1.9.0.6261) by AlliedModders LLC
  62 "Player Commands" (1.9.0.6261) by AlliedModders LLC
  63 "Basic Comm Control" (1.9.0.6261) by AlliedModders LLC
  64 "Reserved Slots" (1.9.0.6261) by AlliedModders LLC
  65 "Thirdperson | Mirrow Mode" (1.11) by Zephyrus
  66 "Store - Trade System" (1.0) by Zephyrus
  67 "Basic Votes" (1.9.0.6261) by AlliedModders LLC
  68 "SM Most Active" (2.6) by Franc1sco Steam: franug / shanapu
  69 "Rock The Vote" (1.9.0.6261) by AlliedModders LLC
  70 "Anti-Flood" (1.9.0.6261) by AlliedModders LLC

Running on latest version of Sourcemod and Metamod

**Comment by Hexer10** [comment]
What happens if you try to start manually an event? Does it start?

**Comment by shanapu** [comment]
You talk about "warden menu & Admins", does the other eventday voting menus (terror & ct) show the eventsdays?
Do you use the default values in Menu.cfg? Do you edited `configs/MyJailbreak/sorting_events.ini ` ?
I was ill and busy last weeks. I do more research these days.

**Comment by Garlicvideos** [comment]
All eventday voting menus do not show up. It occasionally does, on certain server boots, even though nothing has been changed, but 90% of the time it does not.

sorting_events.ini has not been edited.
Menu.cfg has been edited, but the cvars for event days are enabled.

> // 0 - disabled, 1 - enable set eventdays menu
// -
// Default: "1"
// Minimum: "0.000000"
// Maximum: "1.000000"
sm_menu_setdays "1"

// 0 - disabled, 1 - enable vote eventdays menu
// -
// Default: "1"
// Minimum: "0.000000"
// Maximum: "1.000000"
sm_menu_votedays "1"

My serverlanguage is english in core.cfg.

Thanks for taking time to help me out, I really appreciate it. Hope we can find the cause of the problem.

**Comment by Hexer10** [comment]
I've tested it in my server and I can see all the events.
`sm_admin` -> `MyJailBreak` -> `Set event days`.
Do you admins have the root flags? / The right flag to set the events?

**Comment by Garlicvideos** [comment]
Yea, I have the z flag. The issue occurs server-wide. If one person doesn't have it, no one else does.

**Comment by shanapu** [comment]
When you say It happens after boot, is it 'fixed' after a mapchange?

When you open the menu, does you see the Title and/or the exit/back button? Is there an empty menu or no menu?

When you start an evenday voting with command `!voteday` and cvar `"sm_menu_vote_noevent 1"  "0 - disabled, 1 - allow player vote for 'no Event Day' on eventday voting"`, do you see the "No Event Day" button?

Can't reproduce... ...I'm out of ideas.

Just to let you know how this part works, maybe you have an idea:

1. All plugins started/loaded
2. OnConfigsExecuted - eventdays "register" to core
2.5. When evenday register to core the order will be compared with the `sorting_events.ini`

3. when opening a eventday menu - menu.smx receive the eventdays in order to display in menu.

Maybe to find the issue we could add some debug messages and some debug commands to force register or output an eventdayslist.
