### ISSUE TITLE
Menu for warden, prisons and sm_eventdays  don t work 

### ISSUE THREAD

**Issue by GoDzIlLa15** [shanapu/MyJailbreak#321]
![untitled](https://user-images.githubusercontent.com/38585535/50428037-2cccbd80-08bc-11e9-869e-0b0f394a2e08.png)
!menu command don t work and  is activated in menu.cfg in myjailbreak.cfg 
![untitled](https://user-images.githubusercontent.com/38585535/50451964-f6d11d00-093f-11e9-8107-b584e7e71e1b.png)

**Comment by shanapu** [comment]
Without any infos, I can't help you. 
Please provide an full error log and also take a look here: https://github.com/shanapu/MyJailbreak/wiki/Frequently-Asked-Questions#what-should-i-consider-if-i-open-a-issue-or-post-on-forum
