### ISSUE TITLE
Warden and Weapon crash

### ISSUE THREAD

**Issue by xp2000csgo** [shanapu/MyJailbreak#329]
Good evening. After the last new thing of yours the fashion all the same appears краш all plug-ins.
Writes to error logs seldom, such mistake:
```
L 01/05/2019 - 21:06:41: SourceMod error session started
L 01/05/2019 - 21:06:41: Info (map "jb_mario_rescue_v1_2") (file "errors_20190105.log")
L 01/05/2019 - 21:06:41: [SM] Exception reported: Client 16 is not in game
L 01/05/2019 - 21:06:41: [SM] Blaming: MyJailbreak\weapons.smx
L 01/05/2019 - 21:06:41: [SM] Call stack trace: 
L 01/05/2019 - 21:06:41: [SM]   [0] GetClientTeam
L 01/05/2019 - 21:06:41: [SM]   [1] Line 1007, addons/sourcemod/scripting/MyJailbreak/weapons.sp::Timer_Fix
```
Generally when all plug-ins fly, I try to register team via the console: sm plugins list and me gives such error message:

``` MyJailbreak\warden.smx (MyJailbreak - Warden): Error detected in plugin startup (see error logs)```

plugins list:

> Listing 80 plugins:
>            01 "Admin File Reader" (1.9.0.6269) by AlliedModders LLC
>            02 "Admin List" (1.2) by Fredd
>            03 "Anti-Flood" (1.9.0.6269) by AlliedModders LLC
>            04 "[CHAT] AnyChatFilter" (1.1.5) by Skeriiz
>            05 "BanId Fix" (0.5) by SM9();
>            06 "Basic Chat" (1.9.0.6269) by AlliedModders LLC
>            07 "Basic Commands" (1.9.0.6269) by AlliedModders LLC
>            08 "Basic Info Triggers" (1.9.0.6269) by AlliedModders LLC
>            09 "Basic Votes" (1.9.0.6269) by AlliedModders LLC
>            10 "Блокирование sm plugins" (1.1) by Pheonix (????Феникс????)
>            11 "[CS:GO] ChatSpy" (1337) by ESK0
>            12 "Client Preferences" (1.9.0.6269) by AlliedModders LLC
>            13 "Flashlight" (1.3.63) by Mitch
>            14 "Custom Player Skins (Core)" (1.4) by Mitchell, Root
>            15 "GameVoting" (1.8.8) by Neatek
>            16 "Hook Grab Rope Limit Use" (1.0) by Sheepdude
>            17 "Hook Grab Rope Min/Max Distance" (1.0) by Sheepdude
>            18 "Hook Grab Rope" (1.1.4) by Sheepdude, SumGuy14
>            19 "[Keys] Core" (1.4) by R1KO
>            20 "[Keys] VIP" (1.3) by R1KO
>            21 "MapChooser" (1.9.0.6269) by AlliedModders LLC
>            22 "Material Admin" (0.7.7) by Material Admin Dev Team
>            23 "Admin Menu" (0.7.7) by AlliedModders LLC
>            24 "Basic Comm Control" (0.7.7) by AlliedModders LLC
>            25 "Material Admin Checker" (0.7.7) by psychonic, Ca$h Munny, Sarabveer(VEER™)
>            26 "MyJailbreak - Arms Race" (Beta 14.1.dev-0e7ffe4) by shanapu
>            27 "MyJailbreak - Catch & Freeze" (Beta 14.1.dev-0e7ffe4) by shanapu
>            28 "MyJailbreak - CowBoy" (Beta 14.1.dev-0e7ffe4) by shanapu
>            29 "MyJailbreak - DealDamage" (Beta 14.1.dev-0e7ffe4) by shanapu
>            30 "MyJailbreak - Drunk" (Beta 14.1.dev-0e7ffe4) by shanapu
>            31 "MyJailbreak - DuckHunt" (Beta 14.1.dev-0e7ffe4) by shanapu
>            32 "MyJailbreak - War FFA" (Beta 14.1.dev-0e7ffe4) by shanapu
>            33 "MyJailbreak - Freeday" (Beta 14.1.dev-0e7ffe4) by shanapu
>            34 "MyJailbreak - Ghosts War" (Beta 14.1.dev-0e7ffe4) by shanapu
>            35 "MyJailbreak - HE Battle" (Beta 14.1.dev-0e7ffe4) by shanapu
>            36 "MyJailbreak - HideInTheDark" (Beta 14.1.dev-0e7ffe4) by shanapu
>            37 "MyJailbreak - Player HUD" (Beta 14.1.dev-0e7ffe4) by shanapu
>            38 "MyJailbreak - Icons" (Beta 14.1.dev-0e7ffe4) by shanapu
>            39 "MyJailbreak - KnifeFight" (Beta 14.1.dev-0e7ffe4) by shanapu
>            40 "MyJailbreak - Last Guard Rule" (Beta 14.1.dev-0e7ffe4) by shanapu
>            41 "MyJailbreak - Menus" (Beta 14.1.dev-0e7ffe4) by shanapu
>            42 "MyJailbreak - Core" (Beta 14.1.dev-0e7ffe4) by shanapu
>            43 "MyJailbreak - NoScope" (Beta 14.1.dev-0e7ffe4) by shanapu
>            44 "MyJailbreak - OneInTheChamber" (Beta 14.1.dev-0e7ffe4) by Hexah | shanapu
>            45 "MyJailbreak - PlayerTags" (Beta 14.1.dev-0e7ffe4) by shanapu
>            46 "MyJailbreak - Ratio" (Beta 14.1.dev-0e7ffe4) by shanapu, Addicted
>            47 "MyJailbreak - Request" (Beta 14.1.dev-0e7ffe4) by shanapu
>            48 "MyJailbreak - Suicide Bomber" (Beta 14.1.dev-0e7ffe4) by shanapu
>            49 "MyJailbreak - Teleport War" (Beta 14.1.dev-0e7ffe4) by shanapu
>            50 "MyJailbreak - Torch Relay" (Beta 14.1.dev-0e7ffe4) by shanapu
>            51 "MyJailbreak - War" (Beta 14.1.dev-0e7ffe4) by shanapu
>            52 "MyJailbreak - Warden" (Beta 14.1.dev-0e7ffe4) by shanapu
>            53 "MyJailbreak - Weapons" (Beta 14.1.dev-0e7ffe4) by shanapu
>            54 "MyJailbreak - Zeus" (Beta 14.1.dev-0e7ffe4) by shanapu
>            55 "MyJailbreak - Zombie" (Beta 14.1.dev-0e7ffe4) by shanapu
>            56 "Nextmap" (1.9.0.6269) by AlliedModders LLC
>            57 "Map Nominations" (1.9.0.6269) by AlliedModders LLC
>            58 "No Prime Manager" (1.1.5) by OkyHp
>            59 "Реклама" (1.4) by Pheonix (????Феникс????)
>            60 "Reserved Slots" (1.9.0.6269) by AlliedModders LLC
>            61 "Rock The Vote" (1.9.0.6269) by AlliedModders LLC
>            62 "Simple Chat Processor (Redux)" (1.1.5) by Simple Plugins, Mini
>            63 "SM File/Folder Downloader and Precacher" (1.4) by SWAT_88
>            64 "SM_Hosties v2" (2.3.0) by databomb & dataviruset & comando
>            65 "Sound Commands" (1.9.0.6269) by AlliedModders LLC
>            66 "SourceTV / GOTV Protector" (1.0) by CrazyHackGUT aka Kruzya
>            67 "SuperAdminka" (1.5.2) by Grey™
>            68 "Terrible Enable Full Alltalk" (0.02) by Sheepdude
>            69 "[VIP] Admin" (1.0.0) by R1KO
>            70 "[VIP] AURA" (1.0.1) by R1KO & Pheonix (????Феникс????)
>            71 "[VIP] Base Functions" (1.2) by R1KO (skype: vova.andrienko1)
>            72 "[VIP] Bhop" (1.0.1) by KOROVKA
>            73 "[VIP] CHAT (+scp)" (3.1.1) by R1KO
>            74 "[VIP] Core" (2.1.1 R) by R1KO (skype: vova.andrienko1)
>            75 "[VIP] Endurance" (1.0.0) by R1KO (skype: vova.andrienko1)
>            76 "[VIP] Keys" (1.0.2) by R1KO (skype: vova.andrienko1)
>            77 "[VIP] Spawn Effects" (1.2) by Mr.ToNik
>            78 "[VIP] Tag" (1.1) by R1KO
>            79 "[VIP] Test" (1.0.3) by R1KO (skype: vova.andrienko1)
>            80 "VoiceAnnounceEx" (2.2.0) by Franc1sco franug, Mini and GoD-Tony

meta list:
```
           [01] SourceMod (1.9.0.6269) by AlliedModders LLC
           [02] CS Tools (1.9.0.6269) by AlliedModders LLC
           [03] SDK Tools (1.9.0.6269) by AlliedModders LLC
           [04] PTaH (P Tools and Hooks) (1.0.9) by Phoenix (????Ôåíèêñ????)
           [05] SDK Hooks (1.9.0.6269) by AlliedModders LLC
           [06] SteamWorks Extension (1.2.3) by Kyle Sanderson
           [07] DHooks (2.2.0) by Dr!fter
```

Plug-ins fly on again put maps
Help to understand please. Any more I have no information to provide.

**Comment by shanapu** [comment]
I finally fixed the weapons.smx error (`Client x is not in game`).

you say:
`MyJailbreak\warden.smx (MyJailbreak - Warden): Error detected in plugin startup (see error logs)`

but you also say:
`52 "MyJailbreak - Warden" (Beta 14.1.dev-0e7ffe4) by shanapu`

both at same time is iirc not possible. 

If it says `(MyJailbreak - Warden): Error detected in plugin startup (see error logs)` there **MUST BE** an entry for `warden.smx` in your `./addons/sourcemod/logs/errorxxxxxxx.log` file

I don't understand if you just got that error or if your server crash. 
When you server crash please provide a crash log.
**And tell us why you think this crash come from myjailbreak & explain us what to do to reproduce this crash on our server.**

Maybe disable a bunch of plugins, test for a day and disabled more plugins until you find the one plugin causing this issue for you.

**Comment by xp2000csgo** [comment]
> you say:
> MyJailbreak\warden.smx (MyJailbreak - Warden): Error detected in plugin startup (see error logs)
> 
> but you also say:
> 52 "MyJailbreak - Warden" (Beta 14.1.dev-0e7ffe4) by shanapu
> 

It at different times was!

**Comment by Hexer10** [comment]
What do you mean? You get that error only sometimes? 

If you do (or not) when you get that please check the error log and post it, making sure to copy the Warden error.

**Comment by xp2000csgo** [comment]
This mistake every day and in the course of the day several times.
I threw off plugins list how the server was restarted.

**Comment by shanapu** [comment]
>  there MUST BE an entry for warden.smx in your ./addons/sourcemod/logs/errorxxxxxxx.log file
> 
> I don't understand if you just got that error or if your server crash.
> When you server crash please provide a crash log.
> And tell us why you think this crash come from myjailbreak & explain us what to do to reproduce this crash on our server.
> 
> Maybe disable a bunch of plugins, test for a day and disabled more plugins until you find the one plugin causing this issue for you.

**Comment by xp2000csgo** [comment]
> L 01/20/2019 - 16:21:24: [SM] Exception reported: Handle 196408c2 is invalid (error 1)
> L 01/20/2019 - 16:21:24: [SM] Blaming: MyJailbreak\request.smx
> L 01/20/2019 - 16:21:24: [SM] Call stack trace:
> L 01/20/2019 - 16:21:24: [SM]   [0] CloseHandle
> L 01/20/2019 - 16:21:24: [SM]   [1] Line 169, addons/sourcemod/scripting/MyJailbreak/MyJailbreak/Modules/Request/capitulation.sp::Capitulation_Event_RoundStart

next error
