### ISSUE TITLE
VPhysics crashes using warden !noblock? 

### ISSUE THREAD

**Issue by nanociaglia** [shanapu/MyJailbreak#331]
First of all, no error logs, no console errors, last sm stable build.
I'm getting vphysics.dll crashes randomly, not always, but i've noticed that the last console messages printed are about people typing !noblock, after that the server crash.
This is the crash URL
https://crash.limetech.org/2jhvljdaeuwr
I've +4 crashes like that. 
And this is the image of the last console messages (multiple images on imgur)
https://imgur.com/a/8S5mScb

**Comment by nanociaglia** [comment]
Another crash after using !noblock
https://crash.limetech.org/md2cqmuw7ymx

```
62050 | 6572.312426 | duzz: !noblock
-- | -- | --
62051 | 6572.312533 | L 01/07/2019 - 19:22:58: "duzz<170><STEAM_1:0:426955999><CT>" say "!noblock"
```

**Comment by nanociaglia** [comment]
i made a basic plugin that allow warden to use !noblock to enable and !block to disable it.
Also my plugin deactivate the active noblock at the end of the round. Tell me if you wanna look it

**Comment by Franc1sco** [comment]
I will merge the improvements that i made related with noblock in myjailbreak server for prevent these crashes and more.

**Comment by Hexer10** [comment]
When it happens? When you toggle the `noblock` `on` or `off`?

**Comment by nanociaglia** [comment]
when you toggle it off and last myjb version

**Comment by shanapu** [comment]
since I/we cannot reproduce this crash some more information would be helpful.

At first a full "sm plugins list" server console output like Hexer10 already asked you.
Your "sm exts list", "sm version" and OS. 

If I read the crash trace the right way, the trace goes through the `void OnGameFrame()` Forward https://github.com/alliedmodders/sourcemod/blob/ff935b4707c665d160812e67a33a4cfca72029a0/core/sourcemod.cpp#L54 which is not used by MyJB noblock at all.

**Comment by nanociaglia** [comment]
You can see all info here
https://forums.alliedmods.net/showpost.php?p=2632295&postcount=9
Im using the last sm stable build on Windows
By the way, i made a toggeable noblock command that you can see if you want:
!noblock to activate
!block to deactivate
!forcenoblock for admins
And also the block command is executed automatically at the end of the round if the round ends with noblock activated. If you want to see the code just tell me

**Comment by shanapu** [comment]
Please check if this problem still occurs if you are running Sourcemod and Myjailbreak only and have disabled all other third-party plugins.

**Comment by nanociaglia** [comment]
i tried it, and happened again 
https://crash.limetech.org/77eten6p42q5

**Comment by nanociaglia** [comment]
I didn't have any problem like that since i've disabled your noblock function, look at the image, the last vphysics crash was 4 days ago
https://i.imgur.com/7eyiIVm.png

**Comment by nanociaglia** [comment]
I was using my noblock plugin and it crashed too with the same reason today. So there's a problem with the collisions in csgo maybe?

**Comment by shanapu** [comment]
maybe...
if so best would be contract sourcemod devs and/or valve devs and file a bug with all details of the environment and an example script to reproduce this crash.

Had you set up a new clean server in the meantime? 'cause I still cannot reproduce this with myjbs warden noblock on windows server...

**Comment by nanociaglia** [comment]
Sorry i just came back from my vacations. I've tested it in a clean server and this error still happening :)

**Comment by nanociaglia** [comment]
Fixed, you should force this cvar mp_solid_teammates to 0 to enable noblock and the server won't crash
