### ISSUE TITLE
[BUG] myjailbreak_teamgames

### ISSUE THREAD

**Issue by 1DreaM1** [shanapu/MyJailbreak#337]
# Describe the bug
When I enable myjailbreak_teamgames.smx
Every round is tg_cvar_friendlyfire 1, also when eventday is not running.

My cfg settings ->

> / 0 = do nothing "mp_friendlyfire"
> // 1 = set "mp_friendlyfire 1" every map start (after configs are loaded)
> // 2 = set "mp_friendlyfire 1" when game is in progress and set "mp_friendlyfire 0" otherwise.
> // -
> // Default: "1"
> tg_cvar_friendlyfire "2"

# Screenshot

![screenshot](https://overgame.eu/img/csgo.png)

# Logs
No logs showing.

# Environment
  * Operating System:  Linux
  * Current SourceMod version: latest - 1.9
  * Current Metamod: Source snapshot version: latest - 1.10
  * Current MyJailBreak version: latest - 9/1/19

**Comment by 1DreaM1** [comment]
Something new ?

**Comment by shanapu** [comment]
What version of TeamGames are you using?

**Comment by 1DreaM1** [comment]
// major.minor.patch.build
#define _PLUGIN_VERSION "1.1.0.7"

**Comment by shanapu** [comment]
sorry to say but I going to remove the support for teamgames within the update to sourcemod 1.10.
https://github.com/shanapu/MyJailbreak/issues/349#issuecomment-578468783
