### ISSUE TITLE
mod crash server [BUG] 

### ISSUE THREAD

**Issue by xp2000csgo** [shanapu/MyJailbreak#342]
L 05/29/2019 - 18:45:12: Info (map "jb_mist_v1") (file "errors_20190529.log")
L 05/29/2019 - 18:45:12: [SM] Exception reported: Invalid index 27 (count: 27)
L 05/29/2019 - 18:45:12: [SM] Blaming: MyJailbreak/armsrace.smx
L 05/29/2019 - 18:45:12: [SM] Call stack trace:
L 05/29/2019 - 18:45:12: [SM]   [0] GetArrayString
L 05/29/2019 - 18:45:12: [SM]   [1] Line 1228, MyJailbreak/armsrace.sp::Timer_Respawn

**Comment by Hexer10** [comment]
Please follow the issue template
