### ISSUE TITLE
Weapon drop bug 

### ISSUE THREAD

**Issue by ddfigueiras** [shanapu/MyJailbreak#343]
Hello, I installed the myjailbreak plugin, everything is correct but when one player kills another in the air, the weapons do not drop either with a knife or a weapon

**Comment by ddfigueiras** [comment]
"disableradar.smx" // Plugin
{
"type"	"plugin"
"action"	"load" // Load on eventday start, unload on eventday end



Can this be? If yes how to solve?

**Comment by ddfigueiras** [comment]
Or this
"sm_play @all weapons/party_horn_01.wav" // Command
{
"type"	"command" 
"action"	"execute" // execute server command on eventday start

**Comment by Hexer10** [comment]
Duplicated
