### ISSUE TITLE
[BUG] Remove Warden native is missing

### ISSUE THREAD

**Issue by rothadamcz** [shanapu/MyJailbreak#347]
# Logs
L 09/05/2019 - 20:46:52: [SM] Unable to load plugin "gamemenu.smx": Native "warden_remove" was not found

**Comment by rothadamcz** [comment]
Typo in warden.sp:
Native is called warden_removed

**Comment by Hexer10** [comment]
The typo is in the gamemenu plugin not in MyJailbreak.
