### ISSUE TITLE
!crowns[BUG] 

### ISSUE THREAD

**Issue by tivo123** [shanapu/MyJailbreak#350]
Console:

[Root] Tivo :  !crowns 500
Unknown command: play
Unknown command: sm_crowns`
Server connection timed out.

servewr console:

`L 10/22/2019 - 13:11:35: [SM] Blaming: mystore_gamble_crowns.smx
L 10/22/2019 - 13:11:35: [SM] Call stack trace:
L 10/22/2019 - 13:11:35: [SM]   [1] Line 452, addons/sourcemod/scripting/mystore_gamble_crowns.sp::Panel_RunAndWin
L 10/22/2019 - 13:11:35: [SM]   [2] Line 740, addons/sourcemod/scripting/mystore_gamble_crowns.sp::Timer_Run
L 10/22/2019 - 13:11:35: [SM]   [4] TriggerTimer
L 10/22/2019 - 13:11:35: [SM]   [5] Line 389, addons/sourcemod/scripting/mystore_gamble_crowns.sp::Start_Crowns
L 10/22/2019 - 13:11:35: [SM]   [6] Line 215, addons/sourcemod/scripting/mystore_gamble_crowns.sp::Command_Crowns
L 10/22/2019 - 13:11:35: [SM] Exception reported: Stack leak detected: sp:-22102536 should be 37204!
L 10/22/2019 - 13:11:36: [SM] Exception reported: Not enough space on the stack
L 10/22/2019 - 13:11:36: [SM] Exception reported: Not enough space on the stack
L 10/22/2019 - 13:11:36: [SM] Exception reported: Not enough space on the stack
L 10/22/2019 - 13:11:36: [SM] Exception reported: Not enough space on the stack`
YT: [https://youtu.be/pt-QOBa5FcM](url)

**Comment by Hexer10** [comment]
Please if you still have a problem open an issue in the MyStore repo and not here.
