### ISSUE TITLE
[Problem] ctbans doenst work 

### ISSUE THREAD

**Issue by Tene96** [shanapu/MyJailbreak#351]
L 12/15/2019 - 00:52:09: [SM] Unable to load plugin "ctbans.smx": Error detected in plugin startup (see error logs)
L 12/15/2019 - 00:52:09: [SM] Unable to load plugin "MyJailbreak\ratio_ctbans_addicted.smx": Native "CTBans_IsCTBanned" was not found

i connected this to database.cfg but nothing is working , what should i do ?

**Comment by Hexer10** [comment]
You are missing the main CTBan plugin in this case addicted version https://forums.alliedmods.net/showthread.php?p=2496711
