### ISSUE TITLE
[BUG] When using weapon spam in chat 

### ISSUE THREAD

**Issue by xFlume** [shanapu/MyJailbreak#352]
When i shoot with weapon\knife its spam in chat : 
Client : 1
Status : 0

here is a screenshot how its looks like : [https://imgur.com/a/ZlXWOoo](url)

**Comment by xFlume** [comment]
ok i cheked it and the problem found in teambans.smx its not on your jailbreak plugin but i will be happy if you will help me to disable this spam chat

**Comment by xFlume** [comment]
find the problem and i got one me question how can i disable the ct enter the commands and all and add to the server my votect plugin?

**Comment by Hexer10** [comment]
To disable to whole ratio just remove ratio.smx otherwise check the config to choose which features.

Please if you have issue with a plugin that is not MyJailbreak please ask to its creator and not here.
