### ISSUE TITLE
Not possible to translate

### ISSUE THREAD

**Issue by ziipen** [shanapu/MyJailbreak#354]
"Currently no warden" and "Prisoners" can not be translated. Could it possibly be changed? :-)
[https://i.imgur.com/SWyM7az.png](Imgur)

**Comment by shanapu** [comment]
This is possible.
https://github.com/shanapu/MyJailbreak/blob/dev/addons/sourcemod/translations/MyJailbreak.HUD.phrases.txt#L26-L39
http://translator.mitchdempsey.com/phrases/6391
http://translator.mitchdempsey.com/phrases/6393
please double check your translation files and language settings.
If still not works please tell me your server and client ´language.

**Comment by ziipen** [comment]
Thanks, my bad.
