### ISSUE TITLE
[BUG] Weapons menu broke

### ISSUE THREAD

**Issue by azalty** [shanapu/MyJailbreak#358]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Describe the bug
weapons broke since 1.10 compile:
(I still get my saved weapons but when we click on the menu or type !guns nothing happens)

# To Reproduce
--

# Logs
`L 01/30/2020 - 19:40:16: [SM] Exception reported: Menu handle 0 is invalid (error 4) L 01/30/2020 - 19:40:16: [SM] Blaming: MyJailbreak/weapons.smx L 01/30/2020 - 19:40:16: [SM] Call stack trace: L 01/30/2020 - 19:40:16: [SM] [0] DisplayMenu L 01/30/2020 - 19:40:16: [SM] [1] Line 839, addons/sourcemod/scripting/MyJailbreak/weapons.sp::Handler_BuildOptionsMenu`

# Environment
  * Operating System version: Linux (idk)
  * Current SourceMod version: 1.10.0.6460
  * Current Metamod: Source snapshot version: 1.10.7-dev
  * Current MyJailBreak version: Beta 14.1.dev-2990ea0
  - [ ] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens. 
  - [ ] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.
  - [x] I have update MyJailBreak to the [latest dev version](https://shanapu.de/MyJailBreak) and it still happens.

**Comment by Hathoute** [comment]
Please refer to this as I already fixed this issue:
https://forums.alliedmods.net/showpost.php?p=2687490&postcount=954
I hope the authors add this to their source code here.

**Comment by azalty** [comment]
> 
> 
> Please refer to this as I already fixed this issue:
> https://forums.alliedmods.net/showpost.php?p=2687490&postcount=954
> I hope the authors add this to their source code here.

Thanks my man <3

**Comment by Hexer10** [comment]
@Hathoute It would be nice if you could submit a pull request fixing this bug

**Comment by Hathoute** [comment]
Okay never mind I'm doing it.
