### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by ddfigueiras** [shanapu/MyJailbreak#361]
Please healp.. I look for help in many places no one did help... 
I have a cs go server, a jailbreak servers and it have a bug, every simple door, when it close, kills who are blocking...
I followed this tutorial https://forums.alliedmods.net/showthread.php?t=270279 maybe I did something wrong, can some one help?

**Comment by azalty** [comment]
This has nothing to do with myjb. Afaik it's because of your map.
