### ISSUE TITLE
Door kills when it close

### ISSUE THREAD

**Issue by ddfigueiras** [shanapu/MyJailbreak#363]
Please healp.. I look for help in many places no one did help...
I have a cs go server, a jailbreak servers and it have a bug, every simple door, when it close, kills who are blocking...
I followed this tutorial https://forums.alliedmods.net/showthread.php?t=270279 maybe I did something wrong, can some one help?

**Comment by Hexer10** [comment]
I'm sorry but this is not the place for asking general questions about how to make a server, please try asking in the sourcemod forum
