### ISSUE TITLE
[BUG] Warden plugin gets randomly disabled.

### ISSUE THREAD

**Issue by Beaast-exe** [shanapu/MyJailbreak#365]
# Help us help you
  - [*] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [*] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [*] I can always reproduce the issue with the provided description below.

# Describe the bug
The warden plugin gets disabled randomly when the warden kills any player.

# To Reproduce
1. Be warden
2. Kill anybody
3. After that your warden gets removed and plugin disabled, when using !warden again it returns "warden.smx is disabled."

# Logs
Provide here any logs, such as error logs, console logs or any other log that could be useful.

# Environment
  * Operating System version: Linux Ubuntu 18.04
  * Current SourceMod version: latest stable
  * Current Metamod: Source snapshot version: latest stable
  * Current MyJailBreak version: https://shanapu.de/MyJailBreak/  lateste dev
  - [*] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens. 
  - [*] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.
  - [*] I have update MyJailBreak to the [latest dev version](https://shanapu.de/MyJailBreak) and it still happens.  

# Screenshots

# Additional context

**Comment by Beaast-exe** [comment]
Now it is disabling on round start

**Comment by Hexer10** [comment]
Do you still have this issue? If so please send also the `sm plugins list` and your `warden.cfg`
