### ISSUE TITLE
[REQUEST] Questions when entering CT

### ISSUE THREAD

**Issue by cleber1337** [shanapu/MyJailbreak#367]
A good idea is to put a question system for players who enter the CT, if they answer correctly the Plugin lets him stay in the CT, if he misses the questions the plugin does not allow the player to enter the CT during the entire map.

This helps to not have players breaking Jailbreak rules easily

**Comment by WhyFaust** [comment]
It's been a long time since that's what you're carrying...
```
// How many question a player have to answer before join ct/queue. need sm_ratio_join_mode 2
// -
// Default: "3"
// Minimum: "1.000000"
// Maximum: "5.000000"
sm_ratio_questions "3"
```
