### ISSUE TITLE
Event Toggle Error

### ISSUE THREAD

**Issue by hartmanziga** [shanapu/MyJailbreak#369]
Need help to fix this Event toggle error that coming up all the time in error logs

> L 07/23/2020 - 15:02:57: [MyJailbreak/eventday_toggle.smx] ConVar 'sm_afk_enable' not found! Can't set default value '0' on Event Day end
L 07/23/2020 - 15:02:57: [eventday_toggle.smx] ConVar 'sm_afk_enable' not found! Can't set default value '0' on Event Day end

**Comment by Hexer10** [comment]
All you need to do is go in sourcemod/configs/eventday_toggle.cfg and remove this lines
```
	"sm_afk_enable" // ConVar
	{
		"type"			"convar" // type "convar", "command" or "plugin"
		"action"		"0" // On type "convar" - convar value while eventday
	}
```
