### ISSUE TITLE
Wiki overlays image settings missing

### ISSUE THREAD

**Issue by ghost** [shanapu/MyJailbreak#370]
The images found in the wiki custom overlays guide (https://github.com/shanapu/MyJailbreak/wiki/Custom-Overlays) are missing. Can you please add the image back into the guide if possible? The images I am referring to used to reside here.
http://shanapu.de/MyJailbreak/images/overlay1.jpg
http://shanapu.de/MyJailbreak/images/overlay2.jpg
http://shanapu.de/MyJailbreak/images/VTFEdit2.jpg

**Comment by shanapu** [comment]
done.

Am Fr., 4. Sept. 2020 um 21:50 Uhr schrieb ClydeSheldon <
notifications@github.com>:
