### ISSUE TITLE
Not disabled noblock

### ISSUE THREAD

**Issue by deff-dev** [shanapu/MyJailbreak#388]
Hello, i have problem, when i start DuckHunt noblock not disabled (players don't move when spawn,  they stoped at one pos).When i start ArmsRace round players players have collision (it's ok)
I use last dev version (MyJB-dev-2a6fa76)

**Comment by azalty** [comment]
Hi, thanks for your report!

shanapu isn't active anymore on sourcemod related projects nor Hexer, the other maintainer.

I started a fork of MyJailBreak in which I release unofficial fixes until a new maintainer is added.

I think I'm able to fix this bug, I'll take a look when I have some time.

Meanwhile, you can check my other patches here: https://github.com/azalty/MyJailbreak/releases

How it works: everything should be explained, but just download the latest official dev release if you don't already have it and then download my latest patch. Merge all files that match, and watch out if you had custom translations.

**Comment by deff-dev** [comment]
I use your fix. Now i fixed this bugs:
1. Bug with noblock
2. When print kill to console next round i don't shoot (i print kill when start timer to start game)

**Comment by azalty** [comment]
> Bug with noblock

How did you manage to fix it? With my patches?
Are you talking about this issue's bug?

> When print kill to console next round i don't shoot (i print kill when start timer to start game)

This is unrelated to my patch afaik, I didn't touch anything about that

**Comment by deff-dev** [comment]
i added check to noblock.sp
![image](https://user-images.githubusercontent.com/44276186/117766733-b2a4f580-b238-11eb-8f53-bc94b56dcaef.png)



This is unrelated to my patch afaik, I didn't touch anything about that
I know, but i fix this)
