### ISSUE TITLE
[BUG] Can't compile 3 files.

### ISSUE THREAD

**Issue by SprINt3R99** [shanapu/MyJailbreak#389]
I can't compile 3 files

//// warden.sp
//
// warden.sp(164) : fatal error 183: cannot read from file: "MyJailbreak/Modules/Warden/celldoors.sp"
//
// Compilation aborted.
// 1 Error.
//
// Compilation Time: 0,06 sec
// ----------------------------------------

//// request.sp
//
// request.sp(82) : fatal error 183: cannot read from file: "MyJailbreak/Modules/Request/refuse.sp"
//
// Compilation aborted.
// 1 Error.
//
// Compilation Time: 0,06 sec
// ----------------------------------------

//// myjailbreak.sp
//
// myjailbreak.sp(96) : fatal error 183: cannot read from file: "MyJailbreak/Modules/fog.sp"
//
// Compilation aborted.
// 1 Error.
//
// Compilation Time: 0,08 sec
// ----------------------------------------

At all files i change MyJailbreak folder name for mine "JailBreak-Planeta" and all files are compilet but that 3 not. How i can compile them?

**Comment by azalty** [comment]
Well, it's pretty obvious, you don't have those files.

Don't edit folder names, download the latest dev release

**Comment by SprINt3R99** [comment]
But i have this files this is weird
https://i.imgur.com/MYvie78.png
https://imgur.com/tDNBVVz.png

**Comment by azalty** [comment]
Make sure the directories are correct, and that these files are not currently being editted. Maybe it's just a permission/read issue.

**Comment by SprINt3R99** [comment]
Directories are wright, files aren't editting because i try compile them at local compilator

**Comment by SprINt3R99** [comment]
I am trying to compile on "fresh" files and the sam error

**Comment by azalty** [comment]
Everything compiles fine for me.
Did you correctly download from https://shanapu.de/MyJailbreak/ ?

I uploaded to you my little program to create test environments to avoid having a giant mess in my main scripting folder
[test_env_myjb_planeta.zip](https://github.com/shanapu/MyJailbreak/files/6496416/test_env_myjb_planeta.zip)

How it works:
- `_original` = contains scripting folder from the latest stable SM 1.10 (or the one from january 2021, you can probably update it but it shouldn't matter that much)
- `generate_test_env.bat` -> start and enter a suffix : it'll create a copy of `_original` with that name, simple stuff, you can just copy the original folder and it'll have the same effect. If you don't trust me, just delete this file 🤷 
- `test_env_myjailbreak_planeta` : I created a env for you where I put the latest dev version. It compiles fine for me and it should for you as well.

Note: UNZIP BEFORE USING!

**Comment by SprINt3R99** [comment]
I unzip that package, and everything is fine. I change for test i change folder names etc again and its work! :D

**Comment by azalty** [comment]
> I unzip that package, and everything is fine. I change for test i change folder names etc again and its work! :D

Well good to know then!
The best thing would be to understand what was the problem though but hey, if it works then it's great!

**Comment by SprINt3R99** [comment]
Thank you! :)
