### ISSUE TITLE
[BUG] Shot4Shot

### ISSUE THREAD

**Issue by WizardJailbreak** [shanapu/MyJailbreak#399]
Hi!
I have a problem with the plugin.
I want to disable shot4shot plugin because its buggy, but i dont know where i can.
Can you help me please?

Bug: When LR starts and either a prisoner or a guard shoots, he dies instantly.

**Comment by azalty** [comment]
That's the hosties plugin I think, not MyJB

**Comment by WizardJailbreak** [comment]
> That's the hosties plugin I think, not MyJB

Ohh,
Thanks.

**Comment by WizardJailbreak** [comment]
Btw you cant help me , its why have?

**Comment by azalty** [comment]
The hosties anticheat feature is bugged for some LRs, disable it for those LRs.

I've uploaded ENT_Hosties on GitHub, but it also has similar problems. It solves crashes related to tasers, but has other bugs.

Maybe one day we'll get a rewrite of hosties. Apparently one is on the way by another dev (check the AlliedModders thread for ENT_Hosties), although I've not seen any proof of work being actually done, so I can't confirm.

I might consider rewriting and fixing hosties myself in the future. For now I'm focusing with zephyrus store, MyJail* plugins, and my personal projects.

[The repo of the rewrite, currently empty](https://github.com/K4ryuu/Hosties-Karyuu)

**Comment by WizardJailbreak** [comment]
> The hosties anticheat feature is bugged for some LRs, disable it for those LRs.
> 
> I've uploaded ENT_Hosties on GitHub, but it also has similar problems. It solves crashes related to tasers, but has other bugs.
> 
> Maybe one day we'll get a rewrite of hosties. Apparently one is on the way by another dev (check the AlliedModders thread for ENT_Hosties), although I've not seen any proof of work being actually done, so I can't confirm.
> 
> I might consider rewriting and fixing hosties myself in the future. For now I'm focusing with zephyrus store, MyJail* plugins, and my personal projects.
> 
> [The repo of the rewrite, currently empty](https://github.com/K4ryuu/Hosties-Karyuu)

Hi
I downloaded this plugin today, and its really good!
Thank you!
