### ISSUE TITLE
when will you port this mod to source 2 engine (for Counter strike 2)

### ISSUE THREAD

**Issue by SGlickover** [shanapu/MyJailbreak#407]
are you developing it already? we are waiting for it so at least tell us if we should wait for it or not, thanks.

**Comment by azalty** [comment]
shanapu has stopped developping plugins

Source2Mod isn't available yet, so a port isn't going to be worked on until it releases. I might work on it, depending on the amount of work that has to be done.

**Comment by SGlickover** [comment]
> shanapu has stopped developping plugins
> 
> Source2Mod isn't available yet, so a port isn't going to be worked on until it releases. I might work on it, depending on the amount of work that has to be done.

thats cool, but can't you already do it with WIP or CS-Sharp? those are similar to sourcemod too (?)

**Comment by azalty** [comment]
> thats cool, but can't you already do it with WIP or CS-Sharp? those are similar to sourcemod too (?)

I don't know C# at all. I don't know CSSharp at all. MyJB is massive. Conclusion? It would take me a lot of time, which I don't have.

WIP?

Anyways, the little time I have will go towards learning CSSharp and developing private plugins for my servers to get them back running again in a simple state with the minimum amount of features. I'll focus on the rest later.

As Gaben once said "These things, they take time" (and then proceeded to create unregulated casino open to children, named "Case unboxing")
