### ISSUE TITLE
Shoot to push button

### ISSUE THREAD

**Issue by shanapu** [shanapu/MyJailbreak#48]
Maybe we can make this work, like it was in 1.6

**Comment by shanapu** [comment]
i find out that on some maps it already works to shoot buttons... 
i think its a map thing. i searched long time but cannot find a way to trigger a button by shooting. 

maybe someone got an idea

**Comment by good-live** [comment]
Should be possible to just set the flag on Map Start.
(SetEntProp(entity, Prop_Data, "m_fFlags", GetEntProp(entity, Prop_Data, "m_fFlags") | 512);)
https://developer.valvesoftware.com/wiki/Func_button

**Comment by devu4** [comment]
good-live, good idea but how would you get the button entity on map start? You would need to set this up like smartjaildoors. And instead of saving door ids, you would need a plugin to save cell button ids for each map. 

OR

Use FindEntityByClassname to loop through all func_buttons on map and add 512 flag to it.

I can try make this and test it. 2nd method is easier but less efficient.

**Comment by good-live** [comment]
Idk how smartjaildoors is handling it, but there is nothing bad about using FindEntityByClassname (and that would be also the way i would do it)

**Comment by devu4** [comment]
here works perfectly from testing.

`#include <sdktools>


//Compiler Options
#pragma semicolon 1
#pragma newdecls required

public Plugin myinfo = {
	name = "Shoot Buttons",
	author = "Denros",
	description = "Toggle buttons using gun",
	version = "1.0.0"
};

public void OnPluginStart() 
{ 
    HookEvent("round_start", round_start); 
} 

public Action round_start(Handle event, const char[] name, bool dontBroadcast) 
{ 
    int ent = -1; 
    while((ent = FindEntityByClassname(ent, "func_button")) != -1) 
    { 

		SetEntProp(ent, Prop_Data, "m_spawnflags", GetEntProp(ent, Prop_Data, "m_spawnflags")|512);
		
    } 
}`

**Comment by shanapu** [comment]
you guys are awesome!
tested your plugin on 3 maps, works like charm!

**Comment by shanapu** [comment]
THX again guys!
