### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by piotrekkrol7** [shanapu/MyJailbreak#5]
hi i have problem 
MyJailbreak/menu.smx (MyJailbreak - Menus): Native not found: warden_iswarden
MyJailbreak/zeus.smx (MyJailbreak - Zeus): Native not found: warden_iswarden
MyJailbreak/zombie.smx (MyJailbreak - Zombie): Native not found: warden_iswarden
MyJailbreak/ffa.smx (MyJailbreak - War FFA): Native not found: warden_iswarden
MyJailbreak/noscope.smx (MyJailbreak - NoScope): Native not found: warden_iswarden
MyJailbreak/drunk.smx (MyJailbreak - Drunk): Native not found: warden_iswarden
MyJailbreak/war.smx (MyJailbreak - War): Native not found: warden_iswarden
MyJailbreak/request.smx (MyJailbreak - Request): Library not found: lastrequest
MyJailbreak/torch.smx (MyJailbreak - Torch & OnTorch): Native not found: warden_iswarden
MyJailbreak/freeday.smx (MyJailbreak - Freeday): Native not found: warden_iswarden
MyJailbreak/weapons.smx (MyJailbreak - Weapons): Native not found: warden_iswarden
MyJailbreak/knife.smx (MyJailbreak - KnifeFight): Native not found: warden_iswarden
MyJailbreak/hide.smx (MyJailbreak - HideInTheDark): Native not found: warden_iswarden
MyJailbreak/suicide.smx (MyJailbreak - Suicide Bomber): Native not found: warden_iswarden
MyJailbreak/hebattle.smx (MyJailbreak - HEbattle): Native not found: warden_iswarden
MyJailbreak/warden.smx (MyJailbreak - Warden): Native "IsClientRebel" was not found
MyJailbreak/catch.smx (MyJailbreak - Catch & Freeze): Native "warden_iswarden" was not found
MyJailbreak/duckhunt.smx (MyJailbreak - DuckHunt): Native "warden_iswarden" was not found
MyJailbreak/playertags.smx (MyJailbreak - PlayerTags): Native "warden_iswarden" was not found
MyJailbreak/cowboy.smx (MyJailbreak - CowBoy): Native "warden_iswarden" was not found
warden.smx (Jailbreak Warden): unexpected error 23 in AskPluginLoad callback

**Comment by shanapu** [comment]
hi, first look - seems like you have two active warden plugins at same time. 
`warden.smx (Jailbreak Warden)` by ecca     
&
`MyJailbreak/warden.smx (MyJailbreak - Warden)` by shanapu (MyJailbreak)

move `sourcemod/plugins/warden.smx` to `sourcemod/plugins/disabled` and give it a try

**Comment by shanapu** [comment]
problem was missing sm_hosties and two warden plugins.
