### ISSUE TITLE
Add Voteday Menu cs 1.6 Style

### ISSUE THREAD

**Issue by devu4** [shanapu/MyJailbreak#50]
Love the plugin.

Instead of using command to vote for event days, would it be possible to introduce a voting menu.
For example, admins and VIP as warden can type !voteday and this opens up a menu for all players where they can vote for which day to be next round.

Vote menu lasts for 30 seconds and the most chosen event day is set next round. Obviously you can only start a !voteday every 3 rounds.

**Comment by shanapu** [comment]
nice idea. i like it. will work on this.

**Comment by shanapu** [comment]
https://github.com/shanapu/MyJailbreak/commit/7b583b99adc37db9243d9e0277c67f37b6e611fe
