### ISSUE TITLE
Eror BIG

### ISSUE THREAD

**Issue by mrkos9i4ok** [shanapu/MyJailbreak#51]
Crash after KMD ( commander ) makes suicide ( transition to another team , crashed and etc.

- [SM] Listing 101 plugins:
- 01 "Rock The Vote" (1.8.0.5915) by AlliedModders LLC
- 02 "Nextmap" (1.8.0.5915) by AlliedModders LLC
- 03 "SM File/Folder Downloader and Precacher" (1.4) by SWAT_88
- 04 "HostName Rus" (1.0.0) by GoDtm666
- 05 "[Shop] Long Jump" (1.3) by R1KO
- 06 "Admin File Reader" (1.8.0.5915) by AlliedModders LLC
- 07 "Smart Jail Doors" (0.6.0-beta) by Maxim 'Kailo' Telezhenko
- 08 "Disable HUD money" (1.0) by Pheonix (‰7Феникс7‰)
- 09 "Default SM Text Replacer" (0.32) by AZA AND MYARENA.RU
- 10 "Player Commands" (1.8.0.5915) by AlliedModders LLC
- 11 "Thirdperson Mode" (2.2) by Zephyrus & Justkasi
- 12 "Player models by flags" (1.2) by boomix
- 13 "Servers Hop" (1.0) by Нету
- 14 "[Shop] Money Distributor" (1.4.2) by FrozDark (HLModders LLC)
- 15 "[Shop] Laser Aim" (1.3) by Leonardo & White Wolf (HLModders LLC)
- 16 "RandomCycle" (1.8.0.5915) by AlliedModders LLC
- 17 "[Shop] Top10 Function" (2.0.1) by FrozDark
- 18 "HGR:Source" (2.1.5d) by SumGuy14 (Aka Soccerdude)
- 19 "CT Bans" (1.2.3) by FantoM
- 20 "Multiple player boost " (1.00) by boomix
- 21 "[Shop] Double Jump" (1.1) by R1KO
- 22 "Реклама" (1.2) by Pheonix (‰7Феникс7‰)
- 23 "Sound Commands" (1.8.0.5915) by AlliedModders LLC
- 24 "VoiceAnnounceEx" (2.1.0) by Franc1sco franug, Mini and GoD-Tony
- 25 "[Shop] Show You Credits [CS:GO]" (1.0) by L1GHT
- 26 "[CSGO] Team Limit Bypass" (1.1) by Zephyrus
- 27 "Web Shortcuts CS:GO version" (2.4) by Franc1sco franug and James "sslice" Gray
- 28 "SourceBans" (1.5.1) by SourceBans Development Team
- 29 "SM Voice Amount" (v1.4.1) by Franc1sco steam: franug
- 30 "Dissolve" (1.0.0.2) by L. Duke
- 31 "Jailbreak Team Balance" (3.0.8) by databomb and deadly-bullet.ru
- 32 "Jail: Causes Punishment Prisoner" (1.0.1) by AlmazON & Sahapro33 (Саша Шеин)
- 33 "Reserved Slots" (1.8.0.5915) by AlliedModders LLC
- 34 "Admin Help" (1.8.0.5915) by AlliedModders LLC
- 35 "[Shop] Logs" (1.1) by R1KO (skype: vova.andrienko1)
- 36 "Client Preferences" (1.8.0.5915) by AlliedModders LLC
- 37 "Rotate server graphic banners" (0.2) by HiTmAnY
- 38 "Basic Comm Control" (1.8.0.5915) by AlliedModders LLC
- 39 "Clean Chat" (1.1) by Monomizer
- 40 "[CS:GO] SpawnTools7" (1.0.1) by meng & IDDQD
- 41 "Custom Player Skins (Core)" (1.3.4) by Mitchell, Root
- 42 "connect_info_csgo.smx"
- 43 "[Shop] Skins" (2.0.22) by FrozDark (arms by R1KO)
- 44 "Basic Info Triggers" (1.8.0.5915) by AlliedModders LLC
- 45 "MyJailbreak - Last Guard Rule" (Beta 4.1) by shanapu
- 46 "MyJailbreak - Request" (Beta 4.1) by shanapu
- 47 "MyJailbreak - DealDamage" (Beta 4.1) by shanapu
- 48 "MyJailbreak - KnifeFight" (Beta 4.1) by shanapu
- 49 "MyJailbreak - DuckHunt" (Beta 4.1) by shanapu
- 50 "MyJailbreak - War FFA" (Beta 4.1) by shanapu
- 51 "MyJailbreak - Catch & Freeze" (Beta 4.1) by shanapu
- 52 "MyJailbreak - War" (Beta 4.1) by shanapu
- 53 "MyJailbreak - Weapons" (Beta 4.1) by shanapu, Franc1sco
- 54 "MyJailbreak - Suicide Bomber" (Beta 4.1) by shanapu
- 55 "MyJailbreak - Freeday" (Beta 4.1) by shanapu
- 56 "MyJailbreak - Zombie" (Beta 4.1) by shanapu
- 57 "MyJailbreak - Drunk" (Beta 4.1) by shanapu
- 58 "MyJailbreak - Zeus" (Beta 4.1) by shanapu
- 59 "MyJailbreak - NoScope" (Beta 4.1) by shanapu
- 60 "MyJailbreak - Warden" (Beta 4.1) by shanapu, ecca, ESKO & .#zipcore
- 61 "MyJailbreak - PlayerTags" (Beta 4.1) by shanapu
- 62 "MyJailbreak - HideInTheDark" (Beta 4.1) by shanapu
- 63 "MyJailbreak - CowBoy" (Beta 4.1) by shanapu
- 64 "MyJailbreak - HEbattle" (Beta 4.1) by shanapu
- 65 "MyJailbreak - Menus" (Beta 4.1) by shanapu, Franc1sco
- 66 "MyJailbreak - Torch & OnTorch" (Beta 4.1) by shanapu
- 67 "MyJailbreak - Core" (Beta 4.1) by shanapu
- 68 "Basic Commands" (1.8.0.5915) by AlliedModders LLC
- 69 "Simple Chat Processor (Redux)" (2.0.2) by Simple Plugins, Mini
- 70 "SM_Hosties v2" (2.2.1) by databomb & dataviruset & comando
- 71 "[Shop] Respawn" (1.1) by R1KO
- 72 "MapChooser" (1.8.0.5915) by AlliedModders LLC
- 73 "Team Names" (1.1) by Internet Bully
- 74 "Voice Comm" (2.2.1) by databomb
- 75 "[Shop] Aura" (1.2) by R1KO
- 76 "Map Nominations" (1.8.0.5915) by AlliedModders LLC
- 77 "[Shop] Medkit" (2.1.1) by FrozDark (HLModders LLC)
- 78 "CS:GO DEMO Crash Fix" (1.1.0) by Forever
- 79 "Welcome Sound" (1.0.1) by GoDtm666 (www.MyArena.ru)
- 80 "[Shop] Core" (2.0.22) by FrozDark
- 81 "Admin Menu" (1.8.0.5915) by AlliedModders LLC
- 82 "Basic Chat" (1.8.0.5915) by AlliedModders LLC
- 83 "[Shop] Pets" (1.0) by Pheonix & Zephyrus
- 84 "CsGoFlashlight_Sounds_135.smx" (1.3.5)
- 85 "Anti-Flood" (1.8.0.5915) by AlliedModders LLC
- 86 "SM Franug CSGO Sprays" (1.4.1) by Forever
- 87 "CS:GO Slots fix" (1.0.0) by www.MyArena.ru
- 88 "Basic Votes" (1.8.0.5915) by AlliedModders LLC
- 89 "[VIP] Test" (1.0.2) by R1KO (skype: vova.andrienko1)
- 90 "[VIP] Tag" (1.0.0) by R1KO
- 91 "[VIP] Regen HP" (1.0.4) by R1KO
- 92 "[VIP] Bhop" (1.0.0) by KOROVKA
- 93 "[VIP] Keys" (1.0.2) by R1KO (skype: vova.andrienko1)
- 94 "[VIP] Skins" (1.0.5) by R1KO (skype: vova.andrienko1)
- 95 "[VIP] Top Icon" (1.0.0) by R1KO
- 96 "[VIP] Admin Privileges" (1.0.2) by R1KO (skype: vova.andrienko1)
- 97 "[VIP] Kick" (1.0.1) by R1KO (skype: vova.andrienko1)
- 98 "[VIP] Throwing Knives" (1.0.5) by R1KO (original by meng, Bacardi)
- 99 "[VIP] Base Functions" (1.1.0) by R1KO (skype: vova.andrienko1)
- 100 "[VIP] Core" (2.0.0 R) by R1KO (skype: vova.andrienko1)
- 101 "SwapTeam" (1.2.6) by Rogue - Originally by MistaGee and www.MyArena.ru

**Comment by mrkos9i4ok** [comment]
[http://hlmod.ru/attachments/logs-rar.16575/](url)

**Comment by shanapu** [comment]
please post the logs directly here or on pastebin or any other... no rar pls

**Comment by mrkos9i4ok** [comment]
[errors_20160630.txt](https://github.com/shanapu/MyJailbreak/files/342018/errors_20160630.txt)

**Comment by shanapu** [comment]
sorry dude, but i can't click this link

**Comment by mrkos9i4ok** [comment]
Shanapu,logs for plugin did not say anything wrong , the server crash when someone dies (like CT )
That is rejoining the other Kamanda , from HR (hot potato and the like )

**Comment by mrkos9i4ok** [comment]
That used to be , but it seems this is not seen

L 06/30/2016 - 15:48:37: [SM] Blaming: MyJailbreak/torch.smx()
L 06/30/2016 - 15:48:37: [SM] Call stack trace:
L 06/30/2016 - 15:48:37: [SM]   [0] LogToFileEx
L 06/30/2016 - 15:48:37: [SM]   [1] Line 270, MyJailbreak/torch.sp::SetTorch()
L 06/30/2016 - 15:48:37: [SM]   [3] FakeClientCommand
L 06/30/2016 - 15:48:37: [SM]   [4] Line 1194, MyJailbreak/menu.sp::SetEventMenuHandler()

**Comment by mrkos9i4ok** [comment]
In my opinion it is connected with skins ct and T:

1. [SM] Listing 102 plugins:
2.   01 "Rock The Vote" (1.8.0.5915) by AlliedModders LLC
3.   02 "Nextmap" (1.8.0.5915) by AlliedModders LLC
4.   03 "HostName Rus" (1.0.0) by GoDtm666
5.   04 "[Shop] Long Jump" (1.3) by R1KO
6.   05 "Admin File Reader" (1.8.0.5915) by AlliedModders LLC
7.   06 "Smart Jail Doors" (0.6.0-beta) by Maxim 'Kailo' Telezhenko
8.   07 "Disable HUD money" (1.0) by Pheonix (‰7Феникс7‰)
9.   08 "Default SM Text Replacer" (0.32) by AZA AND MYARENA.RU
10.   09 "Player Commands" (1.8.0.5915) by AlliedModders LLC
11.   10 "Thirdperson Mode" (2.2) by Zephyrus & Justkasi
12.   11 "Player models by flags" (1.2) by boomix
13.   12 "[Shop] Money Distributor" (1.4.2) by FrozDark (HLModders LLC)
14.   13 "[Shop] Laser Aim" (1.3) by Leonardo & White Wolf (HLModders LLC)
15.   14 "RandomCycle" (1.8.0.5915) by AlliedModders LLC
16.   15 "[Shop] Top10 Function" (2.0.1) by FrozDark
17.   16 "HGR:Source" (2.1.5d) by SumGuy14 (Aka Soccerdude)
18.   17 "CT Bans" (1.2.3) by FantoM
19.   18 "Multiple player boost " (1.00) by boomix
20.   19 "[Shop] Double Jump" (1.1) by R1KO
21.   20 "Реклама" (1.2) by Pheonix (‰7Феникс7‰)
22.   21 "Sound Commands" (1.8.0.5915) by AlliedModders LLC
23.   22 "VoiceAnnounceEx" (2.1.0) by Franc1sco franug, Mini and GoD-Tony
24.   23 "[Shop] Show You Credits [CS:GO]" (1.0) by L1GHT
25.   24 "[CSGO] Team Limit Bypass" (1.1) by Zephyrus
26.   25 "Web Shortcuts CS:GO version" (2.4) by Franc1sco franug and James "sslice" Gray
27.   26 "SourceBans" (1.5.1) by SourceBans Development Team
28.   27 "SM Voice Amount" (v1.4.1) by Franc1sco steam: franug
29.   28 "Dissolve" (1.0.0.2) by L. Duke
30.   29 "Jailbreak Team Balance" (3.0.8) by databomb and deadly-bullet.ru
31.   30 "Jail: Causes Punishment Prisoner" (1.0.1) by AlmazON & Sahapro33 (Саша Шеин)
32.   31 "Reserved Slots" (1.8.0.5915) by AlliedModders LLC
33.   32 "Admin Help" (1.8.0.5915) by AlliedModders LLC
34.   33 "[Shop] Logs" (1.1) by R1KO (skype: vova.andrienko1)
35.   34 "Client Preferences" (1.8.0.5915) by AlliedModders LLC
36.   35 "Rotate server graphic banners" (0.2) by HiTmAnY
37.   36 "Basic Comm Control" (1.8.0.5915) by AlliedModders LLC
38.   37 "Clean Chat" (1.1) by Monomizer
39.   38 "[CS:GO] SpawnTools7" (1.0.1) by meng & IDDQD
40.   39 "Admin List" (1.2.0) by Fredd and www.MyArena.ru
41.   40 "Custom Player Skins (Core)" (1.3.4) by Mitchell, Root
42.   41 "connect_info_csgo.smx"
43.   42 "[Shop] Skins" (2.0.22) by FrozDark (arms by R1KO)
44.   43 "Basic Info Triggers" (1.8.0.5915) by AlliedModders LLC
45.   44 "MyJailbreak - Last Guard Rule" (Beta 4.1) by shanapu
46.   45 "MyJailbreak - Request" (Beta 4.1) by shanapu
47.   46 "MyJailbreak - DealDamage" (Beta 4.1) by shanapu
48.   47 "MyJailbreak - KnifeFight" (Beta 4.1) by shanapu
49.   48 "MyJailbreak - DuckHunt" (Beta 4.1) by shanapu
50.   49 "MyJailbreak - War FFA" (Beta 4.1) by shanapu
51.   50 "MyJailbreak - Catch & Freeze" (Beta 4.1) by shanapu
52.   51 "MyJailbreak - War" (Beta 4.1) by shanapu
53.   52 "MyJailbreak - Weapons" (Beta 4.1) by shanapu, Franc1sco
54.   53 "MyJailbreak - Suicide Bomber" (Beta 4.1) by shanapu
55.   54 "MyJailbreak - Freeday" (Beta 4.1) by shanapu
56.   55 "MyJailbreak - Zombie" (Beta 4.1) by shanapu
57.   56 "MyJailbreak - Drunk" (Beta 4.1) by shanapu
58.   57 "MyJailbreak - Zeus" (Beta 4.1) by shanapu
59.   58 "MyJailbreak - NoScope" (Beta 4.1) by shanapu
60.   59 "MyJailbreak - Warden" (Beta 4.1) by shanapu, ecca, ESKO & .#zipcore
61.   60 "MyJailbreak - PlayerTags" (Beta 4.1) by shanapu
62.   61 "MyJailbreak - HideInTheDark" (Beta 4.1) by shanapu
63.   62 "MyJailbreak - CowBoy" (Beta 4.1) by shanapu
64.   63 "MyJailbreak - HEbattle" (Beta 4.1) by shanapu
65.   64 "MyJailbreak - Menus" (Beta 4.1) by shanapu, Franc1sco
66.   65 "MyJailbreak - Torch & OnTorch" (Beta 4.1) by shanapu
67.   66 "MyJailbreak - Core" (Beta 4.1) by shanapu
68.   67 "Basic Commands" (1.8.0.5915) by AlliedModders LLC
69.   68 "Simple Chat Processor (Redux)" (2.0.2) by Simple Plugins, Mini
70.   69 "SM_Hosties v2" (2.2.1) by databomb & dataviruset & comando
71.   70 "[Shop] Respawn" (1.1) by R1KO
72.   71 "MapChooser" (1.8.0.5915) by AlliedModders LLC
73.   72 "Team Names" (1.1) by Internet Bully
74.   73 "Voice Comm" (2.2.1) by databomb
75.   74 "[Shop] Aura" (1.2) by R1KO
76.   75 "Map Nominations" (1.8.0.5915) by AlliedModders LLC
77.   76 "Player Cleaner" (1.0) by White Wolf (HLModders LLC)
78.   77 "[Shop] Medkit" (2.1.1) by FrozDark (HLModders LLC)
79.   78 "CS:GO DEMO Crash Fix" (1.1.0) by Forever
80.   79 "Welcome Sound" (1.0.1) by GoDtm666 (www.MyArena.ru)
81.   80 "[Shop] Core" (2.0.22) by FrozDark
82.   81 "Admin Menu" (1.8.0.5915) by AlliedModders LLC
83.   82 "Basic Chat" (1.8.0.5915) by AlliedModders LLC
84.   83 "[Shop] Pets" (1.0) by Pheonix & Zephyrus
85.   84 "CsGoFlashlight_Sounds_135.smx" (1.3.5)
86.   85 "Anti-Flood" (1.8.0.5915) by AlliedModders LLC
87.   86 "SM Franug CSGO Sprays" (1.4.1) by Forever
88.   87 "CS:GO Slots fix" (1.0.0) by www.MyArena.ru
89.   88 "PermaMute" (0.1) by Ryan "FLOOR_MASTER" Mannion
90.   89 "Basic Votes" (1.8.0.5915) by AlliedModders LLC
91.   90 "[VIP] Test" (1.0.3) by R1KO (skype: vova.andrienko1)
92.   91 "[VIP] Tag" (1.0.0) by R1KO
93.   92 "[VIP] Regen HP" (1.0.4) by R1KO
94.   93 "[VIP] Bhop" (1.0.0) by KOROVKA
95.   94 "[VIP] Keys" (1.0.2) by R1KO (skype: vova.andrienko1)
96.   95 "[VIP] Skins" (1.0.5) by R1KO (skype: vova.andrienko1)
97.   96 "[VIP] Top Icon" (1.0.0) by R1KO
98.   97 "[VIP] Admin Privileges" (1.0.2) by R1KO (skype: vova.andrienko1)
99.   98 "[VIP] Kick" (1.0.1) by R1KO (skype: vova.andrienko1)
100.   99 "[VIP] Throwing Knives" (1.0.5) by R1KO (original by meng, Bacardi)
101.   100 "[VIP] Base Functions" (1.1.0) by R1KO (skype: vova.andrienko1)
102.   101 "[VIP] Core" (2.0.0 R) by R1KO (skype: vova.andrienko1)
103.   102 "SwapTeam" (1.2.6) by Rogue - Originally by MistaGee and www.MyArena.ru

**Comment by shanapu** [comment]
> **s**hanapu,logs for plugin did not say anything wrong , the server crash when someone dies (like CT )
That is rejoining the other Kamanda , from LR (hot potato and the like )In my opinion it is connected with skins ct and T:
11 "Player models by flags" (1.2)
40 "Custom Player Skins (Core)

hi mrkos9i4ok,
MyJailbreak isn't known for 'random' server crashes. Maybe use this for more detailed sever crash report: https://forums.alliedmods.net/showthread.php?t=277703

You could test `sm_warden_model "0"` or disable `11 "Player models by flags" (1.2)` or move `zombie.smx & CustomPlayerSkins.smx` to disable folder and tell if the crashes also appear with crash report log.
And do you use hosties version 2.2.3 [(beta branch)](https://github.com/dataviruset/sm-hosties/tree/beta)

**Comment by mrkos9i4ok** [comment]
Crash ID: L3OE-Z2NA-BIJA

**Comment by mrkos9i4ok** [comment]
logs clear

**Comment by shanapu** [comment]
im sorry this crash seems for me nothing to do with myjb. Do you also had disable "Player models by flags" (1.2) and move zombie.smx & CustomPlayerSkins.smx to disable folder?
Do you disabled complete MyJB and does the crash still appears?

**Comment by mrkos9i4ok** [comment]
Shanapu,Huge sorry, this was due to a heavy load on the host , he just could not stand (a huge sorry for the trouble ) seems no longer ruin, server.

**Comment by mrkos9i4ok** [comment]
New question , the menu can be added as an item ( for example the last convict or shop menu

**Comment by mrkos9i4ok** [comment]
Thank,server don`t crush

**Comment by shanapu** [comment]
What/where was the Problem?
