### ISSUE TITLE
Not creating config file SM 1.8

### ISSUE THREAD

**Issue by ngx3** [shanapu/MyJailbreak#54]
MyJb isn't making a config file, with all the convars listed on alliedmods.

Only ratio.cfg and weapon.cfg are available. Eventdays folder is empty as well.

**Comment by shanapu** [comment]
take a look to your logs.... csgo/addons/sourcemod/logs
i bet there is the problem/solution

**Comment by shanapu** [comment]
i bet you forgot the required plugins (hosties)... no hosties -> warden wont load -> no warden no eventdays - > only plugins that doesnt required hosties/warden will load and generate cfg files -> ratio & weapon
