### ISSUE TITLE
Rules menu not fully displayed in "ru"

### ISSUE THREAD

**Issue by shanapu** [shanapu/MyJailbreak#55]
https://forums.alliedmods.net/showpost.php?p=2433223&postcount=141
Not all rules are displayed
![](http://i.imgur.com/wa4xSls.jpg)

**Comment by shanapu** [comment]
> The size of the Latin characters - 1 bytes, the size of the Cyrillic character - 2 bytes. In the message it fits in Latin characters twice.

**Comment by Include5** [comment]
Hello shanapu, i have one suggestion about rules menu, why you cant do several rules menu like make next,previous and exit button so then all russian text what are inside several rules menu will be correctly and all rules will be displayed with next,previous and exit method.

https://camo.githubusercontent.com/39dd5275a156294242c75c876faefe3a2ca61fd8/687474703a2f2f692e696d6775722e636f6d2f77613478536c732e6a7067

By Andy

**Comment by shanapu** [comment]
I understand , but I'm not sure if that is a good way. Sounds more like a workaround.
Is it hard for ru translation to shorten the text?
I prefer to find a solution for:
> Latin characters - 1 bytes, the size of the Cyrillic character - 2 bytes

**Comment by shanapu** [comment]
After longer research and talk with some other devs, I don't see a solution for this. This a an hardcoded valve issue.
I just see to shorten the text.

> why you cant do several rules menu like make next,previous and exit button

I'll keep that in mind if i really do a rewrite of MyJB(2?) sometime.
