### ISSUE TITLE
Ratio

### ISSUE THREAD

**Issue by mrkos9i4ok** [shanapu/MyJailbreak#58]
Players can not go for t \ ct
![20160706172011_1](https://cloud.githubusercontent.com/assets/20227450/16621344/8da58014-439e-11e6-8f25-2796103a8656.jpg)
LOGS:
> L 07/06/2016 - 15:27:49: [SM] Exception reported: Translation string formatted incorrectly - missing at least 1 parameters
> L 07/06/2016 - 15:27:49: [SM] Blaming: MyJailbreak/ratio.smx()
> L 07/06/2016 - 15:27:49: [SM] Call stack trace:
> L 07/06/2016 - 15:27:49: [SM]   [0] VFormat
> L 07/06/2016 - 15:27:49: [SM]   [1] Line 78, D:\Code\MyJailbreak\addons\sourcemod\scripting\include\colors.inc::CPrintToChat()
> L 07/06/2016 - 15:27:49: [SM]   [2] Line 199, MyJailbreak/ratio.sp::OnJoinTeam()

ratio.cfg

> // This file was auto-generated by AutoExecConfig read and append beta
> // ConVars for plugin "MyJailbreak/ratio.smx"
> 
> 
> // Set your custom chat command for become guard. no need for sm_ or !
> // -
> // Default: "gua"
> sm_ratio_cmd "guard"
> 
> // How many prisoners for each guard.
> // -
> // Default: "2"
> // Minimum: "1.000000"
> sm_ratio_T_per_CT "3"
> 
> // 0 - disabled, 1 - enable VIPs moved to front of queue
> // -
> // Default: "1"
> // Minimum: "0.000000"
> // Maximum: "1.000000"
> sm_ratio_flag "1"
> 
> // Set the flag for VIP
> // -
> // Default: "a"
> sm_ratio_vipflag "b"
> 
> // 0 - disabled, 1 - enable adverstiment for 'VIPs moved to front of queue' when player types !quard 
> // -
> // Default: "1"
> // Minimum: "0.000000"
> // Maximum: "1.000000"
> sm_ratio_adsvip "1"

**Comment by shanapu** [comment]
hi mrkos9i4ok,   please dont change the topic. make a new issue! thank you!

as you probably already know, the ClanTag bug coming from the Cyrillic letters... i dont know if we can fix this... so use shorter Tags.... i will make the "ru" Tags also shorter for myjb.

The ratio bug is fixed within next update. 
workaround delete line 20: **https://github.com/shanapu/MyJailbreak/commit/cc82c86a58975e989d69310c0393b862ef178acd**
