### ISSUE TITLE
warden rainbow colors

### ISSUE THREAD

**Issue by deven10** [shanapu/MyJailbreak#6]
Can you make an option so warden can flash all random colors?

Can you add a sound when there is the lastCT maybe this sound? https://dl.dropboxusercontent.com/u/17466145/lastctsound.mp3

And thank you for this plugin, Spices up jailbreak :)

**Comment by shanapu** [comment]
> Can you make an option so warden can flash all random colors?

do you mean warden is changing the colors continuous? So instead this?
```
sm_warden_color_enable: 0 - disabled, 1 - enable colored warden. Default 1
sm_warden_color_red - What color to turn the warden into (set R, G and B values to 0 to disable). Default 0
sm_warden_color_green - What color to turn the warden into (rGb): x - green value. Default 0
sm_warden_color_blue - What color to turn the warden into (rgB): x - blue value. Default 255
```

> Can you add a sound when there is the lastCT maybe this sound? https://dl.dropboxusercontent.com/u/17466145/lastctsound.mp3

A whole "Last Guard System" is coming with next updates.

**Comment by bchewy** [comment]
@shanapu he means the warden will change from red to blue and other colors every few seconds

**Comment by shanapu** [comment]
i had something like that on my todo. will come with futher updates.
