### ISSUE TITLE
Players stay frozen on some event days.

### ISSUE THREAD

**Issue by devu4** [shanapu/MyJailbreak#64]
I have found out that on some days the players stay frozen even after truce timer. For example on HE battle, players stay frozen after truce timer.

This also occurs with other event days too.

this is with dev 6.0 branch.

**Comment by shanapu** [comment]
Thx for the reports!!! I will hav a look tomorrow. Im on  holidays right now (EslOne yeah!!!). 

'''
also occurs with other event days too.'''
Could you tell me which days also hav this Problem?

**Comment by devu4** [comment]
From what I tested, it occurs on knifefight day too once you get it to start cause it doesn't work through !voteday.

**Comment by devu4** [comment]
BUG: CCSGameMovement::CheckParameters - too many stacking levels.
This is what it says in player console. It is the method you use to spawn people in armory. I think.

**Comment by shanapu** [comment]
> For example on HE battle, players stay frozen after truce timer.
> ... it occurs on knifefight day

hi devu4,
i'm a bit confused, cause both days HE battle & Knifefight don't have any Playerfreeze on trucetime.
On roundstart everyone can move. 
Maybe you run a plugin that set "solid players / player collision" or something on roundstart. 
That could result in stucking player and this error:
> BUG: CCSGameMovement::CheckParameters - too many stacking levels.

`

**Comment by shanapu** [comment]
damn, i just see i forgot 
`SetEntData(client, FindSendPropInfo("CBaseEntity", "m_CollisionGroup"), 2, 4, true);`

on round start on both days... thats why your players stucking. fix coming soon

**Comment by devu4** [comment]
Ok I understand, I have it set so players have collisions on my server. Best way might be to force no collisions on event days. Although you are right. Might be worth forcing for servers who want to use player collisions.

**Comment by shanapu** [comment]
>  I have it set so players have collisions on my server.
you can stay on your configs.

just pushed a fix. ready for testing.

**Comment by devu4** [comment]
Ok all good now thanks!
