### ISSUE TITLE
Make eventdays end for LR

### ISSUE THREAD

**Issue by devu4** [shanapu/MyJailbreak#67]
I think you should add a cvar for each eventday where you can chose to enable lr.
So if lr is enabled for event day then when lr is announced the day ends. This obviously wouldn't work for days such as catch and torch relay. But for days where players die, I would like to enabe lr. 

So basically on the last round of the day, lr is reenabled and day is disabled and ends when lr is announced.

**Comment by shanapu** [comment]
#68

**Comment by shanapu** [comment]
https://github.com/shanapu/MyJailbreak/commit/0366331133170234077e65901a75b24818661195
https://github.com/shanapu/MyJailbreak/commit/18c92dd877b080f24b450b60f85fe64fa579b8cd
done by devu4
much thanks!
