### ISSUE TITLE
Players Info HUD

### ISSUE THREAD

**Issue by shanapu** [shanapu/MyJailbreak#73]
A toggleable (configurable throu menu) info hud in center to display (maybe):

- warden name
- CT / Prisoners count
- Roundtime left
- Zeps/open store credits
- Ratio?
- HP 
- event day name
- more?

http://imgur.com/a/8wx15 by jacob

**Comment by shanapu** [comment]
https://github.com/shanapu/MyJailbreak/commit/88c6910f3b2f29acbfd466413893c8b6ca7e86d6

now:
- warden name
- CT / Prisoners count
- event day name (nextround/thisround)

is there need for: 
- Zeps/open store credits?
- Ratio?
- HP?
- more / any other ideas?

please comment!

**Comment by Include5** [comment]
> Zeps/open store credits?

wat?

> Ratio?
HP?


Yes, I think we need it

**Comment by shanapu** [comment]
show the credits of [Store by Zephyrus](https://forums.alliedmods.net/showthread.php?t=276677) or [(Open) Store](https://forums.alliedmods.net/forumdisplay.php?f=157) 

own HP? or HP of teammate you looking at? or for warden hp of prisoner?

**Comment by Include5** [comment]
> show the credits of Store by Zephyrus or (Open) Store

I use shop by frozdark

> own HP? or HP of teammate you looking at? or for warden hp of prisoner?

No, I think it is not necessary

>

**Comment by shanapu** [comment]
i decided that store cedits would be to much work to get all 3 stores working in one plugin. if anyone need this feature i will open a new branch for this stores.

Timeleft & HP is unnecessary.
