### ISSUE TITLE
warden counter: count terror in wardens Field of View

### ISSUE THREAD

**Issue by shanapu** [shanapu/MyJailbreak#76]
command to count all terrorist in a radius/or on field of view(cvar) around/of the the warden.

**Comment by Include5** [comment]
Really I am looking forward to this feature :)

**Comment by shanapu** [comment]
It's harder than i thought to use the warden field of view. At the moment I pause this. Maybe someone got an idea howto.

But i have i nicely working version of counter using clients in radius.

**Comment by good-live** [comment]
A check, whether there is a wall between them or not would be nice to prevent abuse.

**Comment by shanapu** [comment]
> A check, whether there is a wall between them or not would be nice to prevent abuse.

Also on count terror in wardens radius?  or only on wardens Field of View?

**Comment by good-live** [comment]
Also on radius. Currently youre able to just check if there's someone behind a Wall, when youre near enough.

**Comment by shanapu** [comment]
I've found a nice stock to check player sight. I will implement this next days

**Comment by shanapu** [comment]
ok, I got working count in Field of View with wall/obstacle check. Is there still a need for radius(with wall check) so I add a cvar? Or is radius unnecessary and can be replaced with fov?

**Comment by devu4** [comment]
I think if you add fov there will be no real need for radius. SO I say replace radius with fov.

**Comment by good-live** [comment]
Could get replaced.

**Comment by shanapu** [comment]
wrong reference...sry
