### ISSUE TITLE
Suggestion: Calculate eventdays healths

### ISSUE THREAD

**Issue by devu4** [shanapu/MyJailbreak#77]
For days such as Duckhunt and zombie make health depending on multipler. Current system of just giving a set hp is not fair. The health given should be on a (multipler x number of Ts )/ number of CTs.

For example on zombie day, if there are 10 Ts and 5 Cts and multipler set in cfg is 800. Each CT will get (700 x 10) = 1400 hp.

**Comment by devu4** [comment]
Edit: The formula I used was just example. With more inspection I released my formula isn't very fair either for when there is smaller amounts of CTs.

Maybe search for a good health formula.

**Comment by shanapu** [comment]
ugly code, but it work!   i have something simliar build for last guard rule.

`int HPterrors = 0;
int HPterBuffer = 0;
LoopClients(i) if(IsPlayerAlive(i) && GetClientTeam(i) == CS_TEAM_T)
{
	HPterBuffer = (GetClientHealth(i) + HPterrors);
	HPterrors = HPterBuffer;
	HPterBuffer = 0;
}`

> "sm_lastguard_hp", "50" - How many percent of the combined Terror Health the CT get (3 terror alive with 100HP = 300HP / 50% = CT get 150HP

https://github.com/shanapu/MyJailbreak/blob/master/addons/sourcemod/scripting/MyJailbreak/lastguard.sp#L269-L277
https://github.com/shanapu/MyJailbreak/blob/master/addons/sourcemod/scripting/MyJailbreak/lastguard.sp#L314

**Comment by shanapu** [comment]
So far, I haven't anymore thought about it. Before I going deeper in the "algorithms studies", does anyone has an flashing idea?

**Comment by shanapu** [comment]
how about something like this:

|   	| 1 CT             	| 2 CT             	| 3 CT     	|
|---	|-----------------	|-----------------	|---------	|
| 1 T   	| cvar_HP         	|                 	|         	|
| 2 T   	| + cvar_HP_extra 	| cvar_HP         	|         	|
| 3 T   	| + 2x cvar_HP_extra 	| + cvar_HP_extra 	| cvar_HP 	|
| 3 T   	| + 3x cvar_HP_extra 	| + 2x cvar_HP_extra 	| cvar_HP 	|

on zombie will result in this: 

cvar_HP = 4000HP  |  cvar_HP_extra = 1000HP

|      	| 1 CT    	| 2 CT    	| 3 CT    	| 4 CT    	| 5 CT   	| 6 CT   	| 7 CT   	| 8 CT   	|
|------	|---------	|---------	|---------	|---------	|--------	|--------	|--------	|--------	|
| 1 T  	| 4000HP  	|         	|         	|         	|        	|        	|        	|        	|
| 2 T  	| 5000HP  	| 4000HP  	|         	|         	|        	|        	|        	|        	|
| 3 T  	| 6000HP  	| 5000HP  	| 4000HP  	|         	|        	|        	|        	|        	|
| 4 T  	| 7000HP  	| 6000HP  	| 5000HP  	| 4000HP  	|        	|        	|        	|        	|
| 5 T  	| 8000HP  	| 7000HP  	| 6000HP  	| 5000HP  	| 4000HP 	|        	|        	|        	|
| 6 T  	| 9000HP  	| 8000HP  	| 7000HP  	| 6000HP  	| 5000HP 	| 4000HP 	|        	|        	|
| 7 T  	| 10000HP 	| 9000HP  	| 8000HP  	| 7000HP  	| 6000HP 	| 5000HP 	| 4000HP 	|        	|
| 8 T  	| 11000HP 	| 10000HP 	| 9000HP  	| 8000HP  	| 7000HP 	| 6000HP 	| 5000HP 	| 4000HP 	|
| 9 T  	| 12000HP 	| 11000HP 	| 10000HP 	| 9000HP  	| 8000HP 	| 7000HP 	| 6000HP 	| 5000HP 	|
| 10 T 	| 13000HP 	| 12000HP 	| 11000HP 	| 10000HP 	| 9000HP 	| 8000HP 	| 7000HP 	| 6000HP 	|

so on (ratio 1:4)
3 CT & 12Ts = 13.000HP for CT
2 CT & 8Ts = 10.000HP for CT
1CT & 4Ts = 7.000HP for CT

so on (ratio 1:3)
3 CT & 9Ts = 10.000HP for CT
2 CT & 6Ts = 8.000HP for CT
1CT & 3Ts = 6.000HP for CT

so on (ratio 1:2)
3 CT & 6Ts = 7.000HP for CT
2 CT & 4Ts = 6.000HP for CT
1CT & 2Ts = 5.000HP for CT

on first look seems fair... what you think?

**Comment by devu4** [comment]
I think that looks fair enough.

**Comment by shanapu** [comment]
easier to write than i thought... 😄
