### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by mrkos9i4ok** [shanapu/MyJailbreak#78]
## WARDEN
-Add function +speed
-Add function +health
-Add function take solo freeday
-Add function take mass freeday
-Add function separation on blue and red

## Tags
-Add function changes chat and clan tag in different ways, chatting to one another clan tag
-Add support for morecolors

## Extras menu

>## Gangs
>-Add gangs

>## Shop
>-Add ct and t shop

>## Rebel set
>-Add rebel set

**Comment by shanapu** [comment]
hi, thanks for your suggestion! any idea or critic is welcome!
please try to explain all ideas / bugs so detailed as you can. Thank you!

> -Add function +speed
So the warden can set speeds? like x0,5 x1,2 x2,0? Or toggle speed like freeze & walk ?
Is the speed for the warden? Or specific terrorist or all terrors? Or CT?

> -Add function +health
You know about !heal for terrorist so they became a healthshot? 
Here simliar questions:
So the warden can set heatlh? like +10hp, +25hp, +50hp? Or function to set hp to 100hp ?
Is the health for the warden? Or specific terrorist or all terrors? Or CT?

> -Add function take solo freeday
Already asked here and also included in 6.0 - you can already use dev.6.0

> -Add function take mass freeday
What should be the function/difference of this mass freeday? 

> -Add function separation on blue and red
to this I already recommend KissLicks TeamGames
https://github.com/KissLick/TeamGames/wiki/Teams

> -Fix skins(http://hlmod.ru/threads/plaginy-personal-skins-i-custom-player-skins-konfliktujut-ne-vydajotsja-nuzhnyj-skin.36081/)
what is broken with skins? even with google translate I don't understand russian...
I know "Include" and i know the had problems with "personal-skins".
Use [sm_skinchooser](https://forums.alliedmods.net/showthread.php?p=780243) . Tested with no conflicts.

> -Delete freeday
`sm_freeday_enable: 0` or move `plugins/MyJailbreak/freeday.smx` to `plugins/disabled`

> -Add function changes chat and clan tag in different ways, chatting to one another clan tag
you mean e.g 
stats: 
`[warden] shanapu` 
& chat 
`[The great warden] shanapu` ?

> -Add support for morecolors
I will take a closer look at morecolors, muticolors, ColorVariables & colors is near future and compare them.

gangs, JBShop &/or dice will MAYBE come in far far future.

> -Add rebel set
good idea. i will make a menu item and a warden command to make a terror rebel


Please for future ideas / issue. Use on issue per request. thank you!

**Comment by mrkos9i4ok** [comment]
`like x0,5 x1,2 x2,0`
`like +10hp, +25hp, +50hp`
`What should be the function/difference of this mass freeday?`
solo freeday take one player,mass freeday take all players
`what is broken with skins? even with google translate I don't understand russian...
I know "Include" and i know the had problems with "personal-skins".
Use sm_skinchooser . Tested with no conflicts.`
https://github.com/shanapu/MyJailbreak/issues/80
`you mean e.g 
stats: 
[warden] shanapu 
& chat 
[The great warden] shanapu ?`
yes

**Comment by Include5** [comment]
> solo freeday take one player,mass freeday take all players

Use Event freeday. personal freeday will be in version 6.0

**Comment by shanapu** [comment]
-Add function changes chat and clan tag in different ways, chatting to one another clan tag
you mean e.g 
stats: 
[warden] shanapu 
& chat 
[The great warden] shanapu

done
https://github.com/shanapu/MyJailbreak/commit/d1b4efebe01a9ebb7a21cc7ec60a4726205720d2

**Comment by mrkos9i4ok** [comment]
## Warden
>Make a function selection command or cmd players vote

**Comment by shanapu** [comment]
>Make a function selection command or cmd players vote
>Add mute prisoners n sec

sry don't understand. both is there?

**Comment by mrkos9i4ok** [comment]
>сры не понимаю. как там?

>Make a function selection command or cmd players vote
In the early rounds to get out the window kt players , for whom more than vote , and he becomes cmd
>Add mute prisoners n sec
The CMD menu item has to stir up the players , when you press for example is given to players mut 40 seconds

**Comment by Include5** [comment]
Сразу видно, что используешь гугл переводчик :camel:

**Comment by mrkos9i4ok** [comment]
>WARDEN
-Add function +speed
-Add function +health
-Add function separation on blue and red

?

**Comment by shanapu** [comment]
like 9 post above:
please answer all my question so detailed as you can.

> -Add function +speed

So the warden can set speeds? like x0,5 x1,2 x2,0? Or toggle speed like freeze & walk ?
Is the speed for the warden? Or specific terrorist or all terrors? Or CT?


> -Add function +health

You know about !heal for terrorist so they became a healthshot? 
Here simliar questions:
So the warden can set heatlh? like +10hp, +25hp, +50hp? Or function to set hp to 100hp ?
Is the health for the warden? Or specific terrorist or all terrors? Or CT?

> -Add function separation on blue and red

to this I already recommend KissLicks TeamGames
https://github.com/KissLick/TeamGames/wiki/Teams

but maybe i will include such a feature in far future. added to issuses

**Comment by mrkos9i4ok** [comment]
>-Add function +speed
The CMD menu item is added to the speed of + - where if you turn off the normal rate increased when the
>-Add function +health
Same as in speed, but can not be disabled and are always cmd for example 150 hp

**Comment by shanapu** [comment]
> -Add function +speed

Is the speed for the warden? Or specific terrorist or all terrors? Or CT?


> -Add function +health

You know about !heal for terrorist so they became a healthshot? 
Is the health for the warden? Or specific terrorist or all terrors? Or CT?

**Comment by mrkos9i4ok** [comment]
Only warden

**Comment by mrkos9i4ok** [comment]
In a request to add an item to give the reason for the refusal?

**Comment by shanapu** [comment]
> Please for future ideas / issue. Use one issue per request. thank you!

I thought about +speed & +health and talk with friends & other serveradmins. In our view this would be very unbalanced and not realy fit into MyJB. So I decided not implement this feature in MyJB. 

maybe someone is willing to write it as standalone plugin. should be very easy with the warden api.

>In a request to add an item to give the reason for the refusal?

(like always) I don't understand what you mean/want.
Please strive to write better understandable english. Explain your ideas with more details. 
**Im not a mindreader!**
