### ISSUE TITLE
Skins

### ISSUE THREAD

**Issue by mrkos9i4ok** [shanapu/MyJailbreak#80]
A have problem:skins don`t worked:zombi,chicken etc
After cmd survives, the skin becomes in the next round is not cmd but the simple CT, just do not work VIP skins (current 1 round)

**Comment by Include5** [comment]
sm_skinchooser?

**Comment by mrkos9i4ok** [comment]
CustomPlayerSkins + personal_skins

**Comment by Include5** [comment]
If you know Russian , read it
http://hlmod.ru/threads/plaginy-personal-skins-i-custom-player-skins-konfliktujut-ne-vydajotsja-nuzhnyj-skin.36081/

> CustomPlayerSkins + personal_skins

Add me to Skype my login zerald20
try to understand

**Comment by mrkos9i4ok** [comment]
Thanks u 
With the help of Google translator I knew how to fix
