### ISSUE TITLE
Error Ratio

### ISSUE THREAD

**Issue by mrkos9i4ok** [shanapu/MyJailbreak#81]
There was such a mistake that players can only enter 1 for CT and 3 per T, in the config file, and most of them will not let

**Comment by Include5** [comment]
Пожалуйста, пиши лучше на Русском, твой инглиш из соу бад.

**Comment by mrkos9i4ok** [comment]
>Пожалуйста, пиши лучше на Русском, юр инглиш из соу бад

Ошибка,что когда уже 1 кт и 3 т играют,больше игроки не могут присоединиться к команде

**Comment by Include5** [comment]
> Ошибка,что когда уже 1 кт и 3 т играют,больше игроки не могут присоединиться к команде

Я уже понял :) Написал создателю, ждём решение. Раньше у меня такого не было... Какую версию ты используешь?

**Comment by mrkos9i4ok** [comment]
>Я уже понял :) Написал создателю, ждём решение. Раньше у меня такого не было... Какую версию ты используешь?

Последний релиз 5.2

**Comment by shanapu** [comment]
what? can you provide an english translation to your conversation?
Please talk private in russian.

**Comment by mrkos9i4ok** [comment]
Так и не нашли решение...
