### ISSUE TITLE
Ratio

### ISSUE THREAD

**Issue by mrkos9i4ok** [shanapu/MyJailbreak#82]
Error that when it is 1 CT and 3 T playing more players can not join the team

**Comment by shanapu** [comment]
an not join the which team? both? restricted to 4 players?  PLEASE explain more detailed!  i don't have this issue.... 
what's is your ratio?
any errors in log files? 
which plugins do you also use? `sm plugins list`

**Comment by mrkos9i4ok** [comment]
The error is in Ratio
`[SM] Listing 78 plugins:
  01 "SM Admin List Advanced" (v3.0)
  02 "[CS:GO] SpawnTools7" (1.0.1)
  03 "SM_Hosties v2" (2.2.3)
  04 "Thirdperson Mode" (2.2) by Zephyrus & Justkasi
  05 "Basic Chat" (1.8.0.5916) by AlliedModders LLC
  06 "Smart Jail Doors" (0.5.2-beta)
  07 "SourceBans" (1.5.1) by SourceBans Development Team
  08 "Basic Info Triggers" (1.8.0.5916) by AlliedModders LLC
  09 "HostName Rus" (1.0.0) by GoDtm666
  10 "Rock The Vote Extended" (1.10.0)
  11 "RoundEndSound" (1.1.2) by GoDtm666 (www.MyArena.ru)
  12 "MyJailbreak - NoScope" (Beta 5.2) by shanapu
  13 "MyJailbreak - Core" (Beta 5.2) by shanapu
  14 "MyJailbreak - Weapons" (Beta 5.2) by shanapu, Franc1sco
  15 "MyJailbreak - Warden" (Beta 5.2) by shanapu, ecca, ESKO & .#zipcore
  16 "MyJailbreak - CowBoy" (Beta 5.2) by shanapu
  17 "MyJailbreak - DealDamage" (Beta 5.2) by shanapu
  18 "MyJailbreak - Suicide Bomber" (Beta 5.2) by shanapu
  19 "MyJailbreak - HideInTheDark" (Beta 5.2) by shanapu
  20 "MyJailbreak - KnifeFight" (Beta 5.2) by shanapu
  21 "MyJailbreak - PlayerTags" (Beta 5.2) by shanapu
  22 "MyJailbreak - Zeus" (Beta 5.2) by shanapu
  23 "MyJailbreak - War FFA" (Beta 5.2) by shanapu
  24 "MyJailbreak - Ratio" (Beta 5.2) by shanapu, Addicted
  25 "MyJailbreak - Torch & OnTorch" (Beta 5.2) by shanapu
  26 "MyJailbreak - Last Guard Rule" (Beta 5.2) by shanapu
  27 "MyJailbreak - Menus" (Beta 5.2) by shanapu, Franc1sco
  28 "MyJailbreak - DuckHunt" (Beta 5.2) by shanapu
  29 "MyJailbreak - Drunk" (Beta 5.2) by shanapu
  30 "MyJailbreak - War" (Beta 5.2) by shanapu
  31 "MyJailbreak - Zombie" (Beta 5.2) by shanapu
  32 "MyJailbreak - Freeday" (Beta 5.2) by shanapu
  33 "MyJailbreak - Catch & Freeze" (Beta 5.2) by shanapu
  34 "MyJailbreak - Request" (Beta 5.2) by shanapu
  35 "MyJailbreak - HEbattle" (Beta 5.2) by shanapu
  36 "Skins" (1.6)
  37 "Player Commands" (1.8.0.5916) by AlliedModders LLC
  38 "Admin Help" (1.8.0.5916) by AlliedModders LLC
  39 "Disable HUD money" (1.0) by Pheonix (‰7Феникс7‰)
  40 "Flashlight" (1.3.63)
  41 "Admin Menu" (1.8.0.5916) by AlliedModders LLC
  42 "CT Ban" (1.6.1.3) by databomb
  43 "[VIP] Regen HP" (1.0.4) by R1KO
  44 "[VIP] Skins" (1.0.5) by R1KO (skype: vova.andrienko1)
  45 "[VIP] Bhop" (1.0.0) by KOROVKA
  46 "[VIP] HP" (1.0.0) by R1KO (skype: vova.andrienko1)
  47 "[VIP] Armor" (1.0.1) by R1KO (skype: vova.andrienko1)
  48 "[VIP] Speed" (1.0.0) by R1KO (skype: vova.andrienko1)
  49 "[VIP] Vips Online" (1.0.1) by R1KO (skype: vova.andrienko1)
  50 "[VIP] Test" (1.0.3) by R1KO (skype: vova.andrienko1)
  51 "[VIP] Core" (2.0.1 DEV (build 19072016-1)) by R1KO (skype: vova.andrienko1)
  52 "[VIP] Trails (CS:GO)" (1.0.0) by R1KO
  53 "[VIP] Gravity" (1.0.0) by R1KO (skype: vova.andrienko1)
  54 "Admin File Reader" (1.8.0.5916) by AlliedModders LLC
  55 "Anti-Flood" (1.8.0.5916) by AlliedModders LLC
  56 "CSGO Sprays" (1.4.1)
  57 "Basic Commands" (1.8.0.5916) by AlliedModders LLC
  58 "[CSGO] Team Limit Bypass" (1.1) by Zephyrus
  59 "Fun Commands" (1.8.0.5916) by AlliedModders LLC
  60 "Simple Chat Processor (Redux)" (2.0.2) by Simple Plugins, Mini
  61 "Default SM Text Replacer" (0.32.GO) by Mitch/Bacardi
  62 "Player Cleaner" (1.0) by White Wolf (HLModders LLC)
  63 "Voice Comm" (2.2.1) by databomb
  64 "Hook Grab Rope" (1.1.5)
  65 "Client Preferences" (1.8.0.5916) by AlliedModders LLC
  66 "Basic Votes" (1.8.0.5916) by AlliedModders LLC
  67 "CS:GO Slots fix" (1.0.0) by www.MyArena.ru
  68 "SwapTeam" (1.2.6) by Rogue - Originally by MistaGee and www.MyArena.ru
  69 "MapChooser Extended" (1.10.2)
  70 "Реклама" (1.2) by Pheonix (‰7Феникс7‰)
  71 "Basic Comm Control" (1.8.0.5916) by AlliedModders LLC
  72 "Radio Spam Block" (1.0.0)
  73 "stacker" (1.0)
  74 "Fun Votes" (1.8.0.5916) by AlliedModders LLC
  75 "Map Nominations Extended" (1.10.0)
  76 "Custom Player Skins (Core)" (1.3.4) by Mitchell, Root
  77 "Welcome Sound" (1.0.1) by GoDtm666 (www.MyArena.ru)
  78 "Rotate server graphic banners" (0.2) by HiTmAnY`

**Comment by mrkos9i4ok** [comment]
AAAAA 

> // This file was auto-generated by AutoExecConfig read and append beta
// ConVars for plugin "MyJailbreak/ratio.smx"


// Set your custom chat command for become guard. no need for sm_ or !
// -
// Default: "ct"
sm_ratio_cmd "ct"

// How many prisoners for each guard.
// -
// Default: "2"
// Minimum: "1.000000"
sm_ratio_T_per_CT "3"

// 0 - disabled, 1 - enable VIPs moved to front of queue
// -
// Default: "1"
// Minimum: "0.000000"
// Maximum: "1.000000"
sm_ratio_flag "1"

// Set the flag for VIP
// -
// Default: "a"
sm_ratio_vipflag "b"

// 0 - disabled, 1 - enable adverstiment for 'VIPs moved to front of queue' when player types !quard 
// -
// Default: "1"
// Minimum: "0.000000"
// Maximum: "1.000000"
sm_ratio_adsvip "1"

// 0 - instandly join ct/queue, no confirmation / 1 - confirm rules / 2 - Qualification questions
// -
// Default: "1"
// Minimum: "0.000000"
// Maximum: "2.000000"
sm_ratio_join_mode "2"

// How many question a player have to answer before join ct/queue. need sm_ratio_join_mode 2
// -
// Default: "3"
// Minimum: "1.000000"
// Maximum: "5.000000"
sm_ratio_questions "1"

**Comment by mrkos9i4ok** [comment]
Without balance everything works fine

**Comment by mrkos9i4ok** [comment]
In my command sm_ratio_T_per_CT don`t worked,always 3 t per 1 ct

**Comment by mrkos9i4ok** [comment]
im am stupid xD
