### ISSUE TITLE
Divide prisoners to red / blue

### ISSUE THREAD

**Issue by shanapu** [shanapu/MyJailbreak#83]
I always recommend [KissLicks TeamGames](https://github.com/KissLick/TeamGames/wiki/Teams) but people still asking for this feature. maybe sometime time I'm bored i will do this.

**Comment by Include5** [comment]
I have can not compile :/

**Comment by shanapu** [comment]
common include... 
**i will not help anymore if you guys dont give me any infos....**    
What are the errors on compile?

also here the compiled files...
https://github.com/KissLick/TeamGames/issues/26

**Comment by Include5** [comment]
> common include... 
i will not help anymore if you guys dont give me any infos....
What are the errors on compile?

http://imgur.com/rqv2Ih6
Everything is included there

> also here the compiled files...
KissLick/TeamGames#26

thx ;)

**Comment by Include5** [comment]
In fact, this function is better than TeamGameS. :)

**Comment by TiBarification** [comment]
Use this algorythm
```sourcepawn
bool red;
for (int i = 1; i <= MaxClients; ++i)
{
	if (IsClientInGame(i) && GetClientTeam(i) == CS_TEAM_T && IsPlayerAlive(i))
	{
		SetEntityRenderMode(i, RENDER_TRANSCOLOR);
		
		red = !red;
		if (red)
			SetEntityRenderColor(i, 255, 0, 0, 255);
		else
			SetEntityRenderColor(i, 0, 0, 255, 255);
	}
}

**Comment by shanapu** [comment]
Thx for the code snippet.
i think i will do this like kisslick with the opportunity to set single players team too.

**Comment by shanapu** [comment]
I won't do this for myjb beta, yet. Myjailbreak works good with TeamGames.

I'm sry
