### ISSUE TITLE
[BUG]Personal freeday

### ISSUE THREAD

**Issue by Include5** [shanapu/MyJailbreak#85]
The terrorists have a menu function to give a personal freeday. But when you select it, nothing happens
![default](https://cloud.githubusercontent.com/assets/20662946/17270754/5db964be-5673-11e6-8042-2f9876809686.png)
![2](https://cloud.githubusercontent.com/assets/20662946/17270755/5db9c648-5673-11e6-8772-04cc491a427b.png)
![3](https://cloud.githubusercontent.com/assets/20662946/17270756/5dbc3dc4-5673-11e6-9fee-8ee7f46a6f06.png)

Выдачу игроку фридей - Give a personal freeday

**Comment by shanapu** [comment]
ok, i made a mistake, i insert "give freeday" to menu for admin with flag "sm_menu_flag" but hadn't include a admin check tp the command !givefreeday.

Question: should admin could give personal freeday or only available for warden?

**Comment by Include5** [comment]
I think only for warden.

**Comment by Include5** [comment]
Can you add a second warden ? Players it is very necessary. So, can you make a cvar to give a personal freeday at the begining rounds, but not in the next round

**Comment by shanapu** [comment]
**only one bug/request per issue!**

https://github.com/shanapu/MyJailbreak/commit/5eb6ce406dbf4ac185727d1089c56a46e8e1f567 fixed issue and opened [a new issue](https://github.com/shanapu/MyJailbreak/issues/87) for your request...
