### ISSUE TITLE
[6.0]Bugs

### ISSUE THREAD

**Issue by mrkos9i4ok** [shanapu/MyJailbreak#86]
>->HUD not shown
>->Questions for the team to qualify for the special forces are not completely written
![20160730215512_1](https://cloud.githubusercontent.com/assets/20227450/17272509/8de0cc0e-56a0-11e6-8f73-85c5b44cdaa0.jpg)
>->https://github.com/shanapu/MyJailbreak/issues/85
>->Chat tags don`t work,clan tags work
>->...If I find another, I will add here

**Comment by Include5** [comment]
> ->HUD not shown

Use it http://rgho.st/7MXbBtNKP
Password: MYJB

> ->Questions for the team to qualify for the special forces are not completely written


The size of the Latin characters - 1 bytes, the size of the Cyrillic character - 2 bytes. In the message it fits in Latin characters twice.

> ->#85

will be fixed

> ok, i made a mistake, i insert "give freeday" to menu for admin with flag "sm_menu_flag" but hadn't include a admin check to the command !givefreeday.

Question: should admin could give personal freeday or only available for warden?

->Chat tags don`t work,clan tags work

Need more infos

If you have more questions, add in skype zerald20

**Comment by mrkos9i4ok** [comment]
At the beginning of the game Fridey sets round time of 5 00, but does not return the server settings of the round.

**Comment by shanapu** [comment]
please like i said before **only one bug/request per issue**!

HUD fixed  https://github.com/shanapu/MyJailbreak/commit/aafa64d894b8b2e3ac2e75879e63ea89a65e4972

>Questions for the team to qualify for the special forces are not completely written

Bug already reported here https://github.com/shanapu/MyJailbreak/issues/55
Include could you shorten the translations to fit in until I find a working solution to this issue?

>At the beginning of the game Freedey sets round time of 5 00, but don`t return the server settings of the round.

Im stupid,... fixed https://github.com/shanapu/MyJailbreak/commit/974d5971bd22d89311ed576ac2ba8f685ebf6442
Thanks for report

>Chat tags don`t work,clan tags work
works for me without issue... maybe you done a typo in phrases.txt?
