### ISSUE TITLE
Warden Deputy

### ISSUE THREAD

**Issue by shanapu** [shanapu/MyJailbreak#87]
Many times requested.. A Warden Deputy.
How should it look like? What features in contrast to warden?

**Comment by Include5** [comment]
Green color/skin
the ability to be divided into colors
markers
quiz
handcuffs

**Comment by shanapu** [comment]
Deputy set by warden?
Deputy random after a player warden?
Deputy by command?

**Comment by mrkos9i4ok** [comment]
Deputy by command?

**Comment by Include5** [comment]
Deputy set by warden?

**Comment by shanapu** [comment]
what happend to deputy when warden dies? 
deputy -> new warden
no more deputy

**Comment by Include5** [comment]
deputy -> new warden

**Comment by shanapu** [comment]
Done so far. Player can become deputy(cvar) when there is a warden. Warden can set player as deputy(cvar). Deputy has all warden features included per cvar. Deputy has his own menu, PlayerTag, protection from moving to T(ratio), receive refuse and repeat panels & can give personal freedays.

- deputy can't set eventdays
- deputy don't get a TA & health on with !weapons
- deputy can't start eventday voting
- deputy can't receive requests (to answer) except those panel above.
- deputys bulletsparks are smaller
- deputy don't have warden random color change feature, only solid color
- admin can't remove deputy
- if sm_warden_deputy_set **"0"** (0 - disabled, 1 -  warden can choose his deputy) the warden can't remove deputy

Is anything of these `can't & don't` needed?

**Comment by shanapu** [comment]
> admin can't remove deputy
> [...]the warden can't remove deputy
I will implement this `!removedeputy` definitely, tommorow... ...good night

**Comment by shanapu** [comment]
seems 'everything' is good
