### ISSUE TITLE
invisible tt

### ISSUE THREAD

**Issue by krysti500** [shanapu/MyJailbreak#9]
i have problem :/

After install this players in tt are invisibe.
I must use zeus

**Comment by shanapu** [comment]
> After install this players in tt are invisibe.

oO? MyJailbreak don't touch the terror player models/skins, only in 'Duckhunt' ... What plugins do you have also running?

> I must use zeus

Sorry what do you mean? use taser?

**Comment by bchewy** [comment]
Weird after hearing that someone has this problem as well, I did notice that some of my terrorists have invisible models.

I'm not very sure what's causing this but i'll look into it and get back to you here.

**Comment by krysti500** [comment]
Sorry my fail i fix this
