### ISSUE TITLE
Stuck in war

### ISSUE THREAD

**Issue by rsgua** [shanapu/MyJailbreak#93]
Stuck in war. When round start all ter stuck. Can you change cvar mp_solid_teammates 0 when game start?

**Comment by devu4** [comment]
shanapu, this occurs on all eventdays when there is 1 guard and 1 terrorist. I think it is because day starts and then because LR is enabled it ends and players are still in each other when LR is forced.

**Comment by shanapu** [comment]
> this occurs on all eventdays when there is 1 guard and 1 terrorist.

but he talks about "all ter stuck".
I can reproduce the situation that you explain with `sm_war_allow_lr 1` , but I think this is a different issue to that what rsgua talk about, when he explained his problem right. And also if I reproduce this I don't stuck, but have an issue with starting & ending event day like that needs to be fixed.

**Comment by shanapu** [comment]
https://github.com/shanapu/MyJailbreak/commit/d8dc396271d8cfa48073c0fb08db913a18f17197 this will fix the issue @devu4 explained. 

@rsgua could you give some more information or was `sm_war_freezetime` the "problem"?
