### ISSUE TITLE
[Request] Disable Ratio on Admin Command

### ISSUE THREAD

**Issue by SirConor** [shanapu/MyJailbreak#95]
Hey, 

Wondering if it would be possible to add a cvar to disable automatic ratio on admin join?

**Comment by shanapu** [comment]
Do you mean admin ignores `sm_ratio_T_per_CT` so there would be unbalanced teams?
Or immunity for `sm_ratio_force_t` for admin?
Or admins dont have to pass the `sm_ratio_join_mode` agrrement/questions?
Or admins ignore the guardqueue and join instandly to CT?
Or admins get higher priority than VIP in the guardqueue?

or all of them?

**Comment by SirConor** [comment]
If Admin with certain Flag joins it disables the ratio so if an admin swaps or moves player that go over the ratio that has been set it doesn't try and fix the ratio.

**Comment by shanapu** [comment]
got it!
A admin command to toggle the ratiocheck will be implement in next update!
Thanks for your suggestion!

**Comment by shanapu** [comment]
i think an automatic disable check with flag would be cause to many troubles and missunderstoodments. 
Everytime a admin connects it disable the ratio check would be weired.

**Comment by shanapu** [comment]
and i will do this to:

> Or immunity for sm_ratio_force_t for admin?
> Or admins dont have to pass the sm_ratio_join_mode agrrement/questions?

**Comment by shanapu** [comment]
here is a first version for testing:

https://raw.githubusercontent.com/shanapu/MyJailbreak/56daa9cb5b05b1ab2f5b1ad7fc0089979d952d73/addons/sourcemod/scripting/MyJailbreak/ratio.sp

https://raw.githubusercontent.com/shanapu/MyJailbreak/56daa9cb5b05b1ab2f5b1ad7fc0089979d952d73/addons/sourcemod/translations/MyJailbreak.Ratio.phrases.txt

https://github.com/shanapu/MyJailbreak/blob/56daa9cb5b05b1ab2f5b1ad7fc0089979d952d73/addons/sourcemod/plugins/MyJailbreak/ratio.smx?raw=true


these are the new cmds & cvars:
    *  new command - sm_ratio - Allows the admin toggle the ratio check and player to see if ratio is enabled
    *  new cvar - sm_ratio_disabled - Allow the admin to toggle 'ratio check & autoswap' on/off with !ratio
    *  new cvar - sm_ratio_disbaled_announce - Announce in a chatmessage on roundend when ratio is disabled

if you come form 6.1 and not the develop branch this is also new:
*  Ratio: Force player on connect or mapstart to terror team
    *  new cvar - sm_ratio_force_t 0 - disabled, 1 - force player on connect to join T side
