### ISSUE TITLE
Freekill report shows different Names

### ISSUE THREAD

**Issue by good-live** [shanapu/MyJailbreak#97]
Sometimes the Freekill report marks a completely different user as killer.

U should definitly work with userid's here:
https://github.com/shanapu/MyJailbreak/blob/master/addons/sourcemod/scripting/MyJailbreak/request.sp#L209

As clientid's change upon reconnect (and get reassigned to a different client)

**Comment by shanapu** [comment]
this commit should fix this issue
Like always, big Thanks for your help!
