### ISSUE TITLE
Core: Add Team Name

### ISSUE THREAD

**Issue by mrkos9i4ok** [shanapu/MyJailbreak#98]
For example, a CT scan will be Guards, and T will be Prisoners

**Comment by shanapu** [comment]
add this to your .cfg

mp_teamname_1 Guards
mp_teamname_2 Prisoner

**Comment by mrkos9i4ok** [comment]
Not working.

**Comment by devu4** [comment]
It does work, make sure you are adding in the right cfg file. The game mode -server.cfg is best as it is executed last.
