### ISSUE TITLE
Hud: Error displaying

### ISSUE THREAD

**Issue by mrkos9i4ok** [shanapu/MyJailbreak#99]
When writing information about the next round,not everything fits in the frame.
![default](https://cloud.githubusercontent.com/assets/20227450/17364956/ee897414-598b-11e6-8af3-e96ba36bf1f8.png)

**Comment by shanapu** [comment]
Already reported here: https://github.com/shanapu/MyJailbreak/issues/55 and here: https://github.com/shanapu/MyJailbreak/issues/86

Use shorter ru translation. until we find a fix.

**Comment by mrkos9i4ok** [comment]
Okey
